Docs/MoltenVK_Runtime_UserGuide.md

GitHub seems to not like markdown without spaces after the `#`-characters.
The [current CommonMark spec](http://spec.commonmark.org/0.27/#atx-headings) says "The opening sequence of # characters must be followed by a space or by the end of line."
This makes these headings render like normal headings on GitHub.

Fix up broken markdown

---

Common/MVKLogging.h
MoltenVK/MoltenVK/Utility/MVKFoundation.h

This will make the compiler point out improper formatting of variadic functions.

Add printf-like macros to MVKLogImpl and mvkNotifyErrorWithText.

---

MoltenVKShaderConverter/MoltenVKSPIRVToMSLConverter/SPIRVToMSLConverter.cpp

SPIRV-Cross supports the macro `SPIRV_CROSS_EXCEPTIONS_TO_ASSERTIONS` for builds with exceptions disabled. MoltenVK support is just a couple #if statements. When exceptions are disabled, the program will just abort, not throw.

Wrap try/catch blocks for if exceptions disabled

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/Commands/MVKCommandEncodingPool.h
MoltenVK/MoltenVK/Commands/MVKCommandEncodingPool.mm
MoltenVK/MoltenVK/Commands/MVKCommandPipelineStateFactoryShaderSource.h
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.h
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.mm

This fixes #62.
* Vulkan allows any valid copy regions to be used in this function. However, Metal's blit command encoder only allows copy offsets and sizes which are multiples of 4 bytes on macOS.
* Before this change, attempting to copy such a region would cause Metal validation errors to trigger.
* This adds logic to detect such copy regions and uses a special compute shader to perform a byte-by-byte copy from the source buffer to the destination buffer with the appropriate offsets.
* This new code path is only needed on macOS, because iOS does not share the same copy region restrictions.
@billhollings This is my first submission, so please let me know if there's something I have missed, or something I should be doing differently. I've tried to match the patterns and style that are …

Fix vkCmdCopyBuffer when copying unaligned regions.

---

MoltenVK/MoltenVK/Vulkan/vulkan.mm

In order to determine the instance version, the 1.1 loader takes advantage of the fact that a 1.0 ICD will return NULL for vkGetInstanceProcAddr(NULL, "vkEnumerateInstanceVersion")

Fix vkGetInstanceProcAddr to work with 1.1 loader

---

MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm
MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm

Wrap each queue submission in a dedicated @autoreleasepool.
Fix memory leak during creation of global format mappings.

Fix memory issues.

---

fetchDependencies

Changes to fetchDependencies script:
- remove -sdk option
- Add --v-lvl-root and --glslang-root options (with an arg)
that allow caller to pass in the root dir of these two repos
if the caller already has them.  The script then symlinks to
these instead of fetching and building.
Fixes: #79 #84

fetchDeps: remove -sdk. New opts for LVL, glslang trees

---

MoltenVK/MoltenVK/API/mvk_datatypes.h
MoltenVK/MoltenVK/Utility/MVKFoundation.h
MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm

Round up row and layer byte counts when copying compressed images with sizes that are not integer multiples of block size.

---

fetchDependencies

Using a symlink to locate an externally-built glslang
doesn't work if the parent directory of the externally-built
glslang isn't the same as the parent here (External).
This fixes a portability warning when building from V-LVL
because the parent there was "external" vs "External".
Copy is still a win because it is better than fetching and
building.

fetchDeps: Copy glslang instead of symlink

---

README.md
fetchDependencies

If the ninja build system is installed, ask CMake to generate Ninja build files and use
it for the build.
[Ninja](https://ninja-build.org) is globally faster than Make, and automatically parallelize builds depending on the number of CPUs in the system.
On my machine, the execution time of `fetchDependencies` drops from ~10 minutes to ~1 min 30 when ninja is used.

fetchDependencies: Use ninja if available to build dependencies

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm
MoltenVK/MoltenVK/GPUObjects/MVKSync.h
MoltenVK/MoltenVK/GPUObjects/MVKSync.mm
MoltenVK/MoltenVK/Utility/MVKBaseObject.h
MoltenVK/MoltenVK/Vulkan/vulkan.mm

Support deferred secondary signaling of semaphore & fence acquired while image is free.
Add MVKBaseObject::destroy() function to support customization of object destruction.
Support deferred destruction of MVKSemaphore & MVKFence instances.
Fixes Issue #95.

Add workaround for apps that use one semaphore for all swapchain images.

---

README.md

python3 is renamed to python in Homebrew formula. [Link](https://docs.brew.sh/Homebrew-and-Python)
>> Homebrew provides one formula for Python 3.x (python) and another for Python 2.7.x (python@2).

Update python brew install command

---

MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm
MoltenVK/MoltenVK/Utility/MVKOSExtensions.h
MoltenVK/MoltenVK/Utility/MVKOSExtensions.mm

 Don't use CAMetalLayer displaySyncEnabled property if it is not available.

---

Docs/MoltenVK_Runtime_UserGuide.md
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.h
MoltenVK/MoltenVK/Commands/MVKCommandPool.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm
README.md

Update docs to indicate support for Vulkan 1.0, instead of 1.1. Fixes issue #144.

Remove mutex locks on MVKDescriptorPool.

---

MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
MoltenVK/MoltenVK/GPUObjects/MVKShaderModule.h
MoltenVK/MoltenVK/GPUObjects/MVKShaderModule.mm
MoltenVK/MoltenVK/GPUObjects/MVKSurface.mm
MoltenVK/MoltenVK/GPUObjects/MVKSync.h
MoltenVK/MoltenVK/GPUObjects/MVKSync.mm
MoltenVK/MoltenVK/Utility/MVKBaseObject.cpp
MoltenVK/MoltenVK/Utility/MVKBaseObject.h
MoltenVK/MoltenVK/Utility/MVKOSExtensions.h

Move surface access to UI components to main thread.
Fix deadlock possibility between MVKFence and MVKFenceSitter.
Fix handling of locking on deferred-destruction objects.
Update MoltenVK version to 1.0.9.

Synchronization and threading fixes.

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm

Without this, clearing a depth stencil image causes a runtime crash with this message:
```
-[MTLRenderPipelineDescriptorInternal validateWithDevice:]:2400: failed assertion `No valid pixelFormats set.'
```
The fix is to simply keep track of the pixel format here.

Fix an issue where the depth format in MVKCmdClearImage was not getting set correctly.

---

fetchDependencies

Add --v-headers-root, --spirv-cross-root,
and --glslang-root options with an arg that allow
caller to pass in the root dir of these three
repos if the caller already has them.  The script
then symlinks to these instead of fetching and building.

fetchDeps: Add flags for pre-built repos

---

MoltenVK/MoltenVK/API/mvk_datatypes.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/OS/CAMetalLayer+MoltenVK.m
MoltenVK/MoltenVK/OS/MTLSamplerDescriptor+MoltenVK.m
MoltenVK/MoltenVK/OS/MTLTextureDescriptor+MoltenVK.m

Retrieve workgroup sizesVkPhysicalDeviceLimits::maxComputeWorkGroupSize & maxComputeWorkGroupInvocations & maxComputeSharedMemorySize from MTLDevice.
Fixes issue #198.

Report correct workgroup sizes from MTLDevice.

---

MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

When vertex shader translation fails, we were already calling setConfigurationResult, but we were not doing this for fragment shaders.

CreatePipelines should not return SUCCESS when MSL translation fails.

---

MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm

VK_FORMAT_A2B10G10R10_SNORM_PACK32 as a vertex attribute has the MoltenVK equivalent of MTLVertexFormatInt1010102Normalized. This pull request adds this missing format.
Note: We have tested this on MacOS only, its not clear if this works on iOS as well.

new vertex format VK_FORMAT_A2B10G10R10_SNORM_PACK32

---

Docs/MoltenVK_Runtime_UserGuide.md
Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKInstance.h
MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueryPool.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueue.h
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm
MoltenVK/MoltenVK/GPUObjects/MVKShaderModule.h
MoltenVK/MoltenVK/GPUObjects/MVKShaderModule.mm
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm
MoltenVK/MoltenVK/GPUObjects/MVKSync.mm
MoltenVK/MoltenVK/Utility/MVKEnvironment.h
MoltenVK/MoltenVK/Vulkan/vk_mvk_moltenvk.mm

Add MVKConfiguration and deprecate MVKDeviceConfiguration.
Add vkGetMoltenVKConfigurationMVK() and deprecate vkGetMoltenVKDeviceConfigurationMVK().
Add vkSetMoltenVKConfigurationMVK() and deprecate vkSetMoltenVKDeviceConfigurationMVK().
Add build setting overrides for all initial MVKConfiguration member values.
Update to MoltenVK version 1.0.19.
Update to VK_MVK_moltenvk spec version 7.

Move MoltenVK config to instance instead of device.

---

MoltenVK/MoltenVK/Commands/MVKCommandPool.h
MoltenVK/MoltenVK/Commands/MVKCommandPool.mm
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm
MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm
MoltenVK/MoltenVK/Loader/MVKLayers.mm
MoltenVK/MoltenVK/Vulkan/vulkan.mm

Much of this was already supported, simply by being supported by Metal.
Of course, this support is incomplete: Metal doesn't yet allow you to
create a 2D texture view from a 3D texture.

Support the VK_KHR_maintenance1 extension.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm
MoltenVK/MoltenVK/Loader/MVKLayers.mm
MoltenVK/MoltenVK/Vulkan/vulkan.mm

This extension is a prerequisite for multiple other extensions, the
`VK_KHR_push_descriptor` extension in particular.

Support the VK_KHR_get_physical_device_properties2 extension.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

The problem is that on 64-bit platforms (i.e. every platform we support)
there will be padding between the `sType` and `pNext` members of any
extensible Vulkan structure, because `sType` is only 4 bytes while
`pNext` is 8 (and needs 8-byte alignment).
Should fix a segfault running `vulkaninfo`.

MVKDevice: Fix a segfault walking unknown extension structs.

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

This won't help using these image views from shaders, but it will help
attaching them to framebuffers. (Perhaps we should warn or raise an
error in the former case.)
I've left the warning in `validateImageViewConfig()` in place.

MVKImageView: Create 3D MTLTextureViews for 2D image views of 3D textures.

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm

We're not even running more than one thread, let alone taking advantage
of the new method's automatic threadgroup sizing.

vkCmdFillBuffer: Use the older method to dispatch the compute kernel.

---

MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm

For a copy, the spec requires only that the source and destination
bindings are valid, not that the source has been initialized. If the
source binding hasn't been initialized, then we crash attempting to get
the Metal resources corresponding to the uninitialized descriptors. So,
if the descriptor binding hasn't been initialized, don't try to fetch
Metal resources for it.
Yes, this causes us to accept writes of NULL descriptors (from
templates or otherwise), even though the spec forbids this. I don't know
how to solve this without specializing `writeDescriptorSets()`
specifically for the `VkCopyDescriptorSet` case (thereby duplicating
quite a bit of code). Given the general nature of Vulkan as a framework
that does little to no state validation, I wonder if it's even worth it.

vkUpdateDescriptorSet: Handle copies of uninitialized descriptors.

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/Commands/MVKCommandPipelineStateFactoryShaderSource.h

Just add it to the buffer offset when encoding the command. The reason
for this is that we were using it to index the buffer--which, according
to the C++ spec (on which MSL is based), causes it to be offset by that
many 32-bit words instead of bytes. This caused the buffer to be filled
incorrectly. While Metal does require the offset to be aligned to the
type size (in this case, 4 bytes), Vulkan also requires the offset to
`vkCmdFillBuffer()` to be 4-byte aligned, so this shouldn't run into the
same problem as `vkCmdCopyBuffer()`.

Don't pass the offset to the FillBuffer compute kernel.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

Advertise a couple of features—namely `fullDrawIndexUint32`, and `drawIndirectFirstInstance`—that are already supported.
Also advertise `robustBufferAccess`; we don't really support it directly, but the spec says we have to. I haven't observed any issues with out-of-bounds accesses anyway, and I suspect that Apple wouldn't allow shaders to do crazy destabilizing things to the system, so I think we're OK here. (The feature itself does nothing in MoltenVK.)

Advertise some features we already support

---

MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.h
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

Clients can now set multiple viewports and scissor rects, but without a
geometry shader, it won't be much use. For now, however, we can support
`VK_EXT_shader_viewport_index_layer`, which will make this feature more
useful despite us not having geometry shaders.

Support the multiViewport feature.

---

MoltenVK/MoltenVK.xcodeproj/project.pbxproj
MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm
MoltenVK/MoltenVK/Layers/MVKExtensions.cpp
MoltenVK/MoltenVK/Layers/MVKExtensions.def
MoltenVK/MoltenVK/Layers/MVKExtensions.h
MoltenVK/MoltenVK/Vulkan/vulkan.mm

`#include` this file to define the various bits and pieces needed to
support an extension. Now instead of having to change three places, we
now only need change one.
Also, sort the list of extensions. This list is starting to get a little
long and unruly, so before it gets completely out of hand, let's apply a
little semblance of order to it. The extensions are now arranged in the
following order: first, the Khronos-blessed extensions; then multivendor
extensions; then our (`MVK`) extensions; and finally other vendors'
extensions. These subgroups are sorted alphabetically, as Khronos'
master list is.
I'm not happy about the `MVK_EXTENSION_LAST` kluge. But, C++ apparently
doesn't let you stick a dangling comma on a constructor's initializer
list.

Pull extension definitions into a common file.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

Multisample images can be used as storage images in MSL--in fact, this is the only way they are supported. Writing, however, isn't supported yet. (Multisampled array textures are supported as of Metal 2.1.)
As for storage images without formats, Metal doesn't actually care about that. There's no place in MSL to specify it.

Advertise some more features we already support.

---

MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/OS/MTLRenderPassDescriptor+MoltenVK.h
MoltenVK/MoltenVK/OS/MTLRenderPassDescriptor+MoltenVK.m

These properties were introduced in Metal 2.0 on iOS. (They don't exist
yet on Mac.) Currently, they are only used to constrain the size of the
render target area. Perhaps someday, they may be used to support render
passes with no render target attachments. For now, though, Metal doesn't
support that.

vkRenderPass: Set renderTargetWidth and renderTargetHeight when possible.

---

MoltenVK/MoltenVK/GPUObjects/MVKSync.mm

To avoid a data race. Caught this with `ThreadSanitizer`.

MVKFenceSitter: Put a hash table read behind the lock.

---

MoltenVK/MoltenVK/Commands/MVKCmdQueries.mm

Copying the results could block if the client said to wait. If this
completion handler runs before the one that actually finishes the
queries--and it will if it's scheduled first--it will block
indefinitely, causing a deadlock. Instead, run this on a different
dispatch queue; then the query will be allowed to finish.

MVKQueryPool: Shunt copying results off to another thread.

---

MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.h
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.mm

Metal currently requires at least one attachment, in order to define the
size of the render target area (and thus, how many times to run the
fragment shader). Vulkan, however, allows specifying no attachments. In
that case, the size of the render target area comes from the extent and
layer count of the framebuffer object. Since Metal doesn't let you (at
least on macOS) define the render target area without an attachment, we
have to supply a dummy attachment that will be discarded once rendering
is complete.
When possible, the render target uses the memoryless storage mode,
falling back to private when that isn't supported. It is marked as
volatile, and its load and store actions are set to "don't care." The
texture is retained for the lifetime of the subpass.

Add a dummy attachment in case no attachments were specified.

---

MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm

Use the smaller of the render area and the framebuffer area.

Use the passed render area to set the render target extent.

---

MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

Bah. I read the spec wrong. It's hung off the vertex input state, not
the top-level create info.

MVKPipeline: Fix getting the vertex attribute divisor struct.

---

MoltenVK/MoltenVK/GPUObjects/MVKDeviceMemory.mm

Otherwise, if the resource is destroyed first (which it almost always
will be), then when the `VkDeviceMemory` is freed, it will access a
freed resource, at which point it will then proceed to fandango on core.

MVKDeviceMemory: Allow dedicated allocations to forget their resources.

---

MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm

Use `MTLVertexFormatUInt1010102Normalized`. This is the unsigned
equivalent to the signed `MTLVertexFormatInt1010102Normalized`, which we
already use for `VK_FORMAT_A2B10G10R10_SNORM_PACKED`.

Map VK_FORMAT_A2B10G10R10_UNORM_PACKED to an MTLVertexFormat.

---

MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.h
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.mm

Some clients always set blend state for all eight attachments, even if
the attachments are unused. Since the attachments are unused, the
expectation is that the corresponding blend states won't matter. But in
Metal, there's no way to tell if an attachment won't be used. So, if you
enable blending on an unused attachment, its pixel format will be
`MTLPixelFormatInvalid`, which doesn't support blending; Metal will
assert on this.

MVKPipeline: Don't set blend state for unused attachments.

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm

The docs for the `MTLBlitCommandEncoder`'s `copyFromTexture:...` method
state that the source and destination textures must have the same
format.
This was true when it was written in the iOS 8 timeframe
for Metal 1.0. But, I suspect it was changed in Metal 1.1 when support
was added for texture views of differing formats. Like with texture
views, the two formats now need only be compatible. This is the same
behavior that Vulkan prescribes.

vkCmdCopyImage: Allow copies between compatible formats.

---

MoltenVK/MoltenVK.xcodeproj/project.pbxproj
MoltenVKPackaging.xcodeproj/project.pbxproj
Scripts/package_all.sh

When trying to build with scheme "MoltenVK Package (Debug) (macOS only)" on my Mac, it failed at the end with error such as:
/Users/bertel/Library/Developer/Xcode/DerivedData/MoltenVKPackaging-bwwesylglieoalcjcxoqerjnfgqh/Build/Intermediates.noindex/MoltenVKPackaging.build/Debug/MoltenVK-macOS.build/Script-A975D59A2140586700D4834F.sh: line 2: /Volumes/Macintosh: Permission denied
Command PhaseScriptExecution failed with a nonzero exit code
This is because the name of my volume has a whitespace in it: "Macintosh SSD"
With this patch, this step is successful.

Make PhaseScriptExecution works when SRCROOT path has whitespaces.

---

MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm

Set `MTLPixelFormatRG11B10Float` for `VK_FORMAT_B10G11R11_UFLOAT_PACK32`
and `MTLPixelFormatRGB9E5Float` for `VK_FORMAT_E5B9R9G9_UFLOAT_PACK32`.
This should fix the rest of #302.

Correct MTLPixelFormats for a couple of formats.

---

MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
MoltenVKShaderConverter/MoltenVKSPIRVToMSLConverter/SPIRVToMSLConverter.cpp

MVKPipelineLayout set auxiliary buffer MSL index relative to already-calculated
push constant buffer MSL index.
MVKPipeline destructor release auxiliary buffer MTLBuffer instance.
Nudge MVK_VERSION_PATCH.

Update shader caching for compatibility with texture swizzling.

---

MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.mm

Some clients (DXVK primarily) always set all eight color attachments,
even if they are unused. Metal will treat them as though they weren't
specified at all. If none are used, then Metal won't know how big to
make the render area, and the pipeline will fail validation. We have to
treat this case the same as if no attachments were given.

MVKPipeline: Also create a dummy attachment if all attachments are unused.

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

If only some of the 3D image is selected by the view, then we would skip
the usage checks after printing the warning about using a subset.

MVKImageView: Perform the usage check if we're mapping a subset of a 3D image.

---

MoltenVK/MoltenVK.xcodeproj/project.pbxproj
MoltenVK/scripts/create_dylib.sh

Hello, here are some changes to create_dylib.sh, which I had mentioned wanting to submit in #241.
You've already implemented one of the suggestions I wanted to make, which is combining the iOS and macOS scripts into one.
You've introduced a new variable `MVK_ARCH` to tell it what architecture to build for. Xcode already has a variable for that—`ARCHS`—so this PR switches to using that. It also accommodates `ARCHS` containing more than one value, should a universal build ever become relevant.
Since it's a library of C++ code being linked here, do so using clang++ instead of clang; this makes it unnecessary to manually add `-lc++`.
As far as I know it's always unnecessary to add `-lSystem` so remove that too.
And specify which C++ library to use, using the `-stdlib` flag.
I've been using …

create_dylib.sh cleanup

---

MoltenVK/MoltenVK.xcodeproj/project.pbxproj
MoltenVK/scripts/create_dylib.sh
MoltenVKShaderConverter/MoltenVKShaderConverter.xcodeproj/project.pbxproj

Enabling bitcode in Xcode only adds the -fembed-bitcode-marker flag, which doesn't actually create bitcode. The Archive action transforms that flag to -fembed-bitcode which actually creates the bitcode. Adding the User-Defined Setting BITCODE_GENERATION_MODE=bitcode forces bitcode to be created without archiving.

Force Bitcode When Building

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

It isn't. Unfortunately, we have to say it is allowed for linear images,
per the Vulkan spec.

MVKImage: Don't say shared memory is allowed on Mac.

---

MoltenVK/MoltenVK/API/mvk_datatypes.h
MoltenVK/MoltenVK/GPUObjects/MVKBuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKDeviceMemory.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm

This exposes `MTLStorageTypeMemoryless` on iOS as lazily allocated
device-private memory. The semantics of lazily allocated memory are
exactly those of memoryless storage: namely, it can only be used with
images, and only those used as transient attachments. This enables
Vulkan clients to take advantage of this new storage mode starting on
iOS 10.

Add a memory type for memoryless storage on iOS.

---

MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

MVKPipeline: Set the stepRate to 0 when the attribute divisor is 0.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

Also forbid them on multisampled images.

Forbid compressed formats on non-2D images.

---

MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm

Requires Metal 2.1 on Mac. Not supported at all on iOS.
I'm split as to whether or not to have
`mvkMTLTextureTypeFromVkImageType()` return
`MTLTextureType2DMultisampleArray`.

Add support for 2D multisample array textures.

---

MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm

Metal always gives the components in little endian order, while Vulkan
always lists them in big endian order. This also brings us more in line
with the spec, which says that the formats
`VK_FORMAT_R5G6B5_UNORM_PACK16` and `VK_FORMAT_A1R5G5B5_UNORM_PACK16`
must be supported.
Fixes #353.

Correct mapping of packed 16-bit formats.

---

MoltenVK/MoltenVK/Vulkan/vulkan.mm

Since these functions return void, there's no indication of an error
from them.

Explicitly set number of sparse image property/requirement info sets to 0.

---

MoltenVK/MoltenVK/GPUObjects/MVKDeviceMemory.mm

If the device memory is subsequently bound to a `VkBuffer` after it has
been mapped, the heap memory will be freed, leaving dangling pointers in
the client. Instead, create an `MTLBuffer` right away--it is *device*
memory after all--and use its memory.
Another option might be to use `-[MTLDevice
newBufferWithBytesNoCopy:length:options:deallocator:]`, but that
requires that the entire allocation come from a single contiguous
virtual memory mapping, a requirement that is not necessarily satisfied
by `malloc(3)` memory.
Fixes #377.

MVKDeviceMemory: Try creating an MTLBuffer before allocating heap memory.

---

MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.mm

Metal doesn't allow using that as a texture's sampled data type or as a
fragment shader's output type.

Don't use char/uchar for clearing/copying 8-bit formats.

---

MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

Turns out I was wrong. Metal expects at least one attachment to define
the size of the framebuffer, whether or not rasterization is on.

MVKGraphicsPipeline: Add dummy attachments even when rasterization is off.

---

MoltenVK/MoltenVK/Vulkan/vulkan.mm

I was unaware of this method. Mea culpa.
Fixes an out-of-bounds memory access flagged by Address Sanitizer.

Use MVKDevice::getMVKDevice() to get the real underlying device.

---

MoltenVK/MoltenVK/Commands/MVKCommandPipelineStateFactoryShaderSource.h
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.h
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.mm

Only if not multisampling, or multisampling texture arrays are supported.

vkCmdClearAttachments apply [[render_target_array_index]] more carefully.

---

MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

This avoids extra work. It also avoids a race condition flagged by tsan.

MVKPipeline: Set auxiliary buffer offsets once, on layout creation.

---

MoltenVK/MoltenVK/API/mvk_datatypes.h
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/OS/MTLSamplerDescriptor+MoltenVK.h
MoltenVK/MoltenVK/OS/MTLSamplerDescriptor+MoltenVK.m
MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm

In Metal 1.2 on Mac, the `MTLSamplerAddressModeClampToBorderColor`
address mode was added. This mode actually lets clients specify the
border color, instead of hardcoding it to black (opaque without alpha,
transparent with alpha). Use this new mode instead of
`MTLSamplerAddressModeClampToZero` when possible.
Bump `VK_MVK_moltenvk` spec version.

MVKSampler: Support border colors.

---

MoltenVK/MoltenVK/Commands/MVKCmdPipeline.h

The command object assumes it is null if it hasn't been used yet. Let's
ensure this is so.

vkCmdPushDescriptorSetWithTemplate: Initialize data pointer to null.

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm

In which I am proved wrong again. While Metal indeed won't assert if the
pixel formats don't match, the results of attempting such a copy are...
mixed, to say the least. Sometimes, nothing is copied at all. Other
times, pixels are copied in weird ways that don't seem to conform at all
to expectation. (This is most apparent in the output of the CTS's image
copying tests.) It's best, then, to ensure that the source and
destination have the same format.
Unfortunately, in the process of writing this, my fears regarding not
being able to make uncompressed views of compressed images were
confirmed. So we can't do this for compressed images.

vkCmdCopyImage: Cast source image to the destination format.

---

MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm

Null the `sampler` field of the stored `VkDescriptorImageInfo` if the
descriptor uses an immutable sampler. That way, we won't try to
double-free a sampler.
Retain immutable samplers when the set is created. Release them when the
set is destroyed.

MVKDescriptorSet: Fix handling of immutable samplers.

---

MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

Metal validates that this is so.

MVKPipeline: Forbid vertex attribute offsets >= stride.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

As I feared. It's impossible to create an uncompressed view from a
compressed texture.

MVKImage: Make BLOCK_TEXEL_VIEW a hard error.

---

MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.h
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

As discussed and agreed upon in #306.
Since a pipeline might be shared between multiple draws, but those draws
could use different textures, it isn't tenable to have a single aux
buffer shared between those draws. Instead, we'll set up constant
buffers using the `setXxxBytes()` method on the command encoder. That
way, separate draws using the same pipeline won't interfere with each
other.
This change also uses separate buffers for the vertex and fragment
shaders, since they may have different sets of textures.

Use an inline constant buffer for the auxiliary buffer.

---

.travis.yml
ExternalDependencies.xcodeproj/project.pbxproj
ExternalDependencies.xcodeproj/xcshareddata/xcschemes/ExternalDependencies-iOS.xcscheme
ExternalDependencies.xcodeproj/xcshareddata/xcschemes/ExternalDependencies-macOS.xcscheme
ExternalDependencies.xcodeproj/xcshareddata/xcschemes/ExternalDependencies.xcscheme
ExternalDependencies.xcodeproj/xcshareddata/xcschemes/SPIRV-Cross-iOS.xcscheme
ExternalDependencies.xcodeproj/xcshareddata/xcschemes/SPIRV-Cross-macOS.xcscheme
ExternalDependencies.xcodeproj/xcshareddata/xcschemes/SPIRV-Tools-iOS.xcscheme
ExternalDependencies.xcodeproj/xcshareddata/xcschemes/SPIRV-Tools-macOS.xcscheme
ExternalDependencies.xcodeproj/xcshareddata/xcschemes/glslang-iOS.xcscheme
ExternalDependencies.xcodeproj/xcshareddata/xcschemes/glslang-macOS.xcscheme
ExternalRevisions/README.md
MoltenVKPackaging.xcodeproj/project.pbxproj
MoltenVKShaderConverter/MoltenVKGLSLToSPIRVConverter/GLSLToSPIRVConverter.cpp
MoltenVKShaderConverter/MoltenVKSPIRVToMSLConverter/SPIRVToMSLConverter.h
MoltenVKShaderConverter/MoltenVKSPIRVToMSLConverter/spirv.hpp
MoltenVKShaderConverter/MoltenVKShaderConverter.xcodeproj/project.pbxproj
Scripts/package_ext_libs.sh
Scripts/package_ext_libs_ios.sh
Scripts/package_ext_libs_macos.sh
fetchDependencies

This is a build optimization for developers that work on MoltenVK development.
In the past, the MoltenVK project directly included significant code from the _SPIRV-Cross_, _glslang_ and _SPRIV-Tools_ external libraries...which would need to be recompiled each time MoltenVK was compiled (especially from clean). The presence of this fixed library code added significantly to the build time of MoltenVK (_SPIRV-Tools_ was particularly hefty).
These three external libraries are now managed by the `ExternalDependencies.xcodeproj` _Xcode_ project...and are built separately...automatically...and only once...when they are fetched from their respective repositories...as part of the `fetchDependencies` script.
The `fetchDependencies` script places build artifacts...and the finished set of static …

 Build external dependencies into static libraries in External/build when fetched.

---

Docs/Whats_New.md
MoltenVK/MoltenVK.xcodeproj/project.pbxproj
MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/Commands/MVKCommandEncodingPool.h
MoltenVK/MoltenVK/Commands/MVKCommandEncodingPool.mm
MoltenVK/MoltenVK/Commands/MVKCommandPipelineStateFactoryShaderSource.h
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.h
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/Utility/MVKCodec.cpp
MoltenVK/MoltenVK/Utility/MVKCodec.h
MoltenVK/MoltenVK/Utility/MVKDXTnCodec.def

This allows clients to initialize 3D image objects with data in a BC1,
BC2, or BC3 (aka DXTn, aka S3TC) format. Since Metal doesn't support
this natively, DXTn-compressed image data are manually decompressed
prior to upload or copying. This particular algorithm was derived from
Wine, from code originally authored by Connor McAdams. It's somewhat
primitive, and could probably stand some vectorization, but it's a good
first start.
The meat of the algorithm is pulled into a header, "MVKDXTnCodec.def",
intended to be used by both CPU and shader code. CPU uploads, which in
MoltenVK happen when binding a `VkDeviceMemory` object to an image, run
the code normally. GPU uploads, i.e. copying from a buffer to a texture,
run the algorithm as a compute shader, possibly storing the results to
an …

Add support for uploading 3D S3TC-compressed images.

---

ExternalDependencies.xcodeproj/project.pbxproj
MoltenVK/MoltenVK.xcodeproj/project.pbxproj
MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVKShaderConverter/MoltenVKShaderConverter.xcodeproj/project.pbxproj

1. As described in Issue #431...support for `arm64e` architecture in Xcode is only Preview technology...and causes conflicts with the use of Bitcode. This PR removes support for `arm64e` until it is better handled by Xcode.
2. Fix Metal buffer offset with multiple copy regions in MVKCmdBufferImageCopy::encode().
@cdavis5e This second fix is to correct an issue where the Metal buffer offset was not being determined correctly when iterating multiple copy regions. The issue was introduced in PR #435...and so I needed to modify your code from that PR. I have no way of testing 3D compressed textures. Can you review and retest to ensure I have not now broken any of your changes from PR #435, please?

Fix for multiple image copy regions + Remove arm64e support for now.

---

MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm
MoltenVK/MoltenVK/GPUObjects/MVKShaderModule.mm
MoltenVK/MoltenVK/Utility/MVKEnvironment.h
MoltenVKShaderConverter/MoltenVKSPIRVToMSLConverter/SPIRVToMSLConverter.cpp
MoltenVKShaderConverter/MoltenVKSPIRVToMSLConverter/SPIRVToMSLConverter.h

Fixes for:
#459 Enable all vertex attributes and resources in shaders for pre-converted Metal code.
#301 Xcode GPU capture for multiple queues and queue families.
#446 Return error when array of textures or samplers are requested but is not supported by device.
Update MoltenVK to version 1.0.32.
Update `VK_MVK_MOLTENVK_SPEC_VERSION` to 17.

Fixes for issues #459, #301, #446.

---

MoltenVK/MoltenVK/API/mvk_datatypes.h
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.mm
MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm

There is nothing in the Vulkan spec to suggest that
`VK_ATTACHMENT_STORE_OP_STORE` and a resolve attachment cannot both be
specified, nor that one or the other has no effect. So, if the app
supplies a color attachment with both `VK_ATTACHMENT_STORE_OP_STORE` and
a resolve attachment, that means it wants the output to be both stored
to the color attachment and resolved to the resolve attachment. In that
case, we should respect the application's wishes and do both. We can
only do that if the device supports this, though. All devices on Mac
starting with macOS 10.12 support this. On iOS, only the A9 and above
support combined store-resolve actions.
When this isn't supported, and the application asks for both, we should
probably schedule a second render pass which resolves the attachment,
as …

MVKRenderPass: Use combined store-resolve ops when requested and supported.

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/Utility/MVKVector.h

As requested, I added a few missing functions to MVKVector, so that almost all std::vector members functions are now available for MVKVector as well. So in theory you can replace the templated function 
`template<typename T>
static void updateSwizzle(T &constants, uint32_t index, uint32_t swizzle) {`
with
`static void updateSwizzle(MVKVector &constants, uint32_t index, uint32_t swizzle) {`
Just to repeat: Performance of the templated function is higher since accessing MVKVector member functions involves a virtual function call. But in this case, performance implications are basically negligible.
@billhollings Could you please also look at the changes in MVKImage.mm. If the size of _availabilitySignalers is small, e.g. less than 20 elements, then there is no point in using std::list. …

Missing functions for MVKVector

---

fetchDependencies

Glslang does not build SPIRV-Tools when including it.
The `fetchDependencies` script does this when cloning
the repo on its own, but neglects to do this when a path
to a pre-built glslang is provided.
This commit adds the SPIRV-Tools build step when given
a path to a pre-built glslang.

fetchDependencies: Fix SPIRV-Tools including pre-built glslang

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

Why was this turned off? Pretty sure Metal supports this.

Advertise support for the separateStencilMaskRef portability feature.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

Advertise VkPhysicalDevicePortabilitySubsetFeaturesEXTX::standardImageViews enabled if MVKConfiguration::fullImageViewSwizzle enabled.

Advertise VkPhysicalDevicePortabilitySubsetFeaturesEXTX::standardImageViews

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

 vkSetMTLTextureMVK() function retains texture object.

---

MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

Otherwise, the log will be spammed with hundreds of useless messages
that the `IDENTITY` swizzle is not supported.

Only warn on non-default swizzles when fullImageViewSwizzle is off.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

Now that SPIRV-Cross is updated to support it, we can safely advertise
this.
Fixes #372.

Turn on shaderInt8.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

While Metal *does* allow read access to multisampled textures, it does
*not* allow write access. In Vulkan, storage images are always writable.
Therefore, we can't fully support this feature.

Disable the shaderStageImageMultisample feature.

---

Makefile
MoltenVKShaderConverter/MoltenVKShaderConverter.xcodeproj/project.pbxproj
Scripts/package_ext_libs.sh
fetchDependencies

Building external dependency libraries cleans MoltenVK to ensure subsequent MoltenVK builds will link to latest dependency library versions.
Fixes #507.

Building external dependency libraries cleans MoltenVK.

---

Common/MVKLogging.h
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

Add MVKPhysicalDeviceMetalFeatures::mslVersionEnum and set from Metal feature sets.
Derive MVKPhysicalDeviceMetalFeatures:: mslVersion from mslVersionEnum.
MVKDevice::getMTLCompileOptions() sets MTLCompileOptions::languageVersion
from MVKPhysicalDeviceMetalFeatures::mslVersionEnum.
MVKAssert logs error even when assertions disabled.
Update VK_MVK_MOLTENVK_SPEC_VERSION to 18.

Set MSL version for shader compiling from Metal feature set.

---

fetchDependencies

For example, if CMake executable was not found, error message is hidden very well in quite long outputs of Git commands.

Stop on the first error in fetch dependencies script

---

MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm
MoltenVKShaderConverter/MoltenVKShaderConverterTool/MoltenVKShaderConverterTool.cpp

Use autorelease pool for synchronous command buffer submissions also.
MoltenVKShaderConverterTool support cs & csh for compute shader file extensions.

Fix potential memory leak on synchronous command buffer submission.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

Also fix memory overrun if no VB found with same binding as a VA.

Allow zero offset and stride combo in VkVertexInputBindingDescription.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

iOS does not actually support arrays of writable textures. At all.

MVKDevice: Don't enable the shaderStorageImageArrayDynamicIndexing feature on iOS.

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm

According to the Vulkan spec:
> * If either of `srcImage` or `dstImage` was created with a
>   depth/stencil format, the other **must** have exactly the same format
So this should not happen in well-behaved clients.
Is there a reason this check was added?

vkCmdBlitImage: Remove check for invalid behavior.

---

MoltenVK/MoltenVK/Commands/MVKCmdPipeline.mm

Missed this when I was initially implementing this.

Fix updating push constants for tessellation shaders.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/Commands/MVKCmdRenderPass.mm
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueryPool.mm
MoltenVK/MoltenVK/Vulkan/vulkan.mm

- Enable device features based on content of pCreateDeviceInfo.
- Validate requested features are available and return  if not.
- Support returning error from vkCreateDevice(), vkFlushMappedMemoryRanges() and vkInvalidateMappedMemoryRanges().
- Remove "unimplemented" error reporting from sparse binding functions.
- As per Vulkan spec, sparse binding query functions simply return zero responses.
- vkQueueBindSparse() returns VK_ERROR_FEATURE_NOT_PRESENT error.
- Update What's New Document.

Track enabled device features and clean up sparse binding errors.

---

Docs/MoltenVK_Runtime_UserGuide.md
Docs/Whats_New.md
ExternalDependencies.xcodeproj/project.pbxproj
ExternalDependencies.xcodeproj/xcshareddata/xcschemes/ExternalDependencies-iOS.xcscheme
ExternalDependencies.xcodeproj/xcshareddata/xcschemes/ExternalDependencies-macOS.xcscheme
ExternalDependencies.xcodeproj/xcshareddata/xcschemes/ExternalDependencies.xcscheme
ExternalDependencies.xcodeproj/xcshareddata/xcschemes/SPIRV-Cross-iOS.xcscheme
ExternalDependencies.xcodeproj/xcshareddata/xcschemes/SPIRV-Cross-macOS.xcscheme
ExternalDependencies.xcodeproj/xcshareddata/xcschemes/SPIRV-Tools-iOS.xcscheme
ExternalDependencies.xcodeproj/xcshareddata/xcschemes/SPIRV-Tools-macOS.xcscheme
ExternalDependencies.xcodeproj/xcshareddata/xcschemes/glslang-iOS.xcscheme
ExternalDependencies.xcodeproj/xcshareddata/xcschemes/glslang-macOS.xcscheme
MoltenVK/MoltenVK.xcodeproj/project.pbxproj
MoltenVK/MoltenVK.xcodeproj/xcshareddata/xcschemes/MoltenVK-iOS.xcscheme
MoltenVK/MoltenVK.xcodeproj/xcshareddata/xcschemes/MoltenVK-macOS.xcscheme
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVKPackaging.xcodeproj/project.pbxproj
MoltenVKPackaging.xcodeproj/xcshareddata/xcschemes/MoltenVK Package (Debug).xcscheme
MoltenVKPackaging.xcodeproj/xcshareddata/xcschemes/MoltenVK Package (iOS only).xcscheme
MoltenVKPackaging.xcodeproj/xcshareddata/xcschemes/MoltenVK Package (macOS only).xcscheme
MoltenVKPackaging.xcodeproj/xcshareddata/xcschemes/MoltenVK Package.xcscheme
MoltenVKShaderConverter/MoltenVKShaderConverter.xcodeproj/project.pbxproj
MoltenVKShaderConverter/MoltenVKShaderConverter.xcodeproj/xcshareddata/xcschemes/MoltenVKGLSLToSPIRVConverter-iOS.xcscheme
MoltenVKShaderConverter/MoltenVKShaderConverter.xcodeproj/xcshareddata/xcschemes/MoltenVKGLSLToSPIRVConverter-macOS.xcscheme
MoltenVKShaderConverter/MoltenVKShaderConverter.xcodeproj/xcshareddata/xcschemes/MoltenVKSPIRVToMSLConverter-iOS.xcscheme
MoltenVKShaderConverter/MoltenVKShaderConverter.xcodeproj/xcshareddata/xcschemes/MoltenVKSPIRVToMSLConverter-macOS.xcscheme
MoltenVKShaderConverter/MoltenVKShaderConverter.xcodeproj/xcshareddata/xcschemes/MoltenVKShaderConverter.xcscheme

Address issues #359 & #461 as best as can be done under Metal PVRTC.
PVRTC images loaded via host-visible memory-mapping now use the values of zero for both `bytesPerRow` and `bytesPerImage` as expected by Metal.
PVRTC images must be loaded via host-visible memory-mapping, and not via a staging buffer. This limitation is now documented in `MoltenVK_Runtime_UserGuide.md`.

 Fix PVRTC texture content loading via memory mapping.

---

MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.h
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

Fixed crash within MVKPushConstantsCommandEncoderState when accessing absent graphics pipeline during a compute stage.
MVKPushConstantsCommandEncoderState test for tessellation only during graphics stages.
Guard against possible missing graphics pipeline even during graphics stages.
Support null device in MVKBaseDeviceObject and MVKDispatchableDeviceObject instances.

CTS fixes. MVKPushConstantsCommandEncoderState compute / tessellation conflict.

---

MoltenVK/MoltenVK/GPUObjects/MVKBuffer.h
MoltenVK/MoltenVK/GPUObjects/MVKBuffer.mm

The resource options must match between an `MTLBuffer` and any linear
texture created from it. Further, to be writable, the
`MTLTextureDescriptor` should have the `MTLTextureUsageShaderWrite` bit
set.
Fixes #542.

Set options properly on a buffer view's MTLTextureDescriptor.

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm

A double offset would be applied by taking the user offset and global offset, causing the word count to wrap around and trigger an assertion and GPU lockup. This seems to be what caused a GPU hang in Granite for some time.
I also added a rounding bump for wordCount. I'm not sure if the internal buffer size is naturally rounded ahead of time, but the case for this rounding would be if a buffer was, say, 3 bytes, and the application calls for VK_WHOLE_SIZE.
This is related to:
https://github.com/KhronosGroup/MoltenVK/issues/544

Fix wrong offset for vkCmdFillBuffer on VK_WHOLE_SIZE.

---

MoltenVK/MoltenVK.xcodeproj/project.pbxproj
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm
MoltenVK/MoltenVK/GPUObjects/MVKSurface.h
MoltenVK/MoltenVK/GPUObjects/MVKSurface.mm
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.h
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm
MoltenVK/MoltenVK/Utility/MVKBlockObserver.h
MoltenVK/MoltenVK/Utility/MVKBlockObserver.m

Sometimes, the `CAMetalLayer` backing a view can be replaced--for
example, when the window is moved to another screen, or the style bits
on the window are changed. In that case, we must allow the client the
opportunity to recreate the surface and swapchain.
Layer-backed views always set themselves as the layer's delegate; we use
this fact to Key-Value Observe the view's `layer` property.
Other alternatives considered:
* Registering for `NSViewGlobalFrameDidChange` notifications. Aside from
only working on macOS, this doesn't actually catch every case where we
want to report a lost surface. I'm not even sure it works at all for
Metal.
* Holding a reference to the view, and checking when its layer property
has changed.
* Holding a weak reference to the layer; that way, the reference will …

Handle surface loss.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm

Set MTLRenderPassDescriptor renderTargetWidth & renderTargetHeight only when layered rendering supported, to avoid GPU crashes on older devices.

---

MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.h
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm

The `mustSetDynamically` and `isSetDynamically` flags clashed when calling `vkCmdSetViewport`/`vkCmdSetScissor` after drawing a pipeline with a static viewport/scissor but before binding a pipeline with a dynamic viewport/scissor.

Fix case where viewport/scissor doesn't get set properly when mixing dynamic and static-configured pipelines in the same command buffer.

---

MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h

If we don't have them, it's not a tessellation pipeline.

MVKPipeline: Account for tessellation shaders as well.

---

MoltenVK/MoltenVK/GPUObjects/MVKBuffer.mm

Shared storage on textures is disallowed on macOS.
Fixes #573.

MVKBuffer: Force managed storage for linear textures on shared buffers.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

All of the resources' `applyMemoryBarrier()` methods check if the second
scope contains host operations. If they don't, they have no effect. If
there are a lot of resources, iterating them for a method that will
ultimately do nothing is wasteful. Bail out if we can see that they will
do nothing.

MVKDevice: Don't unnecessarily iterate resources for global memory barriers.

---

MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueue.h
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm
MoltenVK/MoltenVK/GPUObjects/MVKSync.h
MoltenVK/MoltenVK/GPUObjects/MVKSync.mm

While `MTLFence` could be used for synchronization within a single
queue, it doesn't prevent execution across queues. For this, an
`MTLEvent` is required. Yes, this requires Metal 2.1 (macOS 10.14, iOS
12). Older versions will continue to use the old, CPU-based
implementation.
According to the Vulkan spec, semaphores must either be already signaled
or have a signal operation in progress before waiting for them. This
implementation increments the `MTLEvent`'s expected value after encoding
a wait operation, which requires this assumption to hold.
One thorny bit is acquiring a swapchain image when it is not already in
use. In this case, any semaphore provided must be signaled right away.
To accomplish this, a command buffer is executed which performs the
signal operation on the device. …

MVKSemaphore: Use MTLEvent for device-side synchronization.

---

MoltenVK/MoltenVK/API/mvk_datatypes.h
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/Commands/MVKCmdPipeline.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm

These two new methods introduced in Metal 2.1 (macOS 10.14) are more
granular, providing more control over what exactly must be sync'd. They
also work on buffer memory, meaning that buffer dependencies work
properly here.

Use the new memory barrier methods for pipeline barrier commands.

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

Since texture can't be coherent on macOS, they need to be synchronized for host read. This PR fixes this.

texture don't have coherent memory on mac os

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKFramebuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm

- Add MVKPhysicalDeviceMetalFeatures::multisampleLayeredRendering feature.
- MVKCmdClearAttachments shader don't include [[render_target_array_index]] if multisample
and multisampleLayeredRendering is false.
- Refactor validation of VkImageCreateInfo when creating an MVKImage.
- Validate MVKImage multisample layered array attachments require multisampleLayeredRendering.
Fixes issue #594.

Fix crash with multisample layered rendering on older macOS devices.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

- Only set MTLRenderPassDescriptor layered rendering properties if layered rendering
is supported and the framebuffer really has multiple layers.
- MVKCmdClearImage don't set renderTargetArrayLength, since layers are cleared individually.
- Update highest available MTLFeatureSets for use in pipelineCacheUUID.
Fixes issue #579.

Fixes to Metal renderpass layered rendering settings.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/Commands/MVKCmdRenderPass.h
MoltenVK/MoltenVK/Commands/MVKCmdTransfer.h
MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.h
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.h
MoltenVK/MoltenVK/Commands/MVKCommandPool.h
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.h
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h

- Consolidate testing of subpass layered rendering.
- Add `MVKCommandEncoder::_isUsingLayeredRendering` member variable.
- Track layered rendering enabled in `MVKRPSKeyClearAtt`.
- Rename `MVKRPSKeyClearAtt::enable()` and `::isEnabled()` functions.
- Add `MVKRPSKeyClearAtt::reset()` function.
- Consolidate viewport, scissor & attachment limits.
- `MVKImage` add validation for layered rendering when used as attachment.

Clear attachments using layered rendering only if framebuffer is layered.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKSurface.mm
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm

`MVKSwapchain` & `MVKSurface` init `_layerObserver` to nil.
Fixes issue #584.

Fix sporadic crash on vkDestroySwapchainKHR().

---

MoltenVK/MoltenVK/Commands/MVKCommandPipelineStateFactoryShaderSource.h
MoltenVK/MoltenVK/Utility/MVKDXTnCodec.def

Buffers in constant address space must be aligned to 256 bytes on macOS.
This fixes Metal validation errors:
Compute Function(cmdCopyBufferToImage3DDecompressDXTn): the offset into the buffer src that is bound at buffer index 0 must be a multiple of 256 but was set to 12928.
Compute Function(cmdCopyBufferToImage3DDecompressDXTn): the offset into the buffer src that is bound at buffer index 0 must be a multiple of 256 but was set to 78464.

Use device address space when decompressing DXT image data.

---

MoltenVKShaderConverter/MoltenVKSPIRVToMSLConverter/SPIRVToMSLConverter.cpp

This is needed for TessLevelInner and TessLevelOuter in tessellation evaluation
shaders.
Fixes dEQP-VK.tessellation.shader_input_output.tess_level_inner_0_tes.

Fix [[attribute]] assignment for tessellation evaluation shaders.

---

MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

Added missing texelBufferTextureWidth setting in MVKComputePipeline::getMTLFunction.

---

MoltenVK/MoltenVK/GPUObjects/MVKBuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm
MoltenVK/MoltenVK/GPUObjects/MVKVulkanAPIObject.mm

Guard against null _debugNames being used to build name strings.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVKShaderConverter/Common/SPIRVSupport.cpp
MoltenVKShaderConverter/MoltenVKGLSLToSPIRVConverter/GLSLToSPIRVConverter.cpp
MoltenVKShaderConverter/MoltenVKSPIRVToMSLConverter/SPIRVReflection.cpp
MoltenVKShaderConverter/MoltenVKSPIRVToMSLConverter/SPIRVReflection.h
MoltenVKShaderConverter/MoltenVKSPIRVToMSLConverter/SPIRVToMSLConverter.cpp
MoltenVKShaderConverter/MoltenVKShaderConverter.xcodeproj/project.pbxproj
README.md

- All external library header references consistently include framework references.
- Cleanup references to external library headers that are no longer required.
- Simplify and consolidate external library header paths in Xcode projects.
- Add `MVK_EXCLUDE_SPIRV_TOOLS` build option to avoid use of SPIRV-Tools library.
- Remove all other references to headers within SPIRV-Tools library.
- Fix #607. 
- Fix #610.

Fixes and consolidation of external library header references.

---

MoltenVK/MoltenVK/Commands/MVKCmdDebug.mm
MoltenVK/MoltenVK/Commands/MVKCmdRenderPass.mm
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.h
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
MoltenVK/MoltenVK/GPUObjects/MVKShaderModule.h
MoltenVK/MoltenVK/GPUObjects/MVKShaderModule.mm

- `vkCmdDebugMarkerBegin()` and `vkCmdDebugMarkerEnd()` attach debug
groups to render encoder if available, or command buffer if not.
- Name `MTLRenderCommandEncoder` first after renderpass,
if named, then command buffer, if named, then usage name.
- Add `MVKCommandEncoder::endRenderpass()` to clean up renderpass components.
- `MVKShaderLibrary` and `MVKShaderLibraryCache` track shader module to
retrieve name for `MTLLibrary` and `MTLFunction`, even when cached offline.

Fixes to VK_EXT_debug_marker extension.

---

MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm

Instead, just avoid calling into Metal. It's perfectly valid to specify
no viewports--for example, if rasterization is disabled. Perhaps, then,
it'd be better to assert that rasterization is disabled when no
viewports are given.

Don't assert if no viewports or scissor rects were given.

---

MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
MoltenVK/MoltenVK/GPUObjects/MVKShaderModule.h
MoltenVK/MoltenVK/GPUObjects/MVKShaderModule.mm

- Set `MTLFunction` label immediately after creation from `MVKShaderModule`.
- Remove `_shaderModule` reference from `MVKShaderLibrary` & `MVKShaderLibraryCache`.
- No-op `propogateDebugName()` function in `MVKShaderModule` & `MVKPipelineCache`.

Fix crash on pipeline cache merge after VkShaderModule destroyed.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/Utility/MVKEnvironment.h

Provides automatic workaround for issues #602 and #625.

VkSemaphore optionally uses MTLEvent, if available and MVK_ALLOW_METAL_EVENTS environment variable is enabled.

---

MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKShaderModule.h
MoltenVK/MoltenVK/GPUObjects/MVKShaderModule.mm
MoltenVK/MoltenVK/Vulkan/vk_mvk_moltenvk.mm
MoltenVKShaderConverter/MoltenVKSPIRVToMSLConverter/SPIRVToMSLConverter.h

Added a way to set compute kernel threadgroup size when using MSL source code or MSL compiled code. Fixes #632.

Added a way to set compute kernel threadgroup size.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/Commands/MVKCmdDraw.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

- MVKPipeline records whether Metal pipelines are successfully compiled.
- Pipeline and draw commands check for valid Metal pipeline state before encoding.
- Compute compilation operations can have custom names.
- Name Tessellation control stage compute compiler for logging.

Guard against missing Metal pipeline states when pipeline compilation fails.

---

.travis.yml
Demos/LunarG-VulkanSamples/API-Samples/API-Samples.xcodeproj/project.pbxproj
Demos/LunarG-VulkanSamples/API-Samples/API-Samples.xcodeproj/xcshareddata/xcschemes/API-Samples-iOS.xcscheme
Demos/LunarG-VulkanSamples/API-Samples/API-Samples.xcodeproj/xcshareddata/xcschemes/API-Samples-macOS.xcscheme
Demos/LunarG-VulkanSamples/Cube/Cube.xcodeproj/project.pbxproj
Demos/LunarG-VulkanSamples/Cube/Cube.xcodeproj/xcshareddata/xcschemes/Cube-iOS.xcscheme
Demos/LunarG-VulkanSamples/Cube/Cube.xcodeproj/xcshareddata/xcschemes/Cube-macOS.xcscheme
Demos/LunarG-VulkanSamples/Hologram/Hologram.xcodeproj/project.pbxproj
Demos/LunarG-VulkanSamples/Hologram/Hologram.xcodeproj/xcshareddata/xcschemes/Hologram-iOS.xcscheme
Demos/LunarG-VulkanSamples/Hologram/Hologram.xcodeproj/xcshareddata/xcschemes/Hologram-macOS.xcscheme
MoltenVK/MoltenVK.xcodeproj/project.pbxproj
MoltenVK/MoltenVK.xcodeproj/xcshareddata/xcschemes/MoltenVK-iOS.xcscheme
MoltenVK/MoltenVK.xcodeproj/xcshareddata/xcschemes/MoltenVK-macOS.xcscheme
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVKPackaging.xcodeproj/project.pbxproj
MoltenVKPackaging.xcodeproj/xcshareddata/xcschemes/MoltenVK Package (Debug).xcscheme
MoltenVKPackaging.xcodeproj/xcshareddata/xcschemes/MoltenVK Package (iOS only).xcscheme
MoltenVKPackaging.xcodeproj/xcshareddata/xcschemes/MoltenVK Package (macOS only).xcscheme
MoltenVKPackaging.xcodeproj/xcshareddata/xcschemes/MoltenVK Package.xcscheme
MoltenVKShaderConverter/MoltenVKShaderConverter.xcodeproj/project.pbxproj
MoltenVKShaderConverter/MoltenVKShaderConverter.xcodeproj/xcshareddata/xcschemes/MoltenVKGLSLToSPIRVConverter-iOS.xcscheme
MoltenVKShaderConverter/MoltenVKShaderConverter.xcodeproj/xcshareddata/xcschemes/MoltenVKGLSLToSPIRVConverter-macOS.xcscheme
MoltenVKShaderConverter/MoltenVKShaderConverter.xcodeproj/xcshareddata/xcschemes/MoltenVKSPIRVToMSLConverter-iOS.xcscheme
MoltenVKShaderConverter/MoltenVKShaderConverter.xcodeproj/xcshareddata/xcschemes/MoltenVKSPIRVToMSLConverter-macOS.xcscheme
MoltenVKShaderConverter/MoltenVKShaderConverter.xcodeproj/xcshareddata/xcschemes/MoltenVKShaderConverter.xcscheme

- Add MVKPhysicalDevice functions to support new MTLDevice methods supportsVersion: and supportsFamily:.
- MVKPhysicalDevice tests for Metal 3.0 & MSL 2.2.
- Move some global functions into the MVKPhysicalDevice class.
- Support Xcode 11.

Initial support for Metal 3.0.

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm

MVKCmdClearAttachment sets the stencil reference value to 0 and the stencil
reference value is not properly restored for subsequent draw calls.
I'm affraid there might be more similar bugs in MoltenVK.

Mark stencil reference value as dirty in MVKCmdClearAttachment command.

---

MoltenVKShaderConverter/MoltenVKSPIRVToMSLConverter/SPIRVToMSLConverter.cpp

SPIRVToMSLConverterOptions should really be refactored into two separate config and results structs.

Quick fixes for pipeline cache lookups.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueue.h
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm
MoltenVK/MoltenVK/Vulkan/vulkan.mm

- Add `MVKPerformanceStatistics::MVKQueuePerformance::mtlCommandBufferCompletion` to track command buffer completion (not execution yet) times.
- Expand `MVK_CONFIG_TRACE_VULKAN_CALLS` to optionally log Vulkan call timings.

Add additional performance and call tracing options.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKVulkanAPIObject.h
MoltenVK/MoltenVK/GPUObjects/MVKVulkanAPIObject.mm

- Retain `MVKSwapchainImage` before passing to `MTLCommandBuffer` completion handler.
- Redesign `MVKVulkanAPIObject` retain/release functionality using atomic ref count
instead of mutex locks, to simplify design and improve performance.
Fixes issue #510.

Fix race condition between swapchain image destruction and presentation completion callback

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm

MVKCmdBlitImage clear _mvkImageBlitRenders vector on reuse.

---

MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKBuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

These were added in Metal 2.1.

Use native texture buffers when available.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

The documentation for the corresponding Metal format recommends using it
on displays with wide-color output to reduce banding artifacts, and thus
implies that it is possible to use it with a CAMetalLayer.
My investigation found that, surprisingly, `MTLPixelFormatRGB10A2Unorm` is
*also* supported.

Advertise VK_FORMAT_A2R10G10B10_UNORM_PACK32 as a surface format.

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

I forgot to make this change when I added support for
`VK_KHR_swapchain_mutable_format`. The extension isn't very useful
without this.

MVKImage: Swapchain images do support texture views.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm

Correct maximum number of texel buffer elements for the native texture
buffer case. With an 8-bit format, I assume it's possible to create a
texture buffer spanning the entire 3.5 GiB (the maximum size of a buffer
on my GPU).
Set the structure type in the physical device's
`_texelBuffAlignProperties` struct. Otherwise, when it gets written out
to a chain, the structure type will be lost, and it wouldn't e.g. show
up in `vulkaninfo`.
Fix enumeration of formats when one of the members of the
`VkFormatProperties` is zero. I intended that to mean "don't care," but
it was erroneously filtering out, well, everything. Now we actually
accurately report the minimum alignment requirements.

Fix implementation of VK_EXT_texel_buffer_alignment.

---

MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm

Advertise linear filtering of linear textures on macOS. I don't see any
reason this was disabled, and I don't know why I didn't turn it on in
PR #391.
Advertise that texel buffers of `VK_FORMAT_A2R10G10B10_UNORM_PACK32` are
supported. This was another oversight of mine in #391.
*Don't* advertise that sRGB formats can be used as vertex attributes.
I'm not sure what that would even mean--I'm guessing that the
implementation performs sRGB->linear conversion on the attribute before
loading it? But we don't do that and neither does Metal.

More format feature fixes.

---

Demos/LunarG-VulkanSamples/API-Samples/API-Samples.xcodeproj/xcshareddata/xcschemes/API-Samples-macOS.xcscheme
Demos/LunarG-VulkanSamples/Cube/macOS/DemoViewController.m
Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKVulkanAPIObject.h

- Revert to supporting host-coherent memory for linear images on macOS.
- `MVKImage::getMemoryRequirements()` include host-coherent for linear images.
- Cube demo on macOS not use staging buffers for loading images.
- Fixes #687 
- Ensure Vulkan loader magic number persists in objects pooled by MoltenVK.
- `MVKDispatchableVulkanAPIObject::getVkHandle()` re-establishes the loader magic number
before returning, in case the loader overwrote it before returning the object.
- Fixes #689

Host-coherent memory for linear images again, plus Vulkan loader magic number fix.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

Apple removed this from all SDKs as of Xcode 11 beta 5.

MVKDevice: Remove usage of MTLSoftwareVersion.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/Utility/MVKVector.h
MoltenVK/MoltenVK/Utility/MVKVectorAllocator.h

- `MVKDevice` check highest queue family index before expanding queue family collection.
- `MVKVector` add bounds check to `at()`, `[]`, `front()` and `back()` functions.
Fixes issue #697.

Fix crash when VkDeviceCreateInfo specifies queue families out of numerical order.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm
MoltenVK/MoltenVK/Layers/MVKExtensions.mm
Scripts/create_dylib.sh

Support `VK_EXT_swapchain_colorspace` on iOS as well. The 13.0 headers
add the `colorspace` property needed for this.

Add more supported color spaces as of the latest OS versions.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

This has now been implemented in SPIRV-Cross. It's supported on Mac as
of Metal 3.0 (10.15).

Advertise the shaderResourceMinLod feature.

---

MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

Mac-only for now. Mostly because I don't know which formats beyond DXTn
and ASTC support 3D textures. Also, the extension to support 3D ASTC
compression isn't ready yet.

Take advantage of Metal 3.0's support for 3D compressed textures.

---

MoltenVK/MoltenVK/API/mvk_datatypes.h
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm

When available, use it instead of doing it manually in the shaders.
Unfortunately, it's only available on Apple GPU family 4 and up, and
desktop GPU family 2. Should still provide a nice boost.

Take advantage of native texture swizzling support.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm

Set the `opaque` property of the `CAMetalLayer` based on this. In the
past, we did nothing; this actually corresponds to
`VK_COMPOSITE_ALPHA_INHERIT_BIT_KHR`.
Drop support for premultiplied alpha. In Core Animation, this is managed
by the `contents` of the layer. Most layers use a `CGImage` or an
`NSImage` for their contents; the `AlphaInfo` property of a `CGImage`
determines whether or not it uses premultiplied alpha. However,
`CAMetalLayer` doesn't use a `CGImage`, but a custom opaque Core
Foundation object which ostensibly vends images to be displayed by the
layer. I don't know which kind of alpha it uses, but since most
applications render postmultiplied colors I'm going to assume that
premultiplied alpha isn't supported yet.

MVKSwapchain: Add handling for compositeAlpha.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/Commands/MVKCmdPipeline.h
MoltenVK/MoltenVK/Commands/MVKCmdPipeline.mm
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.h
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/Commands/MVKCommandPool.h
MoltenVK/MoltenVK/Commands/MVKCommandPool.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm
MoltenVK/MoltenVK/GPUObjects/MVKSync.h
MoltenVK/MoltenVK/GPUObjects/MVKSync.mm
MoltenVK/MoltenVK/Utility/MVKEnvironment.h
MoltenVK/MoltenVK/Vulkan/vulkan.mm

- Add `MVKEvent` class. `MVKEventNative` subclass uses native `MTLEvent`. `MVKEventEmulated`
subclass uses emulation using CPU blocking and `MTLCommandBuffer` completion handling.
- `MVKConfiguration::synchronousQueueSubmits` now disabled by default if `MTLEvents` are not supported.
- Document updated use of `MVK_ALLOW_METAL_EVENTS` and `MVK_CONFIG_SYNCHRONOUS_QUEUE_SUBMITS`
environment variables and `synchronousQueueSubmits` config setting, in `vk_mvk_moltenvk.h`.

Add support for VkEvent.

---

MoltenVK/MoltenVK/GPUObjects/MVKBuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

In these cases, we just use the underlying `MTLBuffer` in the
`MVKDeviceMemory` anyway. Dedicated allocations don't really buy us
anything here.

Don't prefer dedicated allocations for buffer memory.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm

The old `DCI_P3_LINEAR` enum is deprecated. Use
`VK_COLOR_SPACE_DISPLAY_P3_LINEAR_EXT` instead. This is a closer match
for the Core Graphics name anyhow.

Fix name of Display-P3 linear color space.

---

MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKBuffer.h
MoltenVK/MoltenVK/GPUObjects/MVKBuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKDeviceMemory.h
MoltenVK/MoltenVK/GPUObjects/MVKDeviceMemory.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

All Apple GPUs support this, as does Mac GPU family 2. With this, we can
avoid expensive copies between buffers and textures allocated from the
same memory, and reduce memory usage to boot.
macOS is, unfortunately, constrained by the fact that `MTLHeap` objects
do not support any storage mode other than `MTLStorageModePrivate`--not
even `MTLStorageModeManaged`. This won't help for managed textures
there. Perhaps Apple will fix this in a later version.

Use placement heaps for VkDeviceMemory when possible.

---

Common/MVKOSExtensions.h
Common/MVKOSExtensions.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

This is the heap representing system memory. The memory type
corresponding to `MTLStorageModeShared` is reported as belonging to this
heap.
I've tried to correct the reported size of the heaps as well while I'm
at it. UMA GPUs and the system heap for NUMA GPUs use the system memory
size as the heap size, and the amount of available memory as the budget.
iOS 13 uses the new `os_proc_available_memory()` API for this purpose.
NUMA GPUs additionally use the memory used by the process as a crude
measure of system heap usage.

MVKDevice: Report a second heap for non-UMA devices.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKBuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKDeviceMemory.h
MoltenVK/MoltenVK/GPUObjects/MVKDeviceMemory.mm
MoltenVK/MoltenVK/GPUObjects/MVKInstance.h
MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm
MoltenVK/MoltenVK/Utility/MVKEnvironment.h
MoltenVK/MoltenVK/Vulkan/vulkan.mm

- Add `MVK_CONFIG_AUTO_GPU_CAPTURE_SCOPE` env var and build setting.

Add ability to automatically cause an Xcode GPU capture without developer intervention.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/Commands/MVKCmdTransfer.h
MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm

`vkCmdBlitImage()` support format component swizzling.
`vkCmdClearImage()` fix validation of depth attachment formats.
Fixes issues #694 & #704.

Fixes to vkCmdBlitImage() & vkCmdClearImage().

---

Docs/MoltenVK_Runtime_UserGuide.md
Docs/Whats_New.md
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.h
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.h
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.h
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.mm
MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm

- `vkCreateRenderPass()` return `VK_ERROR_FORMAT_NOT_SUPPORTED` if format not supported.
- Disable depth and/or stencil testing if corresponding attachment is missing.

Fixes to issues found during CTS testing

---

Docs/Whats_New.md
MoltenVK/MoltenVK/Commands/MVKCmdTransfer.h
MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/Commands/MVKCommandPipelineStateFactoryShaderSource.h

Use  parallelism more effectively to massively cover buffer with
multiple full threadgroups, instead of serial looping in shader.
Performance improvement measured at 150x (yes...x not %) on macOS.
`MVKCmdFillBuffer` move validation test to `setContent()` instead of `encode()`.

Improve performance of vkCmdFillBuffer().

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm
MoltenVK/MoltenVK/GPUObjects/MVKSync.h
MoltenVK/MoltenVK/GPUObjects/MVKSync.mm
MoltenVK/MoltenVK/Utility/MVKEnvironment.h

- Refactor `MVKSemaphore` class into separate `MVKSemaphoreMTLFence`,
`MVKSemaphoreMTLEvent`, and `MVKSemaphoreEmulated` subclasses.
- Add `MVK_ALLOW_METAL_FENCES` environment variable to optionally
enable using `MTLFence` for Vulkan semaphores.
- Add `MVKPhysicalDeviceMetalFeatures::fences` to track `MTLFence` availability.
- Update `VK_MVK_MOLTENVK_SPEC_VERSION` to version 22.
Supports issues #602 and #486.

Support optional use of MTLFence for Vulkan semaphores via the MVK_ALLOW_METAL_FENCES environment variable.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

This limitation appears to be have been present all along (cf. Metal
Feature Set Tables, under "Maximum function memory allocation for a
buffer in the constant address space"). I guess we never ran into it
before.
Prompted by #730.

MVKDevice: Constant buffer bindings on macOS cannot exceed 64k.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

On iOS 13 and iPad OS 13 MTLDevice minimumLinearTextureAlignmentForPixelFormat will cause a failed assertion if parameter is MTLPixelFormatInvalid.

Avoid MTLDevice minimumLinearTextureAlignmentForPixelFormat failed assertion

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm
MoltenVK/MoltenVK/Utility/MVKEnvironment.h

Allow MVK_CONFIG_SYNCHRONOUS_QUEUE_SUBMITS build setting to be overridden.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm

Wrap retrieval of MTLDevice and MTLCommandQueue in an @autoreleasepool.
Fixes issue #725.

Fix memory leaks of system classes during VkInstance and VkQueue creation.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKSync.mm

Wrap MVKMetalCompiler compiling execution in an @autoreleasepool.
Fix for issue #746.

Fix memory leaks when compiling shaders and pipelines without default OS autorelease pool

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/Utility/MVKEnvironment.h
MoltenVK/MoltenVK/Vulkan/mvk_datatypes.hpp
MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm

- Enable use of MTLFence for Vulkan semaphores, by default.
- Log format substitution error when `MTLPixelFormatDepth24Unorm_Stencil8` is not supported
Fixes issue #593.

Enable use of MTLFence for Vulkan semaphores, by default.

---

MoltenVKShaderConverter/MoltenVKGLSLToSPIRVConverter/GLSLToSPIRVConverter.cpp
MoltenVKShaderConverter/MoltenVKGLSLToSPIRVConverter/GLSLToSPIRVConverter.h

This is a PR for this [issue](https://github.com/KhronosGroup/MoltenVK/issues/755). Simple change to make it so that you can use the linking feature in [glslang ](https://github.com/KhronosGroup/glslang)
Thanks

Add shader linking capability to GLSLToSPIRVConverter

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

Add `MVKImage::_rowByteAlignment` separate from `_byteAlignment`.
Fixes issue #768.

Fix image subresource sizing calculations for heap-based textures.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKDeviceMemory.mm
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm

- Add `MVKDevice::getAnyQueue()` to safely find the first available queue.
- Update MoltenVK version to 1.0.40.
Fixes issue #791 and maybe #779.

Fix crash when app does not use queue family zero.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm

Fix buffer offset in vkCmdPushDescriptorSet() for non-dedicated buffer memory

---

MoltenVK/MoltenVK/Commands/MVKCmdPipeline.mm
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.h
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/Commands/MVKMTLResourceBindings.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm

The separate `bufferBindings` and `inlineBindings` members proved troublesome, and using `set[Vertex/Fragment/Compute]Bytes` always was unnecessary overhead, so replaced with an `MTLBuffer`. Unfortunately I still don't have a proper test of `vkCmdPushDescriptorSets` though, but spotted what I could for now.

Fix a few issues with EXT_inline_uniform_block

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/GPUObjects/MVKBuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKDeviceMemory.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueryPool.mm
MoltenVK/MoltenVK/Utility/MVKFoundation.h

- Add `MVKPhysicalDeviceMetalFeatures::pushConstantSizeAlignment`, set value to 16 (size of
`float4`), and ensure push constant buffers have a size that is a multiple of that value.
- Update `VK_MVK_MOLTENVK_SPEC_VERSION` to `24`.
- Rename `mvkAlignByteOffset()` to `mvkAlignByteCount()`.

Fix Metal validation error on push constant sizing differences between C and MSL structs.

---

Docs/MoltenVK_Runtime_UserGuide.md
Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm

- Fix issue where preallocated descriptor count was not reset during vkResetDescriptorPool().
- Document MVK_CONFIG_PREALLOCATE_DESCRIPTORS runtime environment variable.
- Update MoltenVK_Runtime_UserGuide.md to better explain runtime environment variables.
- Update Whats_New.md document.

Fix issue where preallocated descriptor count was not reset during vkResetDescriptorPool().

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.mm
MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.mm
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm

Suppress spurious debug message.
Minor syntax fix.
Update MoltenVK version to 1.0.41.

Fix issue where immutable samplers are removed during descriptor update.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.h
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKShaderModule.h
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.h
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm
MoltenVK/MoltenVK/Vulkan/vulkan.mm

Add thread ID when logging Vulkan calls during debugging.

Guard against Metal validation assertion from reuse of query number

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

Increase value of VkPhysicalDeviceLimits::minStorageBufferOffsetAlignment to 16 to avoid Metal validation assertions.
Fixes issue #829.

Fix Metal validation assertion on VkPhysicalDeviceLimits::minStorageBufferOffsetAlignment

---

Common/MVKOSExtensions.h
Common/MVKOSExtensions.mm
MoltenVK/MoltenVK/API/mvk_datatypes.h
MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKInstance.h
MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.h
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.mm
MoltenVK/MoltenVK/Layers/MVKExtensions.mm
MoltenVK/MoltenVK/OS/MVKGPUCapture.mm
MoltenVK/MoltenVK/Utility/MVKEnvironment.h
MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm

Depth/stencil textures issued from `MTLHeap` can be flaky in some situations, including depth-only rendering on Intel GPUs, and corruption when DS texture with sampling usage is combined with non-DS texture on a single placement heap.
Fixes issues #792 and #832.

Do not create depth/stencil MTLTextures from MTLHeap.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.h
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm

- Fix potential deadlock when `getMTLTexture(MTLPixelFormat)` calls `getMTLTexture()`.
- Defer resetting MTLTexture in `MVKSwapchainImage` until request to acquire.
Fixes issues #835 & #838.

Support screen captures.

---

MoltenVK/MoltenVK/GPUObjects/MVKBuffer.h
MoltenVK/MoltenVK/GPUObjects/MVKBuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKDeviceMemory.mm

According to the Vulkan spec:
> * If `buffer` is a `VkBuffer` not created with the
>   `VK_BUFFER_CREATE_SPARSE_BINDING_BIT` bit set[...] then the
>   `memoryTypeBits` member always contains at least one bit set
>   corresponding to a `VkMemoryType` with a `propertyFlags` that has
>   both the `VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT` bit and the
>   `VK_MEMORY_PROPERTY_HOST_COHERENT_BIT` bit set. In other words,
>   mappable coherent memory **can** always be attached to these
>   objects.
There is no exception for texel buffers. Even though desktop Metal
disallows textures in shared memory, even linear textures created from a
buffer, we have to advertise host-coherent memory for texel buffers.
Some applications actually depend on this behavior, so it's not just a
theoretical concern.
To …

MVKBuffer: Support texel buffers in "host-coherent" memory on Mac.

---

MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.mm
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.h
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

Special thanks to Epic Games for contributing the underlying support to
SPIRV-Cross.
Metal does not support atomic image accesses, but we can work around
that. For buffer views, and for linear image views, we can pass the
underlying buffer to the shader and do atomic accesses on that. For now,
we only support this for `VK_FORMAT_R32_UINT` and `VK_FORMAT_R32_SINT`,
as required by the Vulkan standard; it should theoretically be possible
to extend this to any format where the size of a pixel is 32 bits. Metal
does not yet support 16-bit or 8-bit atomic access, so those formats are
out for now.
Unfortunately, we cannot yet support this for optimal-tiled images, even
though Vulkan requires it. These images do not have a buffer backing
them. Possible alternatives and their downsides:
* Pass a …

MVKDescriptor: Pass buffers to shaders that do atomic image accesses.

---

MoltenVK/MoltenVK/Commands/MVKCmdDispatch.h
MoltenVK/MoltenVK/Commands/MVKCmdDispatch.mm
MoltenVK/MoltenVK/Commands/MVKCmdDraw.h
MoltenVK/MoltenVK/Commands/MVKCmdRenderPass.h
MoltenVK/MoltenVK/Commands/MVKCmdRenderPass.mm
MoltenVK/MoltenVK/Commands/MVKCmdTransfer.h
MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.h
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.h
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

Use just in time convert to Metal values.

In MVKCommand subclasses, replace holding Metal content with holding smaller Vulkan equivalents.

---

Common/MVKOSExtensions.h
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKInstance.h
MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm
MoltenVK/MoltenVK/Utility/MVKEnvironment.h

Use MVK_CONFIG_AUTO_GPU_CAPTURE_OUTPUT_FILE to set the destination file.
This is useful for capturing traces where the program in question cannot
be run under Xcode's control; the captured trace can then be inspected
later with Xcode.
This new feature requires Metal 3.0 (macOS 10.15, iOS 13).

MVKDevice: Support capturing GPU traces to a file.

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.mm
MoltenVK/MoltenVK/GPUObjects/MVKBuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.h
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.mm
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm
MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm

Many of the names of the MVKPixelFormats member functions where inherited from
function names in mvk_datatypes.h, which is a C API, therefore must have unique
function names, and uses parameter types as part of the names to distinguish.
Since MVKPixelFormats is a C++ class, we can do away with that and make use
of function overloading to simplify the function names.
I forgot to to this when creating MVKPixelFormats in the first place.

Rename most MVKPixelFormats member functions to eliminate naming redundancy.

---

MoltenVK/MoltenVK.xcodeproj/project.pbxproj
MoltenVK/MoltenVK/Commands/MVKCmdDebug.mm
MoltenVK/MoltenVK/Commands/MVKCmdDispatch.mm
MoltenVK/MoltenVK/Commands/MVKCmdDraw.mm
MoltenVK/MoltenVK/Commands/MVKCmdPipeline.mm
MoltenVK/MoltenVK/Commands/MVKCmdQueries.mm
MoltenVK/MoltenVK/Commands/MVKCmdRenderPass.h
MoltenVK/MoltenVK/Commands/MVKCmdRenderPass.mm
MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/Commands/MVKCommand.h
MoltenVK/MoltenVK/Commands/MVKCommandPool.h
MoltenVK/MoltenVK/Commands/MVKCommandPool.mm
MoltenVK/MoltenVK/Commands/MVKCommandTypePools.def
MoltenVK/MoltenVK/Vulkan/vulkan.mm

To allow these classes to contain reasonably-sized pre-allocated vectors,
make `MVKCmdSetViewport` & `MVKCmdSetScissor` template classes based on quantities.
Create two concrete implementations of each for 1 and 16 viewports or scissors.
`vkCmdSetViewport()` and `vkCmdSetScissor()` choose which concrete template class
implementation to use based on the number of viewports or scissors, respectively.

Reduce common memory requirements of MVKCmdSetViewport and MVKCmdSetScissor.

---

MoltenVK/MoltenVK/Utility/MVKBaseObject.mm

Happened to me while logging a big shader.

Malloc redoBuff in reportMessage to prevent stack overflow

---

MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.h
MoltenVK/MoltenVK/GPUObjects/MVKBuffer.h

Consider the following (approximate) sequence of commands:
1. vkCmdBindPipeline (compute)
2. vkCmdDispatch: will call setComputePipelineState:_ and mark state as clean
3. vkCmdBeginRenderPass .. draw .. vkCmdEndRenderPass: will endCurrentMetalEncoding()
4. vkCmdDispatch: will recreate mtlComputeEncoder, but won't setComputePipelineState:_ as state is still marked clean, and will crash as a result
AFAIU this is valid usage and binding made in 1. should hold. The patch makes endCurrentMetalEncoding() also mark compute pipeline state as dirty.

Mark computePipelineState as dirty when destroying mtlComputeEncoder

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKInstance.h
MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.h
MoltenVK/MoltenVK/GPUObjects/MVKShaderModule.h
MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm

Crash happened because MVKPhysicalDevices created inline in MVKSmallVector<, 2>
using emplace_back(). Crash occurred when attempting to reallocate memory in
MVKSmallVector, and move inline MVKPhysicalDevice instances. Revert to tracking
MVKPhysicalDevice as pointers, which are easy to move after memory reallocation.
Review and optimize all uses of MVKSmallVector::emplace_back().
Set VkPhysicalDeviceLimits::maxSamplerLodBias to zero since it's unsupported.
Return error and use VK_POLYGON_MODE_LINE for unsupported VK_POLYGON_MODE_POINT.
Fixes issue #875.

Fix crash when more than two GPUs.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.h
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

Support `MTLPixelFormats` with larger values.
`MVKPixelFormats::getVkFormatProperties()` return
reference and log error if unsupported `VkFormat`.
Remove tests for null format name strings.
Consolidate `MVKPhysicalDevice::getFormatProperties()` overloads.

Ensure vkGetPhysicalDeviceFormatProperties() are zerod for unsupported VkFormats.

---

Docs/MoltenVK_Runtime_UserGuide.md

One of the links in the runtime user guide contains a space between the right square bracket and subsequent left round bracket causing the link to display incorrectly in GitHub's markdown reader.

Fix markdown link syntax in MoltenVK_Runtime_UserGuide.md

---

MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

Fixes secondary issue in #888.

vkGetPhysicalDeviceFormatProperties() remove log message for unsupported format when retrieving properties.

---

MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

The buffer binding size looks unused now (?), but the other commit sets it to the specified value.

 Check for stencil only image view in identity swizzle case 

---

.travis.yml

from Xcode 11.3. Also updates macOS version from 10.14.6 to 10.15.4 and JDK from 14.0.0 to 14.0.1

Travis CI: Update to Xcode 11.5

---

MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

6df700f Avoids a div by zero crash below on %= stride line.
I don't have a good test case for 011f029, but searching github for `MTLVertexStepFunctionConstant` reveals that UE4 and Dawn do something similar.

Handle vertex attributes with zero stride

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.h
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.mm

Report format properties only based on the primary MTLPixelFormat
of a VkFormat, not any possible substitution MTLPixelFormat.
Update MoltenVK version to 1.0.43 and `VK_MVK_MOLTENVK_SPEC_VERSION` to 26.
Fixes secondary problem in issue #888.

Fix issue in reporting properties of substitutable VkFormats.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/Commands/MVKMTLBufferAllocation.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/Utility/MVKFoundation.h

Ensure `kMVKUndefinedLarge...` family of constant values are each a power-of-two.
Change several power-of-two math functions to template functions.

Set maxVertexInputBindingStride and maxVertexInputAttributeOffset to min Vulkan values.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

I just noticed that I put `VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_IMAGE_FORMAT_PROPERTIES` in the wrong method.

Move VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_IMAGE_FORMAT_PROPERTIES

---

MoltenVK/MoltenVK/GPUObjects/MVKBuffer.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKDeviceMemory.h
MoltenVK/MoltenVK/GPUObjects/MVKDeviceMemory.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKResource.h
MoltenVK/MoltenVK/GPUObjects/MVKResource.mm

This includes some fixes and consistency improvements to the recent `VK_KHR_sampler_ycbcr_conversion` extension code.
- Fix `MVKImageViewPlane` ignoring swizzle. Allow `MVKImageViewPlane MTLPixelFormat` to be modified by swizzle settings by `MVKImageView::validateSwizzledMTLPixelFormat()`.
- Treat `MVKImageMemoryBinding`, `MVKImagePlane`, and `MVKImageViewPlane` as subclasses of `MVKBaseObject` for lifecycles. Remove use of `unique_ptr` to manage destruction of instances of these classes, and instead, call `destroy()` on them during destruction of `MVKImage` and `MVKImageView`.
- Make `MVKImageViewPlane` a subclass of `MVKBaseDeviceObject` to streamline device access.
- `MVKImageMemoryBinding::needsHostReadSync()` use `MVKPipelineBarrier`, and remove obsolete …

Fixes and consistency improvements to the recent VK_KHR_sampler_ycbcr_conversion extension.

---

MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.mm
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

* descriptorCount measures bytes
* array indices are offsets into the buffer (allow partial read & write)
* missing isInline flag in bind
* missing struct VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_INLINE_UNIFORM_BLOCK_PROPERTIES_EXT

Fixes 4 bugs in VK_EXT_inline_uniform_block

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKBuffer.h
MoltenVK/MoltenVK/GPUObjects/MVKDeviceMemory.h
MoltenVK/MoltenVK/GPUObjects/MVKDeviceMemory.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKResource.h
MoltenVK/MoltenVK/Utility/MVKFoundation.h

Currently, when a mapping is initiated for host-coherent device memory, existing
image contents are copied from the `MTLTexture` to host memory. However, if
host-coherent device memory is already mapped in a long-standing memory mapping,
changes to `MTLTexture` content are not reflected to the host memory.
- This change adds that capability to open memory mappings. When the image pipeline
barrier is applied to an image that is attached to a host-coherent device memory
that currently has an open memory mapping, the `MTLTexture` contents are copied to
the open host memory binding.
- Add `MVKMappedMemoryRange` to retrieve the currently mapped range in an MVKDeviceMemory.
- `MVKImage` cleanup use of `isHostCoherent()`. Let it be same as `MVKDeviceMemory`
and don't test for it from macOS …

Fix issue where mapped host-coherent device memory not updated from image contents on macOS.

---

MoltenVK/MoltenVK/GPUObjects/MVKVulkanAPIObject.h
MoltenVK/MoltenVK/GPUObjects/MVKVulkanAPIObject.mm

This improves performance of these calls by 30%.

Inline MVKVulkanAPIObject::retain()/release() calls.

---

MoltenVK/MoltenVK/GPUObjects/MVKBuffer.h
MoltenVK/MoltenVK/GPUObjects/MVKBuffer.mm

MVKDeviceBuffer cache management code calls the `flushToDevice` and `pullFromDevice` methods on MVKBuffers without regard to their location and overlap with given range. In the first commit I changed those methods to check for overlap and adjust the range, similarly to how it's done in MVKImage.
The other one allows host-coherent texel buffers to be bound as plain buffers using proper host-coherent memory directly, and not the auxiliary buffer. It is only used for buffer views, when a Metal texture needs to be created.
This fixes a problem which arised when using dxvk, which creates buffers with VK_BUFFER_USAGE_UNIFORM_TEXEL_BUFFER_BIT set when the more general D3D11_BIND_SHADER_RESOURCE is used. The root cause of the problem is cache management, or rather the lack of it, for persistently …

Host-coherent texel buffers

---

MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

As discussed in #918.
This comes with a fixed subgroupSize per physical device until VK_EXT_subgroup_size_control is implemented.

Adds VkPhysicalDeviceSubgroupProperties.

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

Fix an inverted condition. We want that to trip when some usage bit *other* than `COLOR_ATTACHMENT` were specified.
Remove an error message. We only support 2D array views on 3D textures for use as render targets, and in Metal, the array length is specified on the render pass descriptor.

MVKImage: Tweak some errors.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

The corresponding Metal format is now documented as supported for
`CAMetalLayer`, confirming my findings in #673.
Only support the 10-10-10-2 formats on macOS. iOS and tvOS instead have
extended-range formats, which unfortunately have no Vulkan equivalents.
I've added them anyway for completeness. I suppose if Vulkan ever does
get these formats, we'll then be ready to expose them as surface
formats.

MVKDevice: Advertise VK_FORMAT_A2B10G10R10_UNORM_PACK32 as a surface format.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm
MoltenVK/MoltenVK/OS/CAMetalLayer+MoltenVK.h
MoltenVK/MoltenVK/OS/CAMetalLayer+MoltenVK.m

- Add CAMetalLayer::colorspaceNameMVK property to handle retain/release automatically.
- Fixes issue #940.

Fix small memory leak when setting swapchain color space.

---

.travis.yml

In .travis.yml, move fetchDependencies run from install section
to script section, and run it with --no-parallel-build option.

Attempt to fix Travis builds.

---

MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

Some things I missed in my review.
These formats use implicit reconstruction, and we don't support explicit
reconstruction here yet. If there's a demand for it, I or someone else
can implement it, but I don't expect it to be an issue.
Because it uses implicit reconstruction, chroma sampling is determined
by the implementation, i.e. Metal. My testing shows that Metal on AMD
and Intel uses midpoint reconstruction. Based on this, I think NV will
be the same.
Finally, according to the Vulkan spec:
> Implicit reconstruction takes place by the samples being interpolated,
> as required by the filter settings of the sampler, *except that
> `chromaFilter` takes precedence for the chroma samples*. [emphasis
> added]
Since Metal obviously uses the same filters for chroma and luma, we
can't support …

MVKPixelFormats: Correct format features for GBGR/BGRG formats.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/Commands/MVKCmdDraw.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

- Add `MVKPhysicalDeviceMetalFeatures::indirectTessellationDrawing`.
- Return error if indirect tessellated draw command is used when not supported.
Fixes #937.

Track if indirect tessellation drawing is supported.

---

MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

It appears the `USCALED` and `SSCALED` vertex formats should be the exact same as their `UINT/SINT` counterparts, just with `ColorFloat` instead of `ColorInt8/UInt8`. The only parts I'm not sure about are the "alt" formats (`UChar2` for `R8_USCALED`, for example) -- for those I just followed what the int formats did.
I tested this patch with the work-in-progress Vulkan backend for the game Murder Miners, which extensively uses *SCALED vertex formats.

Add support for USCALED/SSCALED vertex formats

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKShaderModule.mm

- `MVKShaderLibrary::getMTLFunction()` synchronize and refactor release of Metal objects.
- Make use of existing autorelease pool instead of discrete retain/release.
- Wrap entire specialization operation in `@synchronized()` to guard against Metal internals not coping with multiple simultaneous specializations.
- Fixes issue #961.

Fix intermittent concurrent shader specialization race condition.

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.h
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

This PR is split into 4 commits, fixing four separate issues:
1. Fixes #962 . Linear textures shouldn't be created with MTLTextureUsageRenderTarget on macOS, otherwise Metal validation complains.
2. `MVKImagePlane::overlaps` did not account for device memory offset. Instead it was just using the subresource layout offset, which is relative to the image memory binding (usually 0).
3. `MVKImage._byteCount` was incorrect in some cases. In my case I had a 16x16 RGBA16F texture that reported row pitch of 256 bytes, yet the size of the entire image was 2048 bytes, which is too small (it should be 16x256=4096). 
This was because `MVKImage::getBytesPerLayer` did not account for the row byte alignment, which was 256 in my case - the actual row size was 128 bytes, rounded to byte alignment it was …

Various fixes

---

Docs/Whats_New.md
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm

`MVKComputeResourcesCommandEncoderState` update buffer-size value before buffer
bindings are encoded into Metal and are no longer marked as dirty.
Fixes issue #959.

Fix issue where expected buffer-sizes buffer not bound to Metal compute encoder.

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/GPUObjects/MVKDeviceMemory.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

It looks like pretending to have images in coherent memory strikes again. Here I add flushing to source images of a image to image transfer. That's probably not great, but it fixes some games having invalid data loaded into textures. I'm not sure to what extent this is a dxvk specific problem in my cases.
Maybe we should also flush (and queue a pull from destination images) in other kinds of transfers? Or do something else entirely?

Images in coherent memory

---

MoltenVK/MoltenVK/API/mvk_datatypes.h
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/Commands/MVKCmdDraw.mm
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/Commands/MVKCommandPipelineStateFactoryShaderSource.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
MoltenVK/MoltenVK/Utility/MVKFoundation.h
MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm
MoltenVKShaderConverter/MoltenVKSPIRVToMSLConverter/SPIRVReflection.h

This should hopefully reduce underutilization of the GPU, especially on
GPUs where the thread execution width is greater than the number of
control points.
This also eliminates the extra invocations previously needed to read the
varyings from the vertex shader into the tessellation shader. The number
of threads per workgroup is now lcm(SIMD-size, output control points).
This should ensure we always process a whole number of patches per
workgroup, and further reduce underutilization of the GPU's SIMD units.
To avoid complexity handling indices in the tessellation control shader,
I've also changed the way vertex shaders for tessellation are handled.
They are now compute kernels using Metal's support for vertex-style
stage input. This lets us always emit vertices into the buffer in order
of …

Process multiple patches per workgroup in a tessellation control shader.

---

MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.mm
MoltenVK/MoltenVK/OS/MTLRenderPassDescriptor+MoltenVK.m

There's one more thing - apparently now it's OK, at least on recent macOS, to not have any attachments. It could be useful to take advantage of that and not allocate a dummy texture - not just to save memory, I've seen one game specify a crazy framebuffer size (16k x 16k x 2k) and then spit out validation warnings when the dummy texture wasn't created. I'm not sure how to detect for that though, and if it deserves a dedicated feature bit.
Maybe `MTLRenderPassDescriptor respondsToSelector: defaultRasterSampleCount` check would do the trick?

Validation warning fixes

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.h
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm

It's a hard validation error to do so. We originally had a check for
this, but it was erroneously completely removed in #988, instead of
being limited to `renderTargetArrayLength`.
Fixes #991.

MVKCommandBuffer: Don't set renderTargetArrayLength on devices that don't support it.

---

MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/Commands/MVKCmdDraw.h
MoltenVK/MoltenVK/Commands/MVKCmdDraw.mm
MoltenVK/MoltenVK/Commands/MVKCmdRenderPass.h
MoltenVK/MoltenVK/Commands/MVKCmdRenderPass.mm
MoltenVK/MoltenVK/Commands/MVKCommand.h
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.h
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.h
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.mm

The current code does not handle multiple subpasses, nor does it handle
secondary command buffers. Handling subpasses was easy enough. The
problem came with secondary command buffers. Tracking them became
extremely complicated, particularly since pipelines may be set either
inside or outside a render pass, and further, a pipeline set in one
buffer might be used in another.
I then realized a simpler and more elegant solution: Metal's deferred
store actions feature. This allows you to defer setting the store action
for a render pass until encoding time. This is exactly what we need,
since we won't know what store action we actually want until we start
encoding draws. This solution should now work with multiple subpasses
and secondary command buffers, with much less code.

Use deferred store actions instead of tracking multi-pass draws.

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.h

The attachment index in the `VkClearAttachment` struct is an index into
the current subpass attachment array, not the render pass attachment
array; so it's not enough to check `VkClearAttachment` for
`VK_ATTACHMENT_UNUSED`. We also need to check the current subpass.
If no attachments can be cleared, don't encode a command to the Metal
command buffer.
Perhaps I should bring back `recordBeginRenderPass()` and
`recordEndRenderPass()` (which will be removed in #998) and
keep track of the current subpass; then we can avoid recording
the command entirely if the intersection of the sets
"attachments to clear" and "used attachments" is null.

MVKCmdClearAttachments: Don't attempt to clear unused attachments.

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.h
MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm

Prior to this, we were assuming one layer per clear rect. When that
assumption were broken, we wound up smashing the stack. This will be
more important once multiview support lands, since all views must be
cleared by the clear command.

MVKCmdClearAttachments: Fix vertex count for clearing multiple layers.

---

MoltenVK/MoltenVK/Commands/MVKCmdDraw.mm

Nothing will be drawn in that case. Nothing would've been drawn anyway,
but Metal's validation layer complains if you issue a draw command with
zero vertices or instances.
We unfortunately cannot do anything about indirect draws, since we won't
know how many vertices to draw until execute time.

MVKCmdDraw: Don't encode commands that draw zero vertices.

---

Scripts/create_xcframework_func.sh

XCFramework headers are still unusable due to an Xcode bug (documented in
create_xcframework_func.sh), but in testing for this, modifications to
create_xcframework_func.sh were made to test for the header file so that this
will work correctly when the Xcode bug is fixed and headers can be reintroduced.

create_xcframework_func.sh script check for header availability before copying.

---

MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm

This was introduced by #1006.
Fixes #1007.

MVKCommandBuffer: Fix a crash on starting a query outside a render pass.

---

MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm

Fixes a crash in `dEQP-VK.api.null_handle.free_descriptor_sets`.

MVKDescriptorPool: Only free descriptor sets it knows about.

---

MoltenVK/MoltenVK/GPUObjects/MVKShaderModule.mm

When a pipeline cache were merged into another pipeline cache, we would
create new `MVKShaderLibrary` objects for each one contained in the
source. The objects would be exact copies of the originals... including
their owner, which could be destroyed after the pipeline caches were
merged. Fix the owner in the new objects to prevent a dangling
reference.

MVKShaderLibraryCache: Fix owner of merged MVKShaderLibraries.

---

MoltenVK/MoltenVK/Commands/MVKCmdDraw.mm
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm

Otherwise, they could be left unset when we switch to compute in order
to set up the state for the draw call.
This supersedes part of #1014. The fix to the logic in
`MVKRenderPassAttachment::encodeStoreAction()`, however, is
still necessary.

MVKCommandEncoder: Set store override actions before finalizing draw state.

---

Common/MVKCommonEnvironment.h

The semicolon is the comment character in ARM64 assembly. Just put the
alias symbol definition on another line.

Fix aliases on ARM64.

---

Demos/LunarG-VulkanSamples/API-Samples/API-Samples.xcodeproj/project.pbxproj
Demos/LunarG-VulkanSamples/Cube/Cube.xcodeproj/project.pbxproj
Demos/LunarG-VulkanSamples/Hologram/Hologram.xcodeproj/project.pbxproj
ExternalDependencies.xcodeproj/project.pbxproj
MoltenVK/MoltenVK.xcodeproj/project.pbxproj
MoltenVKShaderConverter/MoltenVKShaderConverter.xcodeproj/project.pbxproj
Scripts/copy_lib_to_staging.sh
Scripts/create_dylib.sh
Scripts/package_moltenvk.sh

Remove EXCLUDED_ARCHS from all Xcode projects to allow fat platform libraries to be built.
Script copy_lib_to_staging.sh no longer breaks fat libraries into single-architecture
libraries, and simply copies fat file to XCFramework staging area.
This permits support for arm64 on macOS, and arm64e on iOS and tvOS.
Creating a Simulator dylib containing both x86_64 and arm64 (Apple Silicon)
architectures is not currently supported by Xcode, so Simulator dylibs are skipped.

Support fat platform libraries in XCFrameworks and dylibs.

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.h
MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm

When doing multisample resolution in Metal, the dimensions of the MSAA
RT and the resolve destination must be the same. Therefore, if the
resolve region does not cover the entire destination, we must use a
temporary transfer image. This fixes a validation error in the differing
image size tests from the CTS
(`dEQP-VK.api.copy_and_blit.*.resolve_image.diff_image_size.*`).
Because the temporary transfer image has the same dimensions as the
destination and is intended to be resolved to it, copies from the source
should use the destination's parameters for the temp image. That way,
the regions show up in the correct place in the destination. This fixes
the remaining resolve tests.
Don't do expansion blits if the resolve region covers the entire
destination. This should reduce the amount of …

MVKCmdResolveImage: Fix resolving sub-regions.

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/Commands/MVKCommandEncodingPool.h
MoltenVK/MoltenVK/Commands/MVKCommandEncodingPool.mm
MoltenVK/MoltenVK/Commands/MVKCommandPipelineStateFactoryShaderSource.h
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.h
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.mm
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

Linear textures on Mac family GPUs aren't renderable, so we cannot use
a `Clear`/`Store` `MTLRenderPass` to clear them. Instead, use a compute
shader to clear them.
I haven't expanded this to all color images, because the
`MTLTextureUsageShaderWrite` usage disables lossless compression on
Apple GPUs, but `RenderTarget` usage does not. Also, multisample
textures do not yet support writing.

MVKCmdClearColorImage: Clear linear images on Mac with a shader.

---

MoltenVK/MoltenVK/Commands/MVKCommandPool.mm
MoltenVK/MoltenVK/Vulkan/vulkan.mm

Prior to this, we were leaking objects after failing to configure them.
The sole exception was `VkDescriptorSet`; failed descriptor sets are
automatically returned to the pool. Now all objects are destroyed or
freed when creation fails.

Destroy/free objects when configuration fails.

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

Or the `MTLSamplerDescriptor` could be leaked.

MVKSampler: Wrap MTLSamplerState creation in an autorelease pool.

---

MoltenVK/MoltenVK/Commands/MVKCmdPipeline.h
MoltenVK/MoltenVK/Commands/MVKCmdPipeline.mm

Fixes a use-after-free bug when the pipeline layout is destroyed after
recording--e.g. in the
`dEQP-VK.api.pipeline_layout.lifetime.destroy_after_end` test.

MVKCmdBindDescriptorSets: Retain given objects.

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/Commands/MVKCommandPipelineStateFactoryShaderSource.h
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.h
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.mm
MoltenVK/MoltenVK/Utility/MVKFoundation.h

This is needed to get us past the 3D blit tests that were recently added
to the CTS. It *almost* passes all these new tests; the 3D format tests
fail for some reason.

MVKCmdBlitImage: Support blits with non-2D images.

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

Some tests intentionally pass an invalid address mode here when
unnormalized coordinates are in use, ostensibly to test that it is
ignored. Metal's validation layer, however, complains if you set
`rAddressMode` to an invalid value, even if `normalizedCoordinates` is
`false`. To avoid this, don't set the `rAddressMode`, since it can't be
used with unnormalized coordinates anyway.

MVKSampler: Ignore addressModeW with unnormalized coordinates.

---

MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

Otherwise, when we try to draw with them, Metal's validation layer will
complain that the primitive type and primitive topology don't match.

MVKGraphicsPipeline: Fail triangle fan pipelines.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.h
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.mm

We actually can't support this. Metal's validation layer complains if
a pipeline has a different raster sample count from that of the
framebuffer, even in the no-attachment case. This means that the
`defaultRasterSampleCount` property must be set correctly if Metal
supports no-attachment rendering, and the sample count of the dummy
texture must be set properly otherwise.

Disable the variableMultisampleRate feature for now.

---

MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

Use the Vulkan binding index to check that the binding is used.
Previously, we were erroneously using the Metal binding index. This
allows vertex binding divisor info to actually be used, and fixes some
tests in the CTS.
Fixes #1041.

MVKGraphicsPipeline: Fix applying divisors to instanced vertex attributes.

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

This doesn't sit well with Metal, which will immediately abort the
program on the attempt.

MVKImage: Reject attempts to create compressed linear images.

---

MoltenVK/MoltenVK/Commands/MVKCmdDraw.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

In an indirect draw, we wouldn't set the pipeline for the vertex stage
to the command encoder, because we had already switched encoders. This
caused havoc down the line, as we wound up running the "convert indirect
buffers" pipeline again, which smashed memory randomly--possibly causing
the GPU to crash, and bringing down the `WindowServer` with it!
Why is it so easy to bring down the `WindowServer` like this?

MVKPipeline: Don't skip setting the vertex stage pipeline.

---

MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKBuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKDeviceMemory.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

Apple assured me that, starting in 10.15.5, linear textures and texture
buffers can be created from buffers with `Shared` storage. I have tested
this and can confirm that it works at least on Big Sur, and probably on
Catalina as well.

Support linear images and buffer views in shared memory on macOS 10.15.5+.

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.h
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

If this bit is set, add `MTLTextureUsage` bits for features supported by
all possible view formats, not just the image format. Happily, Metal's
API validator layer is OK with this.
This is needed for the mutable format tests, which use this bit with a
format that doesn't support writing, then casts the image to a format
which does.

MVKImage: Handle VK_IMAGE_CREATE_EXTENDED_USAGE_BIT.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.h
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

A collection of assorted fixes for `VK_KHR_sampler_ycbcr_conversion`. These get more of the tests passing. Details are in the commit messages.

Y'CbCr fixes

---

MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

Mac GPUs only support 14 dynamic buffers. One of those is used for push
constants, leaving 13 for inline uniform blocks.

MVKDevice: Limit the maximum number of inline uniform blocks on Mac.

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.h
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

Only set `MTLTextureUsagePixelFormatView` if this bit is set. This
should reduce the usage of this bit, which disables lossless compression
on Apple GPUs, in many cases.
We continue to set it anyway for `VK_IMAGE_USAGE_TRANSFER_SRC_BIT`; this
is because we create those texture views on the application's behalf, to
implement `vkCopyImage()` where the source and destination formats do
not agree. We also continue to set it for depth/stencil formats; Metal
requires it in order to use only the stencil aspect in a view.

MVKImage: Handle VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT.

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.h
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

If the image has a format that supports atomic access, or can be cast to
a format which supports atomic access, then use a texel buffer,
regardless of the memory type. If we can't use the `MTLBuffer` from the
device memory, then create our own.
For #1027.

MVKImage: Always use a texel buffer for atomic linear storage images.

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

We don't want to do this for stencil attachment views, because we use
the original packed depth/stencil format in render pipelines, and
Metal's validation layer for some reason doesn't consider packed formats
and their corresponding stencil view formats to match. So only do this
if the image view usage includes `SAMPLED` or `INPUT_ATTACHMENT`.

MVKImage: Only create a stencil view for reading.

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

For planes other than 0, we must add the offset of the first
subresource, so the plane is at the correct place in memory.

MVKImage: Correct offset for texel buffers and heaps.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

vkSetMTLTextureMVK() Fix crash if incoming MTLTexture does not have an IOSurface.

---

Docs/Whats_New.md
fetchDependencies

Building in parallel does not significantly improve performance, and makes it
more difficult to integrate calling fetchDependencies from a larger build script,
because of the need to trap and kill child processes on an error.
Fixes #1002.

fetchDependencies builds serially by default.

---

MoltenVK/MoltenVK/Commands/MVKCmdDraw.mm
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.h
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

One aspect of the `VK_EXT_vertex_attribute_divisor` spec that I
apparently missed is that, for a vertex buffer binding with a divisor of
0, the base instance determines where the attributes are read from. This
cannot be expressed in Metal, but we can emulate it by offseting the
buffer by `firstInstance * stride`.
Unfortunately, we can't do this for indirect draws. If a program tries
this, we're hosed. Maybe I should turn off
`vertexAttributeInstanceRateZeroDivisor` because of this.

Offset vertex buffers for attribute bindings with zero divisors.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/icd/MoltenVK_icd.json

Plus update MoltenVK_icd.json to tell Vulkan Loader and Layers to use Vulkan 1.1.

Fix memory overrun when enabling VkPhysicalDevicePortabilitySubsetFeaturesKHR features.

---

MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm

If there are no attachments and `renderTargetWidth` and
`renderTargetHeight` are zero, the Metal validation layer complains. To
prevent this, ensure both are at least 1.

Ensure there is at least one pixel in the render area.

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

If a shader uses an input attachment and doesn't do layered rendering,
but the image view is of type `MTLTextureType2DArray`, Metal's
validation layer will complain about the texture type mismatching what
the shader expects. This change makes the texture types line up.

MVKImageView: Use a 2D non-arrayed view for 2D non-arrayed attachments.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

At this point in device initialization, the device properties have not
yet been initialized. Unfortunately, this includes the vendor ID, on
which the maximum SIMD-group size depends. Initialize that property so
we can use it to set the subgroup size correctly.

MVKPhysicalDevice: Get the vendor ID before setting the subgroup size.

---

MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

Normally, we would have to check the framebuffer, but we don't know its
contents until draw time. To avoid yet another situation where we must
compile multiple pipelines, I've used a simple heuristic: if the vertex
pipeline writes to `BuiltInLayer`, this is likely for a layered
framebuffer, and we should use `texture_2darray` for subpass input.
Hopefully this is good enough for all intents and purposes. If not, then
we really will have to wait until draw time. And God help us if someone
try to do this with a 3D texture!

MVKPipeline: Use arrayed textures for layered subpass input.

---

MoltenVK/MoltenVK/GPUObjects/MVKDeviceMemory.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/Utility/MVKFoundation.h

Believe it or not, this is valid usage. If an image is aliasable and it
has a dedicated alloc, it is valid for multiple images to bind to the
dedicated memory. Some tests actually try this--for example, the
`dEQP-VK.device_group.afr_dedicated` test.

Allow multiple images for dedicated allocs of aliasabled images.

---

MoltenVK/MoltenVK/Commands/MVKCommandBuffer.h
MoltenVK/MoltenVK/GPUObjects/MVKQueryPool.mm

I missed this when I fixed occlusion queries begun outside a render
pass.

MVKQueryPool: Fix ending a query outside a render pass.

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm

According to the Vulkan spec:
> If `VK_WHOLE_SIZE` is used and the remaining size of the buffer is not
> a multiple of 4, then the nearest **smaller** multiple is used.
> [emphasis added]
Therefore, we should round down when calculating the number of words to
write.

MVKCmdFillBuffer: Round size down, not up.

---

MoltenVK/MoltenVK/Commands/MVKCmdDraw.mm
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

This was a good heuristic, because the index buffer must be bound for
indexed draws. However, it may also be bound for non-indexed draws--for
example, if an indexed draw were immediately followed by a non-indexed
draw, as happens in some `dEQP-VK.synchronization.*` tests. Therefore,
we can't tell from the presence or absence of the index buffer what kind
of draw we're in. We'll have to keep track of this state in the command
encoder.

MVKPipeline: Don't rely on the index buffer to tell apart indexed draws.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

We only want the window server to use the high-performance GPU if we
will use it to present to the display. If we won't use it to present, we
can save some battery life by not using the display. I had hoped this
would help window server stability in case something goes horribly
wrong while using the GPU, but my experience has sadly not borne this
out.
My testing shows that the device returned by
`MTLCreateSystemDefaultDevice()` is exactly equal (i.e. has the same
pointer value) to one of the devices returned by `MTLCopyAllDevices()`,
so we should see no problems from doing this at swapchain create time
instead of device create time.

MVKDevice: Only force a mux switch when a swapchain is created.

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

Fixes use-after-free bugs in `VK_GOOGLE_display_timing` support.

MVKSwapchainImage: Retain image and swapchain until presentation is done.

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm

I know I said I wouldn't have any more, but this fixes a problem with
my change #1064 that could trip Metal's validation layer and/or result in
no data being copied.

MVKCmdCopyImage: Fix a copy-pasto.

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm

It is only available starting in Metal 3.0 (macOS 10.15, iOS/tvOS 13).

MVKCmdCopyImage: Only use the multi-layer copy method if available.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.h
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm
README.md

Don't use `MTLTextureUsagePixelFormatView` if image will only allow views that use same format or its sRGB/linear variation.
- `MVKImage` track `VkImageFormatListCreateInfo::pViewFormats` and validate `MVKImageView` format against them.
- Add `MVKImage::getMTLTextureUsage()` and move tests for dedicated aliasables, compressed formats, and minimum image usage into it.
- Add `MVKMTLFormatDesc::mtlPixelFormatLinear` and `MVKPixelFormats::compatibleAsLinearOrSRGB()` to track linear counterparts to each Metal `sRGB` format.
- Don't use `MTLTextureUsagePixelFormatView` if image will only allow views that use same format or its sRGB/linear variation.
- Propagate `VkImageFormatListCreateInfo` from mutable format swapchain to swapchain images.

Use VK_KHR_image_format_list to disable MTLTextureUsagePixelFormatView where possible.

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

For an `MVKImage`, when we call `vkUseIOSurfaceMVK()`, the `_mtlTexture` object of each plane will be released but not reset. And later when we destroy the `MVKImage`, the destructor of `MVKImagePlane` calls `releaseMTLTexture()` again, which will cause a crash because of double releasing of an object.
To solve this we need to reset `_mtlTexture` to `nil` after it is successfully released.

MVKImagePlane: Reset _mtlTexture after releasing.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueue.h
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.h
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm

Update `MVKPresentableSwapchainImage::presentCAMetalDrawable()` to create a
`MTLCommandBuffer` scheduled-handler and present the `MTLDrawable` from there.
According to feedback from Apple, it is more performant to call `MTLDrawable` present from within a
`MTLCommandBuffer` scheduled-handler than it is to call `MTLCommandBuffer presentDrawable:`.
Pass presentation timing info as a struct to simplify calls.
This may fix issue #929.

Move Metal drawable presentation from MTLCommandBuffer to MTLDrawable.

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

- Retrieve `MTLDrawable` when presentation requested, not in `MTLCommandBuffer` scheduled
handler, in case a different drawable is established by then.
- Call timed present after adding presented handler, to avoid race
condition if presentation happens before handler is added.
Additional fix for issue #929.

Fix potential drawable present race conditions.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

Move setting of limits from `MVKPhysicalDevice::initProperties()` into separate `initLimits()` function. Call `initProperties()` before `initMetalFeatures()` and `initLimits()` after `initMetalFeatures()`.

MVKPhysicalDevice remove need to call initGPUInfoProperties() twice.

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.h
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.mm
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

Prior to this, we weren't even setting the `BLIT_DST` bit for
depth/stencil formats. Conforming apps would thus never pass DS images
at all to `vkCmdBlitImage()`. It is now possible to do that, and even
get scaling and inversion to boot.
Stencil blits require the use of stencil feedback. If this feature isn't
available, both stencil and packed depth/stencil formats have their
`BLIT_SRC` and `BLIT_DST` features turned off, to prevent apps from
attempting to blit the stencil aspect.
There's only a couple of failing tests, involving a 1D stencil blit
(really a 2D stencil with height 1). For some reason, the fragments
produced during a scaled blit get spread out over the rendering surface.
I think this is a bug in Metal; we can't do anything about it.

MVKCmdBlitImage: Support depth/stencil blits with inversion and scaling.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

In #1093 it was reported that `MTLStorageModeShared` textures don't
actually work on 10.15.5, but do work on 10.15.7. I've increased the
minimum to 10.15.6 for now. If someone else reports that it doesn't work
on 10.15.6 either, I'll bump it to 10.15.7.

MVKDevice: Increase minimum OS for shared-storage textures.

---

MoltenVK/MoltenVK/GPUObjects/MVKQueue.h
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm
MoltenVK/MoltenVK/OS/MVKGPUCapture.h
MoltenVK/MoltenVK/OS/MVKGPUCapture.mm

The `MTLCaptureManager`--at least, the one in the capture layer--uniques
capture scopes created for queues. The two scopes we created--for
command buffer submission and surface presentation, respectively--wound
up referring to the same scope. So don't even bother creating a second
one. Use one scope for everything on the queue.
Since there's no need for the 'purpose' parameter anymore, remove it.
Honestly, I think this is a shame. It's useful to be able to create
distinct scopes for command buffer submission and swapchain
presentation. I've filed FB8791712 to get Apple to let us create
multiple scopes for a single queue. Unfortunately, until that's
resolved, because the objects are uniqued, this will interfere with a
forthcoming workaround for a retain bug in Metal relating to capture …

MVKQueue: Only create one GPUCaptureScope per queue.

---

Docs/MoltenVK_Runtime_UserGuide.md
Docs/Whats_New.md

Clarify documentation on mapping limitations for host-coherent image memory on macOS.

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

Otherwise, SPIRV-Cross would generate no texture variable for the
image-sampler.

MVKSamplerYcbcrConversion: Always make sure there is one plane.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

Starting in iOS/tvOS 13, Apple family 4 and up support 124 fragment
input components, matching macOS. Reduce Mac max to 124 to prevent Metal
from complaining when using more than 124 components.
Tessellation control shaders must support at least 120 per-patch output
components, so make sure the limit is that value.

MVKPhysicalDevice: Correct fragment input component limit.

---

MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

But only if we're drawing triangles. The cull mode only applies to
triangles.
In this case, make sure we don't try to add a fragment shader.

MVKPipeline: Also disable rasterization if culling both sides.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

The minimum number of samplers is the lesser of 96 or *n* times the
per-stage maximum, where *n* is the number of stages supported. So we
need to account for compute shaders as well as graphics pipeline
shaders. Do the same for the other types of resources.

MVKPhysicalDevice: Correct max descriptor set resources.

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

This is particularly important if the resource will be aliased with
another resource; the memory in this case must have a linear layout.

MVKImage: Always use texel buffers for linear images in MTLHeaps.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.mm
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm

- Allow binding descriptor set using layout different than it was created with.
- Bind descriptors based on binding number within pipeline layout, not order within layout, and descriptor set looks up descriptor using binding layout it was created with.
- MVKDescriptorSetLayout speed up lookup of descriptor index.
- Streamline binding access in MVKDescriptorSetLayout.  …
- Use temporary MVKSmallVector of bindings to sort dynamic offset indices.
- Use getDescriptor() where in read/write functions.
Fixes issue #1107.

Allow binding descriptor set using layout different than it was created with.

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

Even if we used a texture view. We can't constrain the depth planes in a
3D texture using a texture view, so we need to set the render depth
plane in that case.

MVKImage: Always set the depth plane when rendering to a 3D image.

---

MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.h
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

Metal currently does not support overlapping attribute loads and asserts on
them. Prevent it by shortening format's vector length to fit within the stride,
but print a cautionary message.
An example of affected program is Kingdom Come: Deliverance, which sets attribute
format to RGBA32 in IA and binding stride to 12, while the shader input is just
a float3.

MVKPipeline: shorten vertex attribute format's length when stride < size

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm

This is why the 3D blit tests failed.

MVKCmdBlitImage: Add 0.5 to layer index before interpolating.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

Both Intel and NV Vulkan drivers enable `strictLines`. My testing shows
in fact that AMD and Apple Silicon exhibit the non-strict-line behavior,
while Intel shows the strict-line behavior.

MVKPhysicalDevice: Enable strictLines for Intel and NVIDIA.

---

Docs/MoltenVK_Runtime_UserGuide.md
Docs/Whats_New.md
MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm
MoltenVK/MoltenVK/Layers/MVKExtensions.mm

Conversely, disable capabilities supported by desktop GPUs that are not
supported on Apple GPUs.
Sadly, no support for 16-bit packed pixel formats on non-Apple GPUs.

Support Apple GPU pixel formats with Apple Silicon on Mac.

---

Docs/MoltenVK_Runtime_UserGuide.md
Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/Layers/MVKExtensions.mm

These extensions were previously supported only on iOS and tvOS. Now that macOS will have Apple GPUs, we can use them there, too.

Enable extensions supported by Apple GPUs on Mac

---

MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

Fixes a race condition picked up by `tsan`.

MVKPipelineLayout: Only set configuration result if validating.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

Starting in macOS 10.15, all desktop GPUs support 256 kiB offsets. Apple
GPUs, however, do not support this until family 7. It isn't clear which
one is the supported limit on Apple Silicon Macs with family 5 or 6
GPUs, so I have left the Apple Silicon limit at 64 kiB for now.

MVKPhysicalDevice: Set max visibility buffer size to 256 kiB where supported.

---

MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.mm
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

- Add macros to set `MTLPixelFormatASTC_*_HDR` to `MTLPixelFormatInvalid` on tvOS.
- Use `MTLRenderPipelineDescriptor::inputPrimitiveTopologyMVK` instead of native method.
- Replace use of `MTLDevice::supportsGPUFamily:` with `supportsFamily:`.
- Wrap unused variable of tvOS with conditional compile macro.

Fix tvOS builds and fix supportsGPUFamily: typo.

---

MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

They can now be used as blit destinations and be cleared with a render
pass.
This also fixes a bug where we were incorrectly validating that the
format supported shader writes if the image were linear, even on
iOS/tvOS.

Allow linear images on Apple GPUs in Blit and Clear commands.

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

Added device fallback to make sure that projects that depend on MoltenVK keep working in certain situations like for CI. Also fixed a typo that prevented the project from building

Device fallback and fixed typo

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm

This fixes a bug where the quad drawn by `vkCmdClearAttachments` can be culled if the winding order of the quad happens to match the current pipeline's cull mode. Note that the original cull mode will be restored immediately after the quad is drawn via the existing `cmdEncoder->_graphicsPipelineState.markDirty();` call, so no pushing and popping of state should be necessary.

Disable culling for the duration of vkCmdClearAttachments

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

The M1 chip supports up to GPU family 7. The enum for this was added to
the SDK in the final version of Xcode 12.2; now we can use it.

MVKPhysicalDevice: Enable Apple family 7 features on macOS.

---

MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

We know the actual threadgroup size, because it is declared in the
shader. Therefore, we know the total count of threads per threadgroup,
which is simply the product of the threadgroup size in all three
dimensions. This is necessary if Metal picks a size lower than the app
is expecting. At least one game (NieR: Automata) needs this to work
correctly.

MVKComputePipeline: Override max threads per threadgroup.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

Forbid ETC2 and EAC 3D textures on all platforms. Apple GPUs do not
support 3D for those.

MVKPhysicalDevice: Enable 3D compressed textures on iOS/tvOS.

---

MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.mm
MoltenVK/MoltenVK/Layers/MVKExtensions.mm
MoltenVK/MoltenVK/OS/MTLSamplerDescriptor+MoltenVK.m
MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm

Apple family 7 GPUs (A14) on iOS support multisample layered rendering,
as well as sampler border colors and the mirror clamp to edge sampler
address mode.

Enable some family 7 features on iOS.

---

MoltenVK/MoltenVK/GPUObjects/MVKBuffer.mm

Validation warning in this case seems to be a fairly recent change in Metal.

MVKBufferView: Avoid triggering bytesPerRow validation warning.

---

MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

If it is enabled and nonzero, then force sample-rate shading in the
fragment shader.

MVKGraphicsPipeline: Handle minSampleShading.

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKSync.h
MoltenVK/MoltenVK/GPUObjects/MVKSync.mm

Fix reversed condition in `MVKTimelineSemaphoreEmulated`, which probably
caused some test failures.
Don't increment the `MTLEvent` binary semaphore's counter unless a
command buffer is actually present to schedule a wait on.
Defer signal operations when a swapchain image is not yet available.
That way, the correct value will be signaled when the image is ready,
instead of causing GPU lockups and timeouts.
When a drawable is presented, immediately mark it available, instead of
waiting until the command buffer finishes. Otherwise, the wrong
semaphore could be signaled when an image is used twice in a row.
This should fix the problems using `MTLEvent` binary semaphores with
presentation, which was preventing us from enabling them by default when
available.
Special thanks to @apayen, whose …

MVKSync: Miscellaneous fixes.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/Layers/MVKExtensions.mm

There's a lot of redundant pointer comparison and version checking in
that function. Use a macro to reduce the redundancy.
Advertise `VK_KHR_shader_subgroup_extended_types` on iOS. I forgot to do
this in #1159.

MVKExtensions: Clean up mvkIsSupportedOnPlatform().

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueryPool.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.h
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm
MoltenVK/MoltenVK/GPUObjects/MVKSync.mm
MoltenVK/MoltenVK/Vulkan/vulkan.mm

If a command buffer fails in Metal, its `status` becomes
`MTLCommandBufferStatusError`, and its `error` property is populated. In
Vulkan, command buffer failure usually triggers device loss. This is
because most drivers can't guarantee that resources weren't affected in
an undefined fashion. We can't make that guarantee, either, so when a
Metal command buffer has an error, mark the device lost. The error is
also logged. All waits are immediately signaled; those that were client
requests instead of internal implementation details immediately return
`VK_ERROR_DEVICE_LOST`.
The app may be able to recreate the logical device and reconstruct its
state. However, some Metal errors are severe enough that all subsequent
command buffers will fail--in those cases, the physical device becomes
lost as …

Handle device loss.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/Utility/MVKEnvironment.h

I haven't seen any problems yet. It passes all the tests--even the
`signal_order` tests. I have tried it with some games, and it seems OK
there, too.

Re-enable MTLEvent-based binary semaphores.

---

MoltenVK/MoltenVK/API/mvk_datatypes.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.h
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm

The game NieR: Automata (via DXVK) attempts to create a 1680x1050
swapchain on a 1600x900 window. It then attempts to render to this
swapchain with a 1680x1050 framebuffer. But we created the textures at
1600x900, matching the window. The render area is thus too big, which
triggers a Metal validation failure. Apparently, DXVK doesn't check the
surface caps before creating the Vulkan swapchain.
Rather than expecting the swapchain to be the same size as the layer, we
can actually support any swapchain size, up to the maximum size of a
texture supported by the device. The system will just scale the texture
when rendering it if it doesn't match the layer size. If the sizes don't
match up, we return `VK_SUBOPTIMAL_KHR`, instead of
`VK_ERROR_OUT_OF_DATE_KHR`, indicating that presentation is …

MVKSwapchain: Allow images whose size doesn't match the CAMetalLayer.

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

We can't rely on those enums not being re-`#define`d, because they're
only re-`#define`d like that in MVKPixelFormats.mm.

MVKImage: Fix compilation with Xcode 11.

---

MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

I forgot to do this when I added the `renderLinearTexture` feature.

MVKPixelFormats: Enable RenderTarget usage for linear textures on Apple GPUs.

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

Before we can upload the texture, we need to make sure there is a
texture to upload to.

MVKImagePlane: When sync'ing, create the texture if it doesn't exist.

---

MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.h
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.mm

Memoryless textures cannot use `Load`/`Store` actions, because there is
no memory to load from or store to. So don't use these actions, even if
we're not rendering to the whole thing.
Multiple subpasses might be a problem. Tessellation and indirect
multiview *will* be problems, because these require us to interrupt the
render pass in order to do compute--and that causes us to use `Store`
unconditionally.
One option, which I've mentioned before, is using tile shaders for these
cases. But I haven't looked seriously into that yet. The other involves
a subtle distinction between Metal's `MTLStorageModeMemoryless` and
Vulkan's `VK_MEMORY_TYPE_LAZILY_ALLOCATED_BIT`: the former *never*
commits memory; while the latter doesn't commit memory *at first*, but
may do so later. If we find that we're …

MVKRenderPass: Don't use Load/Store actions for memoryless.

---

MoltenVK/MoltenVK/GPUObjects/MVKDeviceMemory.h

I missed this when I added support for memoryless on macOS.

MVKDeviceMemory: Don't consider Memoryless host-accessible on macOS/tvOS.

---

MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/Commands/MVKCmdPipeline.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

Apple GPUs don't support them, and in fact Metal's validation layer will
complain if you try to use them.

Don't use barriers in render passes on Apple GPUs.

---

MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.mm

This parameter is intended to indicate the optimal granularity for the
render area. For TBDR GPUs, this will be the tile size. IMR GPUs
continue to use 1x1.
Apple GPUs support tile sizes of 16x16, 32x16, and 32x32. But, we can't
read the tile size used for a Metal render pass until a render command
encoder has been created. So for now, hardcode 32x32 for TBDR GPUs.

MVKRenderPass: Use a non-trivial granularity for TBDR GPUs.

---

MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.mm

MVKRenderPass: Only use MTLStorageModeMemoryless where available.

---

README.md

I believe this information is unnecessary if you read the document in github for example. Just an idea. Feel free to close the issue if you see any reason to not apply this change.

Hide note about a markdown reader if you already use one.

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm

fix incorrectly changing first resolve layer's src/dst base layer,
as well and out of bounds access to the mtlResolveSlices array

fix incorrect behavior for MVKCmdResolveImage

---

MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

Plus add documentation for VK_SEMAPHORE_TYPE_TIMELINE.
Fixes issue #1180.

For Vulkan semaphores, prefer using MTLFence over MTLEvent.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVKShaderConverter/MoltenVKShaderConverterTool/OSSupport.mm

Add `MVKDevice::mslVersionIsAtLeast()` to support tests for MSL version.
Also bump MSL support level of standalone `MoltenVKShaderConverter` tool.
Fixes #1203.

Advertise support for shaderInt64 feature.

---

Docs/MoltenVK_Runtime_UserGuide.md
Docs/Whats_New.md
MoltenVK/MoltenVK.xcodeproj/project.pbxproj
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKInstance.h
MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueryPool.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm
MoltenVK/MoltenVK/GPUObjects/MVKShaderModule.mm
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm
MoltenVK/MoltenVK/GPUObjects/MVKSync.mm
MoltenVK/MoltenVK/Layers/MVKExtensions.mm
MoltenVK/MoltenVK/OS/CAMetalLayer+MoltenVK.m
MoltenVK/MoltenVK/OS/MTLRenderPassDepthAttachmentDescriptor+MoltenVK.m
MoltenVK/MoltenVK/OS/MTLRenderPassDescriptor+MoltenVK.m
MoltenVK/MoltenVK/OS/MTLRenderPassStencilAttachmentDescriptor+MoltenVK.m
MoltenVK/MoltenVK/OS/MTLSamplerDescriptor+MoltenVK.m
MoltenVK/MoltenVK/Utility/MVKBaseObject.mm
MoltenVK/MoltenVK/Utility/MVKEnvironment.cpp
MoltenVK/MoltenVK/Utility/MVKEnvironment.h
MoltenVK/MoltenVK/Vulkan/mvk_datatypes.hpp
MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm
MoltenVK/MoltenVK/Vulkan/vk_mvk_moltenvk.mm
MoltenVK/MoltenVK/Vulkan/vulkan.mm

MVKConfiguration access is now global, and the `VkInstance` provided in the
`vkGet/Set/MoltenVKConfigurationMVK()` functions is ignored. This allows these
functions to be provided with a `VkInstance` object that originates from a
different Vulkan layer than MoltenVK, without risking breaking the API.
`MVKConfiguration` extended to cover all MoltenVK environment variables.
Move all environment variable declarations to `MVKEnvironment.h`.
Add `MVKEnvironment.cpp` to define config functions.
Cleanup `.m` files to use `MVKCommonEnvironment.h` instead of `MVKEnvironment.h`.

Make MVKConfiguration access global, ignoring provided VkInstance.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

We've seen reports that rendering without attachments doesn't work on
family 1 GPUs. Disable it for them.
According to the Metal Feature Set Tables, only family 2 supports
quad-scope permutation. We've been seeing issues with SIMD-group
functions on family 1 hardware, so for now I'm moving quad-group
permutation to family 2.

Require Mac family 2 for some features

---

MoltenVK/MoltenVK/Commands/MVKCmdQueries.mm
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.h
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.h
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/Commands/MVKCommandEncodingPool.h
MoltenVK/MoltenVK/Commands/MVKCommandEncodingPool.mm
MoltenVK/MoltenVK/Commands/MVKCommandPipelineStateFactoryShaderSource.h
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.h
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueryPool.h
MoltenVK/MoltenVK/GPUObjects/MVKQueryPool.mm
MoltenVK/MoltenVK/Utility/MVKFoundation.h

Instead of having Metal directly write to the query pool's internal
storage, we'll have it write to a temp buffer whose lifetime is tied to
the command buffer. The temp buffer's contents are then accumulated to
all queries that were activated.
This last step is particularly important for queries that span multiple
render passes. Since Metal resets the query counter at a render pass
boundary, this means that, up until now, only the last draw counted
toward the query. Data from the others were lost. By using this temp
buffer and accumulating the results to the query storage, the counter
will correctly count draws from all render passes inside the query
bounds.
This will also fix problems using multiple query pools, particularly
with large query pool support on, in a single render pass. …

MVKQueryPool: Totally rework the way occlusion queries work.

---

MoltenVK/MoltenVK/Commands/MVKCommandBuffer.h
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/Commands/MVKCommandEncodingPool.h
MoltenVK/MoltenVK/Commands/MVKCommandEncodingPool.mm
MoltenVK/MoltenVK/Commands/MVKMTLBufferAllocation.h
MoltenVK/MoltenVK/Commands/MVKMTLBufferAllocation.mm

Add support for "dedicated" temp buffers, where instead of allocating a
big buffer and carving regions out of it, a unique buffer is returned
for each allocation request. This is necessary for visibility buffers,
because the offset passed to `-[MTLRenderCommandEncoder
setVisibilityResultMode:offset:]` cannot exceed an
implementation-defined value, currently 256k less 8 bytes for Mac family
2 on Catalina and up, and on Apple family 7; and 64k less 8 bytes
otherwise.

MVKCommandEncoder: Use the temp buffer mechanism for visibility buffers.

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/Commands/MVKMTLBufferAllocation.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueryPool.mm

They are not expected to be useful beyond the commands that use them,
but they take up memory nonetheless. This is exactly the use case
purgeability was designed for. Tell the system that it's OK to reclaim
their memory if necessary.
Doing this every time the buffer is used will cause the purgeable state
to be reset from `MTLPurgeableStateEmpty`, in case the system really did
reclaim their memory.
In accordance with Apple's advice, lock the pages for the buffer when
loading it, so the memory isn't pulled out from under us.
Fixes #1231.

MVKMTLBufferAllocation: Mark temp buffers as volatile.

---

MoltenVK/MoltenVK/Commands/MVKCmdDraw.mm
MoltenVK/MoltenVK/GPUObjects/MVKBuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDeviceMemory.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.mm

Add MVKDeviceTrackingMixin::getPhysicalDevice() to streamline access.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

It is possible for the maximum buffer size to be 4 binary gigabytes or
greater. In that case, the upper 32 bits will be lost, and the value of
the `maxUniformBufferRange` and `maxStorageBufferRange` limits would be
too small or even zero. Clamp it to 4 GiB - 1 in that case, since that
is the maximum value of a 32-bit integer.
For #1240.

MVKPhysicalDevice: Clamp maximum buffer range to 4 GiB - 1.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/Utility/MVKEnvironment.cpp
MoltenVK/MoltenVK/Vulkan/vk_mvk_moltenvk.mm

When app sets `MVKConfiguration`, if struct not fully populated by app, or if app sets strings to `null`,
copy can fail. Test for this before copying.
Also unrelated trivial tweak to What's New doc.

Test for null string on MVKConfiguration copy.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

Our testing shows that none of the SIMD-group functions work on family
1, including `simd_is_first()`, which is needed for even `BASIC`
support.

MVKPhysicalDevice: Disable SIMD-group permutation for Mac family 1.

---

MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.h
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/Vulkan/vk_mvk_moltenvk.mm

Don't reset `MVKOcclusionQueryCommandEncoderState::_mtlVisibilityResultOffset`
when ending occlusion query, as subsequent queries need different offsets.
Also, remove `MVKOcclusionQueryCommandEncoderState::_needsVisibilityResultMTLBuffer`,
as it is always set once from `MVKCommandBuffer::_needsVisibilityResultMTLBuffer`.
The current logic around deciding whether a visibility buffer is needed is relatively crude. Currently, it is applied to all render passes in a Vulkan command buffer based on at least one occlusion query being present. A Metal renderpass needs a visibility buffer if a query is started either before it or inside it. For a command buffer with multiple Metal render passes, not all of them may need it. 
Fixing that logic was out of scope for this PR, but I'll add another …

Fix Metal validation error of duplicate visibility offsets.

---

MoltenVKPackaging.xcodeproj/project.pbxproj
README.md

Document availability of GitHub Discussions in `README.md`.
Expose `.github/workflows/CI.yml` in MoltenVKPackaging Xcode project.
Fixes #1259.

GitHub repository enhancements.

---

Docs/MoltenVK_Runtime_UserGuide.md
Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKShaderModule.mm

Shader code should be submitted as SPIR-V. Although some simple direct MSL shaders may work,
direct loading of MSL source code or compiled MSL code is not officially supported at this time.
Future versions of MoltenVK may support direct MSL submission again.
Addresses issue #1253

Remove official support for direct MSL shader loading from documentation.

---

MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.h
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

`MVKCommandEncoderState` has numerous subclasses, and the polymorphic
`MVKCommandEncoderState::resetImpl()` requires significant maintenance
across these subclasses. It's only use was in disabling depth-stencil state.
Remove `MVKCommandEncoderState::reset()` and all implementations of `resetImpl()`
across all `MVKCommandEncoderState` subclasses.
Remove `MVKPipeline::__hasDepthStencilInfo` and disable depth-stencil state
automatically via cleared Vulkan struct in `MVKPipeline`.
Fixes #1264.

Remove MVKCommandEncoderState::reset().

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
MoltenVK/MoltenVK/GPUObjects/MVKShaderModule.mm

`MTLDevice` retains an internal object web that is used during the creation of
new objects, such as pipeline states, libraries, functions, and samplers.
Simultaneously creating and destroying objects of these types can trigger
race conditions on the internal `MTLDevice` content.
Wrap the following in `@synchronized (mtlDevice) {...}`:
- `MTLRenderPipelineState` creation and destruction
- `MTLComputePipelineState` creation and destruction
- `MTLLibrary` creation
- `MTLFunction` creation
- `MTLSampler` creation and destruction
Fixes #1269.

Fixes for CTS multithread tests.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

This value is derived from limit expected by SPIRV-Cross.
The previous unbounded value was breaking CTS tests that used this value.

Report accurate value for VkPhysicalDeviceLimits::maxBoundDescriptorSets.

---

Common/MVKCommonEnvironment.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

Derive `MVK_APPLE_SILICON` from target CPU.
Derive `MVK_MACOS_APPLE_SILICON` from target CPU and macOS platform.
Derive `MVK_XCODE_12` from macOS and iOS SDK versions.
Test for simulator on non-Apple GPU using `MVK_OS_SIMULATOR` && !MVK_APPLE_SILICON`.
Fixes issue #1250.

Set Metal buffer alignment to 256 on non-Apple Silicon iOS/tvOS simulators.

---

MoltenVK/MoltenVK/Commands/MVKCmdDraw.mm
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.h
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/Commands/MVKCommandEncodingPool.h
MoltenVK/MoltenVK/Commands/MVKCommandEncodingPool.mm
MoltenVK/MoltenVK/Commands/MVKMTLBufferAllocation.h
MoltenVK/MoltenVK/Commands/MVKMTLBufferAllocation.mm

Some buffers, particularly those used by tessellation, indirect
multiview, or occlusion queries, are never written or read from the
host. Keeping the relevant data in VRAM should improve performance by
reducing the need for the GPU to make expensive accesses over the PCI
bus.
VRAM is a scarce resource on discrete GPUs, but this is part of why we
marked the buffers volatile.

MVKMTLBufferAllocation: Support private temp buffers.

---

MoltenVK/MoltenVK/Commands/MVKCommandPool.mm
MoltenVK/MoltenVK/GPUObjects/MVKDeviceMemory.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueue.h
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm

If we're on macOS 11 or iOS/tvOS 14, and debug mode (`MVK_DEBUG=1`) were
enabled, then we'll enable enhanced command buffer errors, which give us
more information about which encoder triggered the error. We'll also
print log messages from shader validation.

Log enhanced command buffer errors in debug mode.

---

MoltenVK/MoltenVK/GPUObjects/MVKQueue.h
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm

Recent enhancements to shader logging triggered `MTLCommandBuffer` completion handler race condition.
Fixes to `MVKQueueCommandBufferSubmission`:
- Consolidate `MTLCommandBuffer` completion callbacks, and ensure all other activities,
including logging, which references the object, occurs before `finish()` is called.
- Remove separate flag that indicates whether to track `MTLCommandBuffer` completion times.
- Localize Vulkan error reporting to the queue instead of the device.
- Reduce debug log noise by only logging header msg for shader debug logs if at least one shader log exists.

Ensure queue submission message logging occurs before submission object is destroyed.

---

MoltenVK/MoltenVK/GPUObjects/MVKInstance.h

When `mvkGetMVKConfiguration()->advertiseExtensions` is disabled, and MoltenVK
artificially advertises that all extensions are not supported, allow the functions
of those extensions to be called anyway.
Some CTS tests are structured to assume one or more basic extensions are supported,
and currently do not bother checking for those extensions and provide alternate code paths
based on the extension not being supported. Permitting the calls to be made anyway
allows those tests to proceed and avoid crashing.
I have posted a [CTS issue](https://github.com/KhronosGroup/VK-GL-CTS/issues/245) to request the underlying situation be fixed.

Permit extension functions when all extensions have been disabled via configuration.

---

Docs/Whats_New.md
MoltenVK/MoltenVK.xcodeproj/project.pbxproj
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.h
MoltenVKShaderConverter/Common/SPIRVSupport.cpp
MoltenVKShaderConverter/MoltenVKShaderConverter.xcodeproj/project.pbxproj
MoltenVKShaderConverter/MoltenVKShaderConverter/GLSLToSPIRVConverter.cpp
MoltenVKShaderConverter/MoltenVKShaderConverter/SPIRVReflection.h
MoltenVKShaderConverter/MoltenVKShaderConverter/SPIRVToMSLConverter.h

Remove `SPIRV-Cross/` qualifier from include references to SPIRV-Cross header files.
Remove `glslang/` qualifier from include references to glslang header files.
This change allows easier integration with app build scripts.
Fixes issue #1279.

Remove project qualifiers from references to SPIRV-Cross and glslang header files.

---

MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm
MoltenVK/MoltenVK/Utility/MVKEnvironment.h

Only start frame-scope automatic GPU capture on queue identified by `MVKConfiguration::defaultGPUCaptureScopeQueueFamilyIndex`
and `defaultGPUCaptureScopeQueueIndex`.
Introduce `MVKConfigAutoGPUCaptureScopeBits` enum to specify values of
`MVKConfiguration::autoGPUCaptureScope` in a Vulkan-friendly manner,
while automatically documenting the same values for env vars.
Update some config documentation.
Fixes #1296.

Fixes to auto GPU capture

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm

- Fix `MVKPhysicalDevice::getSurfaceFormats()` returning `VK_FORMAT_UNDEFINED`
in available surface formats when a Metal surface format is available that
doesn't map to a defined Vulkan format (eg. `MTLPixelFormatBGRA10_XR`).
- Restore support for `VK_COLOR_SPACE_HDR10_HLG_EXT` and `VK_COLOR_SPACE_HDR10_ST2084_EXT`
under Xcode12 that was removed due to App Store conflicts using older enum values.
- Don't assume the incoming `CAMetalLayer` has default (no-op) values for `colorspace` and
`wantsExtendedDynamicRangeContent` properties, since they could have been set externally.
Ensure the Vulkan app has control over both of these properties.
- `vkCreateSwapchainKHR()` returns `VK_ERROR_FORMAT_NOT_SUPPORTED` for unsupported colorspaces.
Fixes issues #1292 and #1299.

Several surface format and colorspace fixes.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.mm
MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm

For memoryless attachments, setting renderpass load and store
actions to "load" and "store" triggers Metal validation errors.
Refactor determination of renderpass `MTLLoadAction` and `MTLStoreAction`.
For memoryless attachments, replace load with don't care,
and store with resolve or don't care.
Fixes #1308.
@cdavis5e Can you sanity-check my refactored`MTLLoadAction` and `MTLStoreAction` logic, please?

In a renderpass, don't load or store memoryless attachments.

---

MoltenVK/MoltenVK.xcodeproj/project.pbxproj
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm
MoltenVK/MoltenVK/Utility/MVKBitArray.h

Add `MVKBitArray` class.
Consolidate `MVKPreallocatedDescriptors` into `MVKDescriptorPool`
and remove `MVKPreallocatedDescriptors`.
This refactor is part of the larger project for introducing Metal argument buffers. Pushing this out now as part of a cleanup as I rework the actual argument buffer design.

Refactor preallocated descriptor handling.

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.h
MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.mm
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm

`MVKDescriptor` subclasses: Simplify interface and reduce redundant content.
Remove `MVKDescriptor::setLayout()` and pass `MVKDescriptorSetLayoutBinding`
to `MVKDescriptor::bind(), write(), and read()`.
Remove `MVKSamplerDescriptorMixin::_hasDynamicSampler`.
Remove `MVKInlineUniformBlockDescriptor::_length`.
`MVKDescriptor` subclasses: Reduce unused content.
Don't populate `MVKMTLBufferBinding::size` unless using `mtlBytes` and `isInline`.
Remove `MVKBufferDescriptor::_buffRange`.
Remove `MVKImageDescriptor::_imageLayout`.
Remove `MVKCmdBufferImageCopy::_imageLayout`.
Another prep step compatible with argument buffers.

MVKDescriptor subclasses: Reduce redundant and unused content.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/Utility/MVKEnvironment.h

- Preallocate a pool of descriptors by default.
- Enable `MVKConfiguration::preallocateDescriptors` and
`MVK_CONFIG_PREALLOCATE_DESCRIPTORS` by default.
- Rename MVKDescriptorTypePreallocation to `MVKDescriptorTypePool`.
- `MVKDescriptorPool` optimize reseting descriptor pool.
- Don't free individual pooled descriptors during a pool reset.
- Don't mark availability of individual descriptor sets during a pool reset.
- Add `MVKDescriptorPool::_hasPooledDescriptors` as SVOT to track if descriptors
are pooled, and is set from outside constructor to ensure all internal
descriptor pools are constructed with the same SVOT.
- `MVKDescriptorPool::allocateDescriptorSet()` ensure correct result returned.
- `MVKDescriptorPool` pools its descriptor sets.

Descriptor pooling enhancements

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

The test for single-texel capability used a mod calculation to compare the linear
alignment requirement reported by Metal to the texel size. Instead, it should use an
inequality comparison, to check if the alignment requirement is LTE the texel size.
Fixes #1318.

Fix advertising single-texel alignment capability for texel buffers.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKInstance.h
MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueryPool.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm
MoltenVK/MoltenVK/GPUObjects/MVKShaderModule.mm
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm
MoltenVK/MoltenVK/GPUObjects/MVKSync.mm
MoltenVK/MoltenVK/Layers/MVKExtensions.mm
MoltenVK/MoltenVK/Layers/MVKLayers.mm
MoltenVK/MoltenVK/Utility/MVKBaseObject.mm
MoltenVK/MoltenVK/Utility/MVKEnvironment.cpp
MoltenVK/MoltenVK/Utility/MVKEnvironment.h
MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm
MoltenVK/MoltenVK/Vulkan/vk_mvk_moltenvk.mm
MoltenVK/MoltenVK/Vulkan/vulkan.mm

Appears everywhere, and commonly in if-statements, etc. Thought it would be helpful to have it concise.
This change does not affect the app-facing API.

Rename mvkGetMVKConfiguration() to mvkConfig() for brevity.

---

MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.mm
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/Utility/MVKBitArray.h

Move tracking descriptor index to `MVKDescriptorSetLayoutBinding` from `MVKDescriptorSetLayout`.
Refactor `MVKDescriptorSet::write()` to be more DRY.
Grow and shrink `MVKDescriptorSet` memory consumption during allocate and free.
`MVKPhysicalDevice` refactor layout of `pipelineCacheUUID` to remove redundancy in MoltenVK
revision and allow tracking of enabled features that affect pipeline cache content.
`MVKBitArray` support resizing and simplify setBit() functionality.

Several underlying non-functional changes towards Metal argument buffer support.

---

MoltenVK/MoltenVK/Commands/MVKCommand.h
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.h
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/Commands/MVKMTLBufferAllocation.h
MoltenVK/MoltenVK/Commands/MVKMTLBufferAllocation.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h

Check allocations are larger than `MTLBuffer` alignment to avoid Metal errors.
Align returning safely with allocating safely, and change callers to use
`MVKMTLBufferAllocation::returnToPool()` globally, to ensure this match.
Fix use of const on `returnToPool()`;
Move `MVKCommandEncoder::copyToTempMTLBufferAllocation()`
and support setting private and dedicated flags.
Align constructor parameter order on `MVKMTLBufferAllocationPool`
with that of `MVKMTLBufferAllocator`.
Move subclass overrides of `MVKObjectPool::newObject()` to protected access.

Enhancements and fixes to temporary MTLBuffer allocation.

---

Demos/Cube/iOS/DemoViewController.m
Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.h
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm

Add Cube app iOS device rotation support, to test swapchain destruction on iOS.
Fixes issue #1324.

Fix memory leak where swapchains and images were not destroyed due to a retention loop.

---

MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm
MoltenVK/MoltenVK/Utility/MVKEnvironment.cpp
MoltenVK/MoltenVK/Utility/MVKEnvironment.h

Add `MVKConfiguration::resumeLostDevice` and `MVK_CONFIG_RESUME_LOST_DEVICE` env var,
to allow VkDevice to resume after non-fatal VK_ERROR_DEVICE_LOST error.
When running CTS, when one test triggers a `VK_ERROR_DEVICE_LOST` error condition,
CTS does not create a new `VkDevice` for subsequent tests, which causes all subsequent
tests to fail. This creates an incredible amount of results noise, and makes it
difficult to determine accurate test failure numbers. This is particularly problematic
because `VK_ERROR_DEVICE_LOST` may be triggered sporadically by internal Metal issues,
often making it not traceable to a consistent failure of a particular CTS test.

Add MVKConfiguration::resumeLostDevice and MVK_CONFIG_RESUME_LOST_DEVICE env var.

---

MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h

Those functions are also usable from standard C, no need for the caller
to be compiled as Objective-C. Move their definition outside the __OBJC__
guards.

Expose vkGetIOSurfaceMVK() / vkUseIOSurfaceMVK() also under non-ObjC.

---

MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm

vkGetPastPresentationTimingGOOGLE() does not have return status codes and proper
return values for the pPresentationTimingCount in/out parameter wrt. the specification.
The queuing of returned presentation timing records is also not in agreement with the
spec. This confuses client applications and requires awkward workarounds.
These two commits should fix this.

Compliance fixes for VK_GOOGLE_display_timing extension implementation.

---

MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.mm

I believe SPIRV_CROSS_NAMESPACE_OVERRIDE should be replaced by SPIRV_CROSS_NAMESPACE defined in SPIRV-Cross spirv_common.hpp. This ensures that SPIRV_CROSS_NAMESPACE_OVERRIDE usage in MVK is optional.

Use SPIRV_CROSS_NAMESPACE define in MVKDescriptor.mm

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/mvk_datatypes.h
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKInstance.h
MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueryPool.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm
MoltenVK/MoltenVK/GPUObjects/MVKShaderModule.mm
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm
MoltenVK/MoltenVK/GPUObjects/MVKSync.mm
MoltenVK/MoltenVK/Layers/MVKExtensions.mm
MoltenVK/MoltenVK/Layers/MVKLayers.mm
MoltenVK/MoltenVK/Utility/MVKBaseObject.mm
MoltenVK/MoltenVK/Utility/MVKEnvironment.cpp
MoltenVK/MoltenVK/Utility/MVKEnvironment.h
MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm
MoltenVK/MoltenVK/Vulkan/vk_mvk_moltenvk.mm
MoltenVK/MoltenVK/Vulkan/vulkan.mm

Rename `kMVKShaderStageMax` to `kMVKShaderStageCount` to clarify it's common use in array sizing and for loops.
Change `mvkConfig()` to return reference instead of pointer to improve syntactic sugar to use `.` instead of `->`.
Update MoltenVK version to 1.1.4.
Update _What's New_ document.

Miscellaneous non-functional maintainability updates.

---

MoltenVK/MoltenVK/GPUObjects/MVKQueue.h
MoltenVK/MoltenVK/GPUObjects/MVKVulkanAPIObject.h
MoltenVK/MoltenVK/GPUObjects/MVKVulkanAPIObject.mm
MoltenVK/MoltenVK/Utility/MVKBaseObject.h

Separate reference counting from `MVKVulkanAPIObject` into a new `MVKReferenceCountingMixin` class, so reference counting can potentially be used in other areas of the class hierarchy.
Replace `MVKConfigurableObject` with `MVKConfigurableMixin` for the same reason.
Remove some inline definitions as unnecessary in the files being revised here.

Add class mixins for reference counting and configuration results.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm

Fix crash when requesting MTLCommandBuffer logs in runtime debug mode on older OS versions.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

MVKImagePlane::getMTLTexture() protect against crash when image has no device memory bound.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

These new cards are supported in the 11.4 beta.

MVKDevice: Add new AMD devices supporting 32 lanes.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

Adjust `VkPhysicalDeviceLimits` values:
- `minMemoryMapAlignment` raised to MIN of 64 per Vulkan spec.
- `pointSizeRange` upper limit to 511 per Metal.
- `lineWidthGranularity` to 0 per Vulkan spec when wideLines disabled.
- `maxSamplerLodBias` set to 4 to cover setting in shader.

Fixes for CTS dEQP-VK.info.device_properties failures.

---

MoltenVK/MoltenVK/API/mvk_datatypes.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm

- `mvkMTLSamplerAddressModeFromVkSamplerAddressMode()` support `MTLSamplerAddressModeClampToBorderColor` and `MTLSamplerAddressModeMirrorClampToEdge` if available.
- Add `MVKSampler::getMTLSamplerAddressMode()` to test for device feature availability.
Remove special border color handling in `MVKSampler::newMTLSamplerDescriptor()`.

Cleanup handling of sampler border color and mirror edge clamp.

---

MoltenVK/MoltenVK/GPUObjects/MVKInstance.h

Previously we had loosened the behavior so that function proc addresses are returned
for an extension function even if that extension is disabled, if the API was artificially
restricted during testing, to bypass CTS tests that appeared to assume certain
extension functions were available.
This loosening in turn caused the `dEQP-VK.api.version_check.entry_points` test to fail,
so the restriction is reapplied and only functions from enabled extensions are published.

Revert to strict publishing of functions only from enabled extensions.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h

Move mutex lock for using `MTLArgumentEncoder` to `MVKMTLArgumentEncoder` to be tracked along with the `MTLArgumentEncoder` it guards. Previously, the mutex was tracked in `MVKPipeline`, which did not guard any `MTLArgumentEncoder` that came from an `MVKDescriptorSetLayout`.

Fix synchronization issue with locking MTLArgumentEncoder.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

Was causing some CTS attachment clearing tests to fail, or incorrectly report Not Supported, on Apple Silicon.

Fix inconsistent handling of linear attachment decisions on Apple Silicon.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueue.h
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm

- Fix race condition on `MVKQueueCommandBufferSubmission` fence during device loss.
- `MVKQueueCommandBufferSubmission` `retain()` and `release()` fence and signal semaphores
to ensure they live long enough for the submission to finish using them.
- On command buffer submission failure, if `MVKConfiguration::resumeLostDevice` enabled,
do not release waits on `VkDevice`, and do not return `VK_ERROR_DEVICE_LOST`, unless
`VkPhysicalDevice` is also lost.
Fixes #1366. But I decided not to do anything further about moving `markLost()` to `MVKPhysicalDevice`. The Vulkan spec is clear that the app should destroy and re-create a `VkDevice` under these conditions, so the current behavior is correct (even if the spec is heavy-handed). I did change the behavior under …

Device loss fixes

---

MoltenVK/MoltenVK/Commands/MVKCommandBuffer.h
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/Commands/MVKCommandPool.mm
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKDeviceMemory.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueue.h
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm
MoltenVK/MoltenVK/Utility/MVKFoundation.h
MoltenVK/MoltenVK/Vulkan/vulkan.mm

Extend `MVKCommandUse` enum to identify additional command buffer uses.
`MVKQueueCommandBufferSubmission` track use type.
`MVKQueue` pass use type in functions that result in creation of a `MTLCommandBuffer`.
Add `mvkMTLCommandBufferLabel()` to map use types to label strings.

Add label strings to MTLCommandBuffers, based on use type, for GPU Capture debugging.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKBuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

Don't allow memoryless storage for `VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT`.
Memoryless storage for `VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT` descriptors
requires support for, and use of, shader framebuffer fetch.
Remove compile-time checking for `MVK_APPLE_SILICON` before disabling memoryless storage
for buffers and images, since the requirement exists for all platforms, and memoryless
storage will already otherwise be disabled on other platforms anyway.

Fix crash using memoryless storage for input attachments on Apple Silicon.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/Commands/MVKCmdRenderPass.h
MoltenVK/MoltenVK/Commands/MVKCmdRenderPass.mm
MoltenVK/MoltenVK/GPUObjects/MVKFramebuffer.h
MoltenVK/MoltenVK/Vulkan/vulkan.mm

PR #1370 introduced a bug by not clearing attachments when `MVKCmdBeginRenderPass` instances were reused from the command pool.
While fixing that, I also cleaned up some redundancies in the `vkCmdBeginRenderPass()` and `vkCmdBeginRenderPass2KHR()` functions and `MVKCmdBeginRenderPass` constructors.
- Clear attachments in `MVKCmdBeginRenderPass` between invocations. Fixes crash due to incorrect number of attachments.
- Consolidate `vkCmdBeginRenderPass()` and `vkCmdBeginRenderPass2KHR()` handling.
- Derive `MVKCmdBeginRenderPass` attachment count and imageless status once.
@f32by please review relative to the recent #1370. I can't request you as a reviewer from the list until you accept the collaboration request.

Begin renderpass fixes

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKDeviceMemory.h
MoltenVK/MoltenVK/GPUObjects/MVKDeviceMemory.mm

`MVKDeviceMemory` track original Vulkan memory coherency request, not just Metal coherency status.
`MVKDeviceMemory map()/unmap()` only triggers host flush if coherent Vulkan memory was requested, not just when Metal memory is coherent, because this can be changed for dedicated image resources.
Redesign `MVKDeviceMemory flushToDevice()/pullFromDevice()` to be consistent operation with each other.
Don't trigger automatic texture flush during `vkCmdCopyImage()`, as it can
cause an unexpected update from mapped memory, resulting in a race condition.

Reorganize coherent texture flushing on memory map and unmap.

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/Commands/MVKCommandEncodingPool.h
MoltenVK/MoltenVK/Commands/MVKCommandEncodingPool.mm
MoltenVK/MoltenVK/Commands/MVKMTLBufferAllocation.h
MoltenVK/MoltenVK/Commands/MVKMTLBufferAllocation.mm
MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueryPool.mm

e1ac50c0 marks temporary buffers as volatile, but it only mlocks() them for the duration
of memcpy() of initial data, leaving Metal runtime a window to snatch it before the buffer
gets encoded into the command buffer. This patch fixes it by keeping the buffers mlocked()
until they are returned to their pools.
Since mlock() and munlock() have page granularity and do not stack multiple locks, this
patch only manages locking of whole MTLBuffers. This prevents an accidental unlock of
a buffer that shares the same page with another temporary allocation used in a different
command buffer. Number of memory locks for a buffer is counted in the pool it belongs to,
necessitating some extra care for multithreaded scenarios.
Fixes rendering issues in Sekiro: Shadows Die Twice menus.
Some details to …

MVKMTLBufferAllocator: Make sure temporary buffers stay mlocked() until they're encoded.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.h
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.h
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueue.h
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm

Fixes #1385.
Per discussion in issue, this PR allows a single Metal visibility buffer to be used for all render encoders in a single `MTLCommandBuffer`.
- The first commit in this PR fixes the issue across multiple Metal render encoders in a single Vulkan command buffer.
- The second commit here extends this to an entire Vulkan submit (multiple Vulkan command buffers, one Metal command buffer).
- Third commit cleans up some syntax around tracking query locations in the visibility buffer to make it clearer how the mapping works.

Occlusion query fixes for M1

---

MoltenVK/MoltenVK/GPUObjects/MVKQueue.h
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm

Follow up to PR #1367, based on issues uncovered in #1178 and #1366.

Retain MVKQueue in MVKQueueSubmission to avoid possible race condition.

---

MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm

I've ran into an issue where the "buffer size buffer" is empty and the shader ends up indexing into this empty buffer. I believe this is caused by a mistake in order.
`encodeBindings` first calls `encodeBinding` which marks all `shader.bufferBindings` as non-dirty after binding them. 
Here is the implementation of that function:
```c++
// `encodeBinding` body
if (bindingsDirtyFlag) {
bindingsDirtyFlag = false;
for (auto& b : bindings) {
if (b.isDirty) {
mtlOperation(_cmdEncoder, b);
b.isDirty = false;
}
}
}
```
As you can see it will always set `IsDirty` to false for all bindings as long as the `bindingsDirtyFlag` is true which in this case is `shaderStage.areBufferBindingsDirty` which as far as I can tell should never be false if any of the bindings is dirty.
However after that is done …

Fix execution order of `encodeBindings` for `bufferBindings`

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

The same set of CTS tests either fails or passes on different GPUs
based on whether or not we adjust float clear colors by one ULP.
- Add `MVKFloatRounding` enum.
- Add `MVKPhysicalDeviceMetalFeatures::clearColorFloatRounding`.
- Disable ULP adjustment for clear colors on Apple Silicon.
- For consistency and to simplify bookkeepping, calculate clear color ULP adjustment from bit width of format component. This was not strictly necessary, but is clearer, and could potentially allow us to more easily adjust the ULP offset calcs per GPU if needed (eg. 1/4 ULP offsets, etc).
- Update MoltenVK version to 1.1.5.
- Update VK_MVK_MOLTENVK_SPEC_VERSION to 32.

Fix incorrect translation of clear color values on Apple Silicon.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

Sampling depth/stencil values into an RGBA value in a shader behaves inconsistency across Metal platforms, resolving to `(v, 0, 0, 1)` (as expected by Vulkan) on some platforms, but to `(v, v, v, v)` on others. This causes several hundred CTS tests to fail.
To get around this, we force an artificial swizzle for D/S textures that are sampled, if it's available on the platform.
- `MVKImageViewPlane` track Vulkan component swizzle instead of just packed swizzle, and modify swizzle when using depth or stencil sampling or reading.
- Refactor `MVKImageView::validateSwizzledMTLPixelFormat()`.
- Move `MVKImageView::validateSwizzledMTLPixelFormat()` to `MVKImageViewPlane::initSwizzledMTLPixelFormat()`, make it non-static, and use instance member content instead of passing all the data as function …

Fix swizzle of depth and stencil values into RGBA (float4) variable in shaders.

---

MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

`MVKImageViewPlane` distinguish tracking of native and shader swizzling.
Only provide packed swizzle value if shader swizzling is used.

Fix occasional crash when swizzling used but shader swizzling not enabled.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

Disable `VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT` for `VK_FORMAT_E5B9G9R9_UFLOAT_PACK32` on macOS Apple Silicon.
On Apple Silicon (iOS/tvOs/macOS M1), format `VK_FORMAT_E5B9G9R9_UFLOAT_PACK32`
is fully supported as a color attachment except that format components cannot
be individually write-enabled. All components must either be write-enabled or
write-disabled together. This is causing several hundred Vulkan CTS blending
tests to fail on M1. The least intrusive behavioural change to allow the CTS
tests to report Not Supported instead, is to disable blending for this format.
Fixes https://github.com/KhronosGroup/Vulkan-Portability/issues/28.

Disable blending for VK_FORMAT_E5B9G9R9_UFLOAT_PACK32 on macOS Apple Silicon.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

If alpha-to-coverage is enabled, we must enable the fragment shader first color output,
even without a color attachment present or in use, so that coverage can be calculated.
@cdavis5e FWIW...in working through this in CTS `dEQP-VK.pipeline.multisample.alpha_to_coverage_no_color_attachment.samples_2.alpha_opaque`, I noticed that enabling all attachments in `mslOptions.enable_frag_output_mask` did not trigger any Metal validation errors, even with no color attachments and `MTLRenderPipelineDescriptor::alphaToCoverageEnabled` disabled. I'm not sure if Apple no longer performs the validation that catalyzed the requirement for `mslOptions.enable_frag_output_mask`, or whether I just didn't encounter the appropriate use case for that validation. Just in case, I've left it intact except for the …

Support alpha-to-coverage without a color attachment.

---

MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.h
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.mm

See for reference spec description of `VkGraphicsPipelineCreateInfo`, and CTS test
`dEQP-VK.api.pipeline.pipeline_invalid_pointers_unused_structs.graphics`
Struct pointers that should be ignored under certain conditions, are 
permitted to contain non-null garbage according to the spec and tests.

Properly ignore non-null pipeline creation pointers that should be ignored.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

Move update of `MVKSwapchainImageAvailability::acquisitionID` to the acquisition
time instead of the become available again time, so other images will be preferred
if either all images are available or no images are available.
Fixes part of issue #1407.

Fix issue where swapchain images were acquired out of order under heavy load.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/Commands/MVKCmdPipeline.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

On Apple GPUs, `MVKCmdPipelineBarrier` restarts Metal renderpass when encountered inside self-dependent Vulkan subpass where the same attachment acts as both input attachment and render attachment.
Also...`MVKPhysicalDeviceMetalFeatures::memoryBarriers` and `::textureBarriers` are never enabled on Apple Silicon. Remove it as an possibility in `MVKDevice`.

Fix pipeline barriers not working inside self-dependent subpasses on Apple GPUs.

---

MoltenVK/MoltenVK/GPUObjects/MVKQueue.h
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm

For better identification in GPUCapture, particularly when tracking sync issues.
Resulting labels are also cached for performance.

Add queue and queue family indices to MTLCommandBuffer label.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/Utility/MVKEnvironment.h

This was deliberately constructed in two steps in two commits:
1) Prefer `MTLEvent` over `MTLFence`, except on NVIDIA. This still uses `MTLFence` on NVIDIA.
- Prefer MTLEvent over `MTLFence` for `VkSemaphore`, because `MTLEvent` handles sync across `MTLCommandBuffers` and `MTLCommandQueues`, except on NVIDIA GPUs, which have demonstrated trouble with `MTLEvents`, prefer `MTLFence`.
- Add `MVKDevice::VkSemaphoreStyle` enum to consolidate and simplify selection.
This provides behavior similar to existing code, except reverses the priority, but does not fix CTS tests, because `MTLFence` is not suitable for syncing across `MTLCommandBuffers` and `MTLCommandQueues`, so it really doesn't fulfil the Vulkan semaphore contract.
2) Prefer `MTLEvent` and use CPU sync emulation on NVIDIA.
- Disable …

Prefer MTLEvent for VkSemaphore, except on NVIDIA, prefer emulation.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/Commands/MVKCmdDraw.mm
MoltenVK/MoltenVK/Commands/MVKCmdPipeline.mm
MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.h
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.h
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.mm
MoltenVK/MoltenVK/Utility/MVKFoundation.h

Apologies for the random grouping here. I probably should have done these as three separate PRs. Look at the individual commits for clarity.
1. Support stencil-only partial attachment clearing:
- Rename `MVKRenderPassAttachment::shouldUseClearAttachment()` to `shouldClearAttachment()`, pass whether testing for stencil clearing, and check stencil clearing distinct from depth clearing.
- Refactor `MVKRenderSubpass::populateClearAttachments()` to work with this.
- Remove `MVKRenderPassAttachment::getAttachmentStencilLoadOp()` as obsolete.
2. Fix GPU race condition when clearing a renderpass input attachment on Apple GPUs:
- Apple GPUs do not support rendering/writing to an attachment and then reading from that attachment within a single Metal renderpass. On Apple Silicon, restart the Metal …

Several renderpass clearing and input fixes from CTS

---

Docs/Whats_New.md
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.h
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueryPool.h
MoltenVK/MoltenVK/GPUObjects/MVKQueryPool.mm

- Check that appropriate GPU counter set is supported on the device before creating GPU counter sample buffer. 
- Don't attempt to timestamp using GPU counters unless a GPU sample counter buffer has been created.
- Add `MTLFence` between Metal encoders and timestamp stage counter BLIT encoder to ensure previous work is finished before being timestamped.
Fixes issue #1433.

Improved checks for timestamp GPU counter support on older devices + Ensure timestamp sync.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

An `MVKImageView` that renders to only one layer of a multilayer `MVKImage` is not performing multilayer-rendering. Only validate multilayer-rendering when it is definitely requested in an `MVKImageView`, instead of presuming when a multilayer `MVKImage` is marked for rendering.
Fixes issue #1440.

Move multilayer-rendering validation from MVKImage to MVKImageView.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm

Dynamic pipeline state set before the pipeline is set was reading dynamic flags from previous pipeline. This is fixed here by accepting the dynamic state, but deferring the decision to use either dynamic or static state until the pipeline is encoded.
Fixes issue #1441.

Ensure dynamic pipeline state always respects pipeline dynamic flags.

---

Common/MVKLogging.h
MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm

Related to this #1445 issue.
As declared in [spec](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkApplicationInfo.html) "Vulkan 1.1 or later must not return VK_ERROR_INCOMPATIBLE_DRIVER for any value of apiVersion". So I decided to check what a Nvidia driver does in this case, it shows validation warning and sets apiVersion to latest available version. I think it would be great to have similar actions in MoltenVK.

Add unsupported VkApplicationInfo->apiVersion warning

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

Metal does not provide direct support for `BC1_RGB` formats (`VK_FORMAT_BC1_RGB_UNORM_BLOCK` & `VK_FORMAT_BC1_RGB_SRGB_BLOCK`). We have been faking it by mapping these Vulkan formats to Metal formats containing alpha (`MTLPixelFormatBC7_RGBAUnorm` & `MTLPixelFormatBC7_RGBAUnorm_sRGB`, respectively), and advertising support for BC1_RGB formats.
However, this triggers CTS failures, because the `BC1_RGBA` formats can return an alpha value of 0.0 when constructed that way, whereas the `BC1_RGB` formats always expect 1.0 (opaque) to be returned.
This change moves to indirect support for `BC1_RGB` formats. They will still be covered by `MTLPixelFormatBC7_RGBAUnorm` & `MTLPixelFormatBC7_RGBAUnorm_sRGB`, and will effectively work (except transparency), but are no longer advertised through …

Remove advertised support for BC1_RGB texel formats.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

For Vulkan `BC1_RGB` formats, swizzle alpha of substituted
Metal `BC1_RGBA` to `1.0`, to return value expected by Vulkan.
Fixes #1461 and reverses and improves PR #1460.

Restore support for BC1_RGB compressed formats.

---

MoltenVK/MoltenVK.xcodeproj/project.pbxproj
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKInstance.h
MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm
MoltenVK/MoltenVK/Utility/MVKBaseObject.h
MoltenVK/MoltenVK/Utility/MVKBaseObject.mm
MoltenVK/MoltenVK/Utility/MVKLogging.h

* Replaced ASL levels with MVKConfigLogLevel.
* Moved ```MVKLogging.h``` to ```Utility/``` directory.
* Added MVKConfigLogLevel Warning and Debug levels.

Clean up MVKLogging

---

Docs/MoltenVK_Runtime_UserGuide.md
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/Vulkan/vulkan.mm

- Support retrieving `MTLTexture` from `VkImageView` and `VkBufferView`.
- Document support for `VK_EXT_metal_objects` in `MoltenVK_Runtime_UserGuide.md`.

Update to latest version of VK_EXT_metal_objects extension

---

Common/MVKCommonEnvironment.h
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm
MoltenVK/MoltenVK/Vulkan/vk_mvk_moltenvk.mm
MoltenVK/MoltenVK/Vulkan/vulkan.mm

Move the aliasing of promoted function pointers to the function pointer lookup collection, because non-global function alias symbols in `vulkan.mm` are not available in separately compiled `MVKInstance` object file.
Add public aliased Vulkan extension functions that were promoted to 1.1 to the public symbols that are hidden when `MVK_HIDE_VULKAN_SYMBOLS` is enabled.
Add functions from the private `VK_MVK_moltenvk` extension that depend on Vulkan object handles to the public symbols that are hidden when `MVK_HIDE_VULKAN_SYMBOLS` is enabled, to discourage their use by apps that are using the Vulkan Loader and Layers, because they are not supported by the Vulkan Loader and Layers.
Update `VK_MVK_MOLTENVK_SPEC_VERSION` to version 33.

Optionally hide additional static Vulkan linkage symbols.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/Commands/MVKCmdRenderPass.mm
MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.h
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKFramebuffer.h
MoltenVK/MoltenVK/GPUObjects/MVKFramebuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.h
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.mm

Older Metal does not support rendering without subpass attachments. In this case, a dummy attachment with a dummy `MTLTexture` is created whenever the subpass begins, but was not being correctly used.
Move the creation, retaining, and releasing of the dummy MTLTexture to `MVKFramebuffer`, where the extent and layer count is known and can be reused.
Pass framebuffer to `MVKCommandEncoder::beginRenderpass()` and remember current framebuffer in `MVKCommandEncoder`.
Add `getFramebufferExtent()` and `getFramebufferLayerCount()` to `MVKCommandEncoder`.
Pass framebuffer to `MVKRenderSubpass:populateMTLRenderPassDescriptor()` and retrieve dummy `MTLTexture` from framebuffer.
Fixes issue #1487.

Fix memory leak of dummy MTLTexture in render subpasses that use no attachments.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueue.h
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm

If using GPU counters, on all Apple GPUs lock `timestampPeriod` to 1.0, since Apple GPUs use nanoseconds, and on non-Apple GPUs, dynamically adapt value of `timestampPeriod` by correlating GPU ticks with GPU ticks.
If using CPU sync, set `timestampPeriod` to OS CPU timestamp tick period.
This is a partial fix for issue #1438.

Improve accuracy of VkPhysicalDeviceLimits::timestampPeriod.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

Previously, on Apple Silicon (iOS, tvOS & macOS M1), we tried to guess `deviceID` from GPU parameters, but this is becoming harder as the types of Apple Silicon is growing, and the actual device SoC itself is less relevant that the GPU capabilities. So we now set deviceID from the combination of OS version and GPU type.
Rename `MVKDevice::getHighestMTLFeatureSet()` to `getHighestGPUCapability()`.
Fixes #1486.

On Apple Silicon, set VkPhysicalDeviceProperties::deviceID from GPU capabilities.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

Replace test for `MVK_APPLE_SILICON` with test for `MVK_MACOS` plus `Apple1` GPU.
Fixes issue #1518.

Fix use of GPU counter sets on older versions of iOS running on the simulator.

---

Common/MVKOSExtensions.h
Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm

Update MoltenVK version to 1.1.8.
Minor spelling fixes in comments.

Remove logged warning if MoltenVK does not support VkApplicationInfo::apiVersion value.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
MoltenVKShaderConverter/MoltenVKShaderConverter/SPIRVReflection.h

When flattening shader inputs for stage_in, which are to be read from a buffer that was populated as nested structs during an earlier stage, the structs will be aligned according to C++ rules, which can affect the alignment of the first member of the flattened input struct.
Add `SPIRVShaderOutput::firstStructMemberAlignment` to track the alignment requirements of the first member of a nested structure, and recursively determine the alignment of the first member of each nested output structure.
Move `sizeOfOutput()` from `MVKPipeline.mm` to `SPIRVReflection.h`, rename to `getShaderOutputSize()`, and add `getShaderOutputAlignment()` to extract member alignment.

Align flattened shader inputs to previous stage output structs.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.h
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.mm

For a combined depth-stencil format in an `MVKImageView` attachment with `VK_IMAGE_ASPECT_STENCIL_BIT`, the attachment format may have been swizzled to a stencil-only format. In this case, we want to guard against an attempt
to store the non-existent depth component.
Pass `MVKImageView` attachment to `MVKRenderPassAttachment::encodeStoreAction()` and `MVKRenderPassAttachment::populateMTLRenderPassAttachmentDescriptor()` to check attachment depth format component.
Consolidate calls to `MVKImageView::populateMTLRenderPassAttachmentDescriptor()` by calling it from within `MVKRenderPassAttachment::populateMTLRenderPassAttachmentDescriptor()`.

Don't attempt to store the depth component of a stencil-only renderpass attachment.

---

MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

Fixes #1525.
This enables support for [base vertex instance attributes for iOS in SPIR-V Cross](https://github.com/KhronosGroup/SPIRV-Cross/blob/2a7f436135bbb74c0b721e1471b07732a523ef72/spirv_msl.hpp#L336). This was included in MVKPipeline::initShaderConversionConfig as suggested by @billhollings :-)
However, I'm curious if a certain platform/metal version actually doesn't support this? Does this not include tvOS (I didn't check yet). Or is this some just weird wording from the SPIRV-Cross devs? Right now it just enables it wholly but I'm testing on a very recent Metal device.

Enable base vertex instance support in shader conversion

---

Docs/Whats_New.md
MoltenVK/MoltenVK/Commands/MVKCmdPipeline.mm
MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.mm

Ensure non-Apple GPU's enable memory barriers.
A previous commit inadvertently disabled GPU memory barriers.
Change tests for memory barriers to runtime test for Apple GPU, instead of
build-time test for Apple Silicon, to accommodate running on Rosetta2, and
refactor tests for Apple Silicon and OS version on some macOS GPU feature settings.
Fixes issue #1538.

Reinstate memory barriers on non-Apple GPUs.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.h
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm

Move release of GPU counter MTLFence from `MVKCommandEncoder` destructor to `MTLCommandBuffer` completion handler.
Fixes #1537.

Fix deletion of GPU counter MTLFence while it is being used by MTLCommandBuffer.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

When using argument buffers, Metal imposes a hard limit on the number of `MTLSamplerState` objects that can be created within the app. When not using argument buffers, no such limit is imposed. This has been verified with testing up to 1M `MTLSamplerStates`.
Fixes issue #1512.

Remove limit on VkPhysicalDeviceLimits::maxSamplerAllocationCount when not using Metal argument buffers.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

For GPUs that round float clear colors down, a half-ULP adjustment is performed on normalized formats. But this adjustment should not be performed on sRGB formats, which Vulkan requires to be treated as linear, with the value managed by the app.
Fixes issue #1504.

Avoid adjusting SRGB clear color values by half-ULP.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKBuffer.h
MoltenVK/MoltenVK/GPUObjects/MVKBuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/Utility/MVKBaseObject.h

For a resource object that can be retained by descriptors beyond its lifetime, release memory resources when the object is destroyed by the app. This includes objects of type `MVKBuffer`, `MVKBufferView`, `MVKImageView`, and `MVKSampler`.
When the app destroys an `MVKBuffer`, also detach from the `MVKDeviceMemory`, to fix a potential race condition when the app updates the descriptor on one thread while also freeing the MVKDeviceMemory on another thread.
`MVKImageView` guard against detached planes while in descriptor.
Add comment to clarify how `destroy()` is called from `release()`.
Fixes issue #1315. Long time coming. Sorry for the delay.
@cdavis5e This PR should still be compatible with your original PR #329, and this PR does not affect any CTS tests that I've been running. But let me …

Fixes to optimize resource objects retained by descriptors beyond their lifetimes.

---

MoltenVK/MoltenVK/Utility/MVKFoundation.h
MoltenVK/MoltenVK/Utility/MVKSmallVector.h

`std::iterator` is deprecated in C++17, which triggers multiple compilation warnings.
Update `MVKSmallVector::iterator` to explicitly specify iterator traits, instead of subclassing from `std::iterator`.
Qualify use of `std::remove()` in `mvkRemoveAllOccurances()`, to eliminate resolution ambiguity.

Remove use of C++17 deprecated feature: std::iterator.

---

MoltenVK/MoltenVK/Commands/MVKCommandBuffer.h
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm

When a command buffer uses ```VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT``` and ```MVK_CONFIG_PREFILL_METAL_COMMAND_BUFFERS``` is enabled, we can directly encode the ```MVKCommand```s into the MTLCommandEncoder instead of first storing it inside an array. This should reduce memory consumption in some cases where many commands are recorded.
Sorry for submitting the PR multiple times, but I merged it all into one commit because the thing with multiple users got too messy.

Added optimized support for VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT when MVK_CONFIG_PREFILL_METAL_COMMAND_BUFFERS is used

---

MoltenVK/MoltenVK/Vulkan/vk_mvk_moltenvk.mm

Calls to `vkGetMTLCommandQueueMVK()` returned garbage because `MVKQueue*` cannot be cast from `VkQueue`, use `MVKQueue::getMVKQueue()` instead.

Fix crash in vkGetMTLCommandQueueMVK()

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

A small leak occurs if no existing IOSurface is provided to vkUseIOSurfaceMVK() because CoreFoundation objects returned from functions with Create in their name must be released with CFRelease()

Fix leak of CoreFoundation objects during calls to vkUseIOSurfaceMVK()

---

Docs/MoltenVK_Runtime_UserGuide.md
Docs/Whats_New.md
MoltenVK/icd/MoltenVK_icd.json
README.md

- Update `README.md` and `MoltenVK_Runtime_UserGuide.md` to document the impact of the `VK_KHR_portability_enumeration` extension during runtime loading on macOS.
- Update MoltenVK version to 1.1.10.

MoltenVK_icd.json support VK_KHR_portability_enumeration extension.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.h
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

Fix error where previously bound push constants can override a descriptor buffer binding used by a subsequent pipeline that does not use push constants.
This error was previously introduced in 2a17f75, where a push constants binding could override the Metal buffer binding 0 of a subsequent pipeline that does not use push constants.
When pipeline binding is encoded, track which stages use push constants and only encode push constants if the pipeline and stage uses them.
(unrelated) Make use of `MVKResourcesCommandEncoderState::getPipeline()` consistent.
Fixes issue #1569.

Fix error where previously bound push constants can override a descriptor buffer binding

---

MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h

The type of the second argument to `vkSetMoltenVKConfigurationMVK` is missing a `const` qualifier in the function typedef.
Compare the following two lines:
https://github.com/KhronosGroup/MoltenVK/blob/1236d2f5350062327a2428f80dee615a2e67304f/MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h#L996
https://github.com/KhronosGroup/MoltenVK/blob/1236d2f5350062327a2428f80dee615a2e67304f/MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h#L1089-L1092
Fixes issue https://github.com/KhronosGroup/MoltenVK/issues/1577

Fix vkSetMoltenVKConfigurationMVK function typedef

---

Docs/MoltenVK_Runtime_UserGuide.md
Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/Layers/MVKExtensions.def

Add `VK_KHR_separate_depth_stencil_layouts` and enable its features.
Metal generally ignores image layouts, so nothing further needed.
Update `Whats_New.md` and `MoltenVK_Runtime_UserGuide.md` documents with recently-added extensions.
Passes almost all supported separate_layouts CTS tests, with the few remaining tests failing due to issues with unrelated capabilities.
Unrelated cleanup:
- `MVKDevice` enable extensions before features.
- `MVKDevice` reorder ivar declarations to reduce memory layout gaps, and define default values.
- Rename `VkSemaphoreStyle` to `MVKSemaphoreStyle` to remove potential conflicts with Vulkan `Vk` name space.

Add support for VK_KHR_separate_depth_stencil_layouts extension.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/Commands/MVKCmdQueries.mm
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.h
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm

Fix error on some Apple GPU's where a `vkCmdTimestampQuery()` after a renderpass was writing timestamp before renderpass activity was complete.
- `MVKCommandBuffer` tracks whether it contains a stage-based timestamp command, and `MVKCommandEncoder` updates the timestamp command fence when ending any Metal command encoder on such a `MVKCommandBuffer`.
- `MVKCommandEncoder` reorder member variables to avoid layout gaps (unrelated).
- `MVKCommandBuffer` update `_commandCount` even for single-use immediate command encoding (unrelated).
Fixes issue #1585.

Fix error on some Apple GPU's where a vkCmdTimestampQuery() after a renderpass was writing timestamp before renderpass activity was complete.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

Add workaround for zombie memory bug in Intel Iris Plus Graphics driver when repeatedly retrieving GPU counter sets.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/Commands/MVKCmdDraw.mm
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.h
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

Fix vertex buffer binding counts when establishing implicit buffers binding indexes.
This patch fixes a regression caused by 1b6b8bc9 when the implicit buffers were moved to top of Metal buffer index range.
Fix vertex buffer binding counts when binding indexes are not consecutive, or when additional synthetic buffer bindings are required to accommodate vertex attributes that are outside the vertex buffer stride values. Take into consideration that the app may bind more vertex attribute buffers than a pipeline may consume, and don't allow these to overwrite any implicit buffers sent to the shader.
`MVKResourcesCommandEncoderState::encodeBinding()` clear binding dirty flag before calling lambda function to allow function operation to possibly override and leave binding marked dirty.
Set …

Fix vertex buffer binding counts when establishing implicit buffers binding indexes.

---

MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm

Continuation of #1358. Thanks to @kleinerm for the initial work.
The aforementioned PR was already over a year old and was not merged because of a flaw where the CALayer of the swap chain was not the top layer of a window, making the code default to `[NSScreen mainScreen]`. This fixes that issue by combining a suggestion by @cdavis5e in which we take the absolute super layer of the swap chain's layer so that we actually have the top layer of the window. This should now cover all edge cases.

Implement vkGetRefreshCycleDurationGOOGLE() for macOS

---

MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.h
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/Commands/MVKMTLResourceBindings.h

Here's a couple of patches that in my tests can reduce Metal command buffer encoding time pretty significantly in some cases, by avoiding encoding things redundantly.
There's another one (not included) to allocate MVKCommands into a linear buffer, which speeds things up a little and reduces freeing them to a trivial "count = 0;" (which otherwise takes some time of the order of 1ms from what I've seen), but there's the complication of a handful commands which actually do things in their destructor, which I haven't resolved yet.

Reducing redundant state changes

---

MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm

Creating an empty MVKDescriptorSet will read this member and tip off undefined behavior sanitizer. It shouldn't actually cause any bugs, but with UB you never know.

MVKDescriptorPool: Move _hasPooledDescriptors to the top to ensure it's initialized first.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

- Revert to avoid `MTLLanguageVersion1_0` on macOS (Xcode 14.0 Beta 2 had erroneously indicated support).
Fixes issue #1634.

Support Xcode 14.0 Beta 3.

---

MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

- Derive `MVKDescriptorPool::_hasPooledDescriptors` within constructor, instead of being passed in from outside, and set before any other construction.
Fixes issue #1640, to cleanup obsolete code resulting from PR #1639.

Clean up MVKDescriptorPool constructor.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

- Add `0x8a51` and `0x8a52` to list of device IDs requiring workaround.
Fixes issue #1642.

Work around MTLCounterSet crash on additional Intel Iris Plus Graphics drivers

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKSync.h
MoltenVK/MoltenVK/GPUObjects/MVKSync.mm

- `vkCreateSemaphore()` create binary semaphore, unless timeline explicitly requested. Previously, timeline semaphore was always created when `exportObjectType == VK_EXPORT_METAL_OBJECT_TYPE_METAL_SHARED_EVENT_BIT_EXT`.
- `vkCreateSemaphore()` record error when `MTLSharedEvent` imported or marked for export, and MoltenVK configured for VkSemaphore using `MTLFence` or CPU emulation.
- `MVKTimelineSemaphore` elide unused constructor arguments.
Fixes issue #1631.

VK_EXT_metal_objects fix issue where timeline event incorrectly created.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

- Add `MVKPhysicalDeviceMetalFeatures::shaderBarycentricCoordinates`, enable it based on `[MTLDevice supportsShaderBarycentricCoordinates]`, and subsequently enable support for `VK_KHR_fragment_shader_barycentric` and `VK_NV_fragment_shader_barycentric` extensions, based on it.
- Update `VK_MVK_MOLTENVK_SPEC_VERSION` to version `35`.

Check MTLDevice for barycentric coordinate support.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

`VK_EXT_swapchain_colorspace` is only required to be enabled for implementations to **use** the advanced color spaces. However, implementations are allowed to return any enum value it wants, and applications simply have to ignore these 'unknown' enumerations.

Fix: No need to check if EXT_swapchain_color_space was enabled

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKQueryPool.mm

When checking query wait completion, all queries were previously checked for `Available` status, and blocked until all became `Available`. However, only queries that were encoded to be written should be checked. It is okay for queries that are not encoded to be written to remain in `Initial` state, and not block the wait.

Fix query pool wait block when query is not encoded to be written to.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.mm

- Plus inline `MVKDescriptorSetLayoutBinding::getImmutableSampler()` for consistency with `usesImmutableSamplers()`.

Ignore sampler update in descriptor set bindings that use immutable samplers.

---

MoltenVK/MoltenVK/OS/MVKGPUCapture.mm

Apply Apple fix to MTLCaptureScope retention bug to macOS 12.5.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/Commands/MVKCmdPipeline.h
MoltenVK/MoltenVK/Commands/MVKCmdPipeline.mm
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/Vulkan/vulkan.mm

- Fix `vkUpdateDescriptorSetWithTemplate()` for inline block descriptors.
- Rename entities for `VK_KHR_descriptor_update_template` extension since it's promoted to Vulkan 1.1.
First commit contains functional changes. Second commit contains the renaming noise.

Fix vkUpdateDescriptorSetWithTemplate() for inline block descriptors.

---

Demos/Cube/macOS/DemoViewController.m
Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.h
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm

- `DemoView` implements `NSViewLayerContentScaleDelegate` protocol to update `[CAMetalLayer contentsScale]` property when moved between screens.
- Log `contentsScale` value during swapchain creation.
- Remove a few unnecessary inline declarations.
Fixes issue #1591.

Update macOS Cube demo to demonstrate optimizing swapchain across multiple screens.

---

Docs/MoltenVK_Runtime_UserGuide.md
Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm
MoltenVK/MoltenVK/OS/CAMetalLayer+MoltenVK.h
MoltenVK/MoltenVK/OS/CAMetalLayer+MoltenVK.m

- Add `[CAMetalLayer screenMVK]` extension method to retrieve screen.
- If the layer has a `delegate` view, use it to locate the screen, otherwise revert to iterating across windows, looking for the `CAMetalLayer`, to identify the window the layer is in, from which to retrieve the screen.
- Fix the iteration of the layer hierarchy, to accommodate that Apple may add superlayers to the `CAMetalLayer` under the covers.
- Update `MoltenVK_Runtime_UserGuide.md` to encourage the app to ensure the view is the delegate of the CAMetalLayer, to more efficiently access the screen.
Fixes issue #1617.

Fix retrieval of accurate refresh duration across multiple display screens.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKInstance.h
MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm

Report appropriate values of `VkDebugUtilsMessageTypeFlagsEXT` for debug util messages generated within MoltenVK.
Fixes issue #1622.

Report appropriate values of VkDebugUtilsMessageTypeFlagsEXT

---

MoltenVK/MoltenVK.xcodeproj/project.pbxproj
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKDeviceFeatureStructs.def

- Add `MVKDeviceFeatureStructs.def` file to describe each device feature struct, and define, populate, and manage `MVKDevice` device feature tracking iVars using the list in this file.
- Reorder switch cases in `MVKPhysicalDevice::getFeatures()` to match the list in `MVKDeviceFeatureStructs.def`.
- Where possible, remove extension suffixes from device feature structs and associated `VkStructureType` values.
- Remove const qualifier from device feature enabling structs.
This supports automatic enablement tracking for all device features, ensures such enablement tracking will evolve as new device features are added, and better sets up enabling device features in Vulkan 1.2 and beyond.

MVKDevice consolidate enabling device feature tracking.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

In preparation for Vulkan 1.2, support the following device feature and property structures, and use them to populate the corresponding device feature and property values originally supplied by Vulkan extensions, to ensure a single source of truth for these values:
- `VkPhysicalDeviceVulkan11Features`
- `VkPhysicalDeviceVulkan11Properties`
- `VkPhysicalDeviceVulkan12Features`
- `VkPhysicalDeviceVulkan12Properties`
Disable `VkPhysicalDeviceVulkan12Features::drawIndirectCount` and `VkPhysicalDeviceVulkan12Features::samplerFilterMinmax`, to indicate that Vulkan 1.2 support will not include extensions `VK_KHR_draw_indirect_count` and `VK_EXT_sampler_filter_minmax`, respectively.
Support enabling device features during `VkDevice` creation using `VkPhysicalDeviceVulkan11Features` and …

Support Vulkan 1.2 device feature and property structs.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm
MoltenVK/MoltenVK/Utility/MVKBitArray.h

- `MVKDescriptorPool::reset()` don't waste time freeing descriptor sets that were never allocated.
- If descriptor set could not be allocated, set availability bit (unrelated).
- `MVKBitArray` add `_lowestNeverClearedBitIndex` to track the lowest bit index that has not been cleared since last reset.
- `MVKBitArray` rename `_minUnclearedSectionIndex` to `_clearedSectionCount` for clarity.
- `MVKBitArray` use `_clearedSectionCount` and `_lowestNeverClearedBitIndex` to optimize operation of setting or clearing all bits.
- `MVKBitArray::setBit()` ensure we don't try to change a bit that is out of range.
- `MVKBitArray::resize()` no-op if size doesn't actually change.
- `MVKQueue` don't include object pointer in error log, so CTS log results are consistent across multiple CTS runs (unrelated). …

Improve performance of vkResetDescriptorPool().

---

Docs/Whats_New.md
MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.h
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.h
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/Commands/MVKMTLResourceBindings.h

This fixes an earlier regression, where when only the offset changes in a buffer descriptor, the binding is not marked dirty if the same Metal binding index is used by a push constant in between descriptor bindings.
- Add `MVKResourcesCommandEncoderState::markMetalBufferIndexDirty()` to find and mark dirty a descriptor buffer binding that uses an index
- `MVKPushConstantsCommandEncoderState::encodeImpl()` mark descriptor buffer binding override.
- `MVKCommandEncoder::setXXXBytes()` calls optionally mark overridden descriptor buffer bindings as dirty, allowing this functionality to be generalized.
- `MVKMTLBufferBinding::update()` inline buffers never update just offset because inline contents may have changed.
- `MVKCmdClearAttachments` mark specific overridden buffer bindings dirty …

Fix occasional missing Metal buffer binding when only offset changes.

---

MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

We cannot use Cereal due to legal reasons. However, we are fine with not having the pipeline cache serialization feature.

Add MVK_USE_CEREAL build option to avoid use of Cereal library.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKSurface.h
MoltenVK/MoltenVK/GPUObjects/MVKSurface.mm
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.h
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm

When presenting drawables in the future, the `MVKPresentableSwapchainImage`and `MVKSwapchain` were both being retained by the drawable-presented callback, so that the presentation timing info can be recorded on the swapchain. Unfortunately, in the case where the presentation timing is set far enough into the future (I'm looking at you CTS), the swapchain, and even the `CAMetalLayer's` view may be destroyed, causing occasional bad access crashes.
- `MVKSwapchainImage` don't retain() the swapchain, and move clearing the swapchain from the destructor to destroy(), so the `MVKSwapchain` is not necessarily retained by the `MVKSwapchainImage`, for a drawable being presented in the future.
- `MVKSwapchainImage` add a lock around clearing swapchain and accessing it from callbacks.
- Add lockable …

Fix retention of MVKSwapchain for future drawable presentations.

---

MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm

NSScreen's `localizedName` property is only available on macOS 10.15+, so check before use.

Fix crash in vkCreateSwapchainKHR() on macOS 10.14 and earlier

---

Docs/MoltenVK_Runtime_UserGuide.md
Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKShaderModule.mm
MoltenVK/MoltenVK/Layers/MVKExtensions.def
Scripts/runcts

- Add support for `VK_KHR_shader_float_controls` extension.
- Enable `shaderSignedZeroInfNanPreserveFloat16` and `shaderSignedZeroInfNanPreserveFloat32`. Other float control properties are not settable in Metal.
- `MVKShaderModule` debug log whether compiling with fast math enabled.
- Update `MoltenVK_Runtime_UserGuide.md` and `Whats_New.md` documents.
- `runcts` script enable `MVK_CONFIG_FAST_MATH_ENABLED` by default.

Add support for the VK_KHR_shader_float_controls.

---

Docs/MoltenVK_Runtime_UserGuide.md
Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/Utility/MVKEnvironment.cpp
MoltenVK/MoltenVK/Utility/MVKEnvironment.h
MoltenVKShaderConverter/MoltenVKShaderConverter.xcodeproj/xcshareddata/xcschemes/MoltenVKShaderConverter.xcscheme
MoltenVKShaderConverter/MoltenVKShaderConverterTool/MoltenVKShaderConverterTool.cpp
MoltenVKShaderConverter/MoltenVKShaderConverterTool/MoltenVKShaderConverterTool.h
Scripts/runcts

- Change `MVKConfiguration::useMetalArgumentBuffers` to enum instead of boolean and default to enabling Metal argument buffers for VK_EXT_descriptor_indexing.
- **_However, leave Metal argument buffers disabled by default until they are improved._**
- Enable `VkPhysicalDeviceVulkan12Features::descriptorIndexing`.
- Add `MVKPhysicalDeviceVulkan12FeaturesNoExt` to track and enable Vulkan 1.2 features not part of any prior extensions absorbed by Vulkan 1.2.
- Update `VK_MVK_MOLTENVK_SPEC_VERSION` to version `36`.
- `MVKDeviceTrackingMixin` remove unnecessary inline declarations.
- `MoltenShaderConveter` tool support Metal Argument Buffers and MSL 3.0.
Fixes #1689.

Support automatically enable Metal argument buffers when VK_EXT_descriptor_indexing extension is enabled.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/Utility/MVKEnvironment.cpp
MoltenVK/MoltenVK/Utility/MVKEnvironment.h
Scripts/runcts

- Support option to use `MTLEvents` for Vulkan semaphores on NVIDIA and Rosetta2.
- Add public `MVKVkSemaphoreSupportStyle` enumeration.
- `MVKConfiguration` rename recently renamed `semaphoreUseSingleQueue` back to `semaphoreUseMTLFence` for backwards compatibility.
- `MVKConfiguration` replace deprecated legacy booleans `semaphoreUseMTLEvent`, and `semaphoreUseMTLFence` with enumerated `semaphoreSupportStyle`.
Fixes issue #1695.
@tellowkrinkle Builds on #1693. Please review.

Vulkan semaphore functional improvements.

---

Makefile

Makefile currently special-case MVK_HIDE_VULKAN_SYMBOLS as the only variable that can be customised on the command line. There are many others that are useful though, such as MVK_LOG_*. This commit makes the Makefile more generic and allows to forward to xcode whatever variable was declared on the command line.

Makefile: forward to xcode any variable declared on the command line

---

.github/workflows/CI.yml
Docs/MoltenVK_Runtime_UserGuide.md
Docs/Whats_New.md
MoltenVK/MoltenVK/Layers/MVKExtensions.def
MoltenVKShaderConverter/MoltenVKShaderConverter.xcodeproj/xcshareddata/xcschemes/MoltenVKShaderConverter.xcscheme
MoltenVKShaderConverter/MoltenVKShaderConverter/GLSLToSPIRVConverter.cpp
MoltenVKShaderConverter/MoltenVKShaderConverter/SPIRVSupport.cpp

- Advertise support for extension `VK_KHR_spirv_1_4`.
- `MoltenVKShaderConverter` automatically map bindings when converting GLSL.
- `MoltenVKShaderConverter` improvements to diagnostic logging.
- Update `Whats_New.md` document.
Support for _SPIR-V 1.4_ features added in [recent updates](https://github.com/KhronosGroup/SPIRV-Cross/issues/2004) to `SPRIV-Cross`.

Advertise support for extension VK_KHR_spirv_1_4.

---

Docs/MoltenVK_Runtime_UserGuide.md
Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm
MoltenVK/MoltenVK/Utility/MVKEnvironment.h
MoltenVK/MoltenVK/Vulkan/vulkan.mm
README.md

- Set `MVK_VULKAN_API_VERSION` from `VK_API_VERSION_1_2`.
- Update MoltenVK version to `1.2.0`.
- Remove several previously overlooked extension suffixes in use of promoted Vulkan struct and enum values.
- Update documentation.
Implements #1567.
Well...this should have everything we need, but I have a nagging feeling there might be some kind of _unknown-unknown_ that's been missed. Please identify anything that might have been overlooked in the transition to 1.2.

Add support for Vulkan 1.2.

---

MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/Utility/MVKEnvironment.cpp
MoltenVK/MoltenVK/Utility/MVKEnvironment.h

- If `MTLEvents` are unusable, fallback to single queue.
- Adjust values of `MVKVkSemaphoreSupportStyle` enumeration.
- For legacy compatibility, if legacy `semaphoreUseMTLEvent` and `semaphoreUseMTLFence` are both disabled, use CPU callback emulation.
- Update and expand related documentation in `vk_mvk_moltenvk.h`.
This PR is an expansion of, and replaces, PR #1735, based on a suggestion from @marzent in that PR.
This PR makes `MVK_CONFIG_VK_SEMAPHORE_SUPPORT_STYLE_SINGLE_QUEUE` the default in all cases where `MTLEvents` are unusable, provides legacy consistency with `semaphoreUseMTLEvent` and `semaphoreUseMTLFence`, and clarifies documentation.
@marzent @Gcenx Please review relative to #1735 & regression fix request in issue #1736.

Vulkan semaphore fallback to using single queue if `MTLEvents` unusable.

---

MoltenVK/icd/MoltenVK_icd.json

Minor change. The icd json file still listed MoltenVK as supporting version 1.1 of the API. This changes updates that to 1.2.

fix for wrong version number in icd json

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm

Update MoltenVK version to 1.2.1.
Fixes issue #1752.

Fix crash on descriptor update with out-of-bounds descriptor count data.

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.h
MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/Layers/MVKExtensions.def
MoltenVK/MoltenVK/Vulkan/vulkan.mm

Closes #1734.
I've ran the 12809 `dEQP-VK.api.copy_and_blit.copy_commands2.*` CTS tests (note that I have never used the CTS before so not sure if these are the correct tests and if there are more) with these results:
```
Passed:        3676/12779 (28.8%)
Failed:        0/12779 (0.0%)
Not supported: 9103/12779 (71.2%)
Warnings:      0/12779 (0.0%)
Waived:        0/12779 (0.0%)
```
With this PR all the relevant commands now use the 2 versions of the structs internally where possible, I've also added some missing `MVKSmallVector::reserve` calls, and we now properly move structs into the vectors where possible.
@billhollings I'd like to request a review from you but can't for some reason.

Add: KHR_copy_commands2

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

Do this even if `OPTIMAL` tiling were requested. Vulkan mandates support for image atomics on `OPTIMAL`-tiled `R32_UINT` and `R32_SINT` images. In a way, this is "optimal"; image atomics won't work without this.
Advertise support for atomics on `OPTIMAL` tiled images now.
Fixes at least two CTS tests under
`dEQP-VK.compute.basic.image_atomic_op_*`.
Closes #1766.

MVKImage: Always use a texel buffer for atomic storage images.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.h

- `MVKVkFormatDesc::chromaSubsamplingPlaneCount` must be `> 1` to be considered supported.
- Fixes mistaken `VK_ERROR_FORMAT_NOT_SUPPORTED ` errors for some `YCBCR` formats found in issue #1760.
- Has the same `YCBCR` CTS test results as before this patch.
@Lichtso Please also review.

Fix mistaken YCBCR format support indication.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.h
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/Commands/MVKMTLResourceBindings.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

Push constants and attachment clearing can temporarily override Metal buffer bindings for descriptor sets and vertex attributes. Mark the overridden descriptor buffer bindings and ensure they are reinstated when the pipeline is updated.
- Add `MVKMTLBufferBinding::isOverridden` to track if buffer binding is temporarily overridden.
- Rename `MVKResourcesCommandEncoderState::markIndexDirty()` to `markBufferIndexOverridden()` to mark buffer bindings as overridden.
- Rename `MVKGraphicsResourcesCommandEncoderState::markBufferIndexDirty()` to `markBufferIndexOverridden()`.
- Rename `MVKComputeResourcesCommandEncoderState::markBufferIndexDirty()` to `markBufferIndexOverridden()`.
- Add `MVKResourcesCommandEncoderState::markOverriddenBufferIndexesDirty()` to mark overridden buffer bindings as …

Fix Metal buffer index binding overrides for push constants and attachment clearing.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/Utility/MVKEnvironment.cpp
MoltenVK/MoltenVK/Utility/MVKEnvironment.h

The introduction of `shaderSignedZeroInfNanPreserveFloat32` was causing Metal fast math to be aggressively disabled by the use of `SignedZeroInfNanPreserve` in shaders in some apps, causing a regression in shader performance in those apps.
- Change `MVKConfiguration::fastMathEnabled` from `bool` to enumeration to distinguish between always using fast math or allowing shaders to selectively disable it.
- Default value to fast math always.
Fixes issue #1746.

Fix app performance regression triggered by the previous introduction of VK_KHR_shader_float_controls.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/Commands/MVKMTLResourceBindings.h

`MVKMTLBufferBinding` don't allow `justOffset` if binding was overridden.

Fix crash when buffer binding updates only offset while it is overridden.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm

Metal uses `MTLRenderPassDescriptor` properties `renderTargetWidth`, `renderTargetHeight`, and `renderTargetArrayLength` to preallocate tile memory storage on machines using tiled rendering. This memory preallocation is not necessary if we are not rendering to attachments, and some apps actively define extremely oversized framebuffers when they know they are not rendering to actual attachments, making this internal tile memory allocation even more wasteful, occasionally to the point of triggering OOM crashes.
Update MoltenVK version to 1.2.2.
- Fixes issue #1650.

Fix excessive Metal tile memory preallocation when rendering without attachments.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm

The now-reverted commit had caused fragment shader not to run at all when no render attachment was available.
Reverts PR #1797.

Revert PR #1797.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

- Fix Metal validation error caused by `CAMetalDrawable` released before `MTLCommandBuffer` is finished using it.
- When presenting, `MVKPresentableSwapchainImage` retains in-flight `CAMetalDrawable` until `MTLCommandBuffer` completion.
- Fix memory leak of `MVKFences` and `MVKSemaphores` when a swapchain image is acquired more than it is presented.
- Force `MVKPresentableSwapchainImage` to untrack any tracked fences or semaphores when it is destroyed.
- Update MoltenVK version to 1.2.2.

Fix small memory issues with MVKPresentableSwapchainImage.

---

Common/MVKCommonEnvironment.h
Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm
MoltenVK/MoltenVK/Layers/MVKExtensions.mm
MoltenVK/MoltenVK/Layers/MVKLayers.mm
MoltenVK/MoltenVK/Utility/MVKFoundation.h
MoltenVK/MoltenVK/Vulkan/vulkan.mm

- Ensure Vulkan public symbols are not stripped from the library when statically linked to an app that calls all Vulkan functions dynamically.
- Per Vulkan 1.2 spec, support calling `vkGetInstanceProcAddr()` with a null instance, when `vkGetInstanceProcAddr` itself is the function name.
- Replace uses of `strcmp()` with `mvkStringsAreEqual()` to protect against null pointers, and provide a direct bool output (unrelated cleanup).
Fixes issue #1809.
Possible fix for issue #1808.

Fix linking issues with dynamic Vulkan functions.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

- Update `maxClipDistances` and `maxCombinedClipAndCullDistances` to more accurate values.
- Update `maxDrawIndexedIndexValue` to acknowledge automatic primitive restart.
Fixes #1822.

Set more accurate values for some VkPhysicalDeviceLimits members.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

- Fix issue where extension `VK_KHR_fragment_shader_barycentric` was sometimes incorrectly disabled due to a Metal driver bug.
- Update MoltenVK version to 1.2.3.
Fixes issue #1831.

Fix issue where VK_KHR_fragment_shader_barycentric incorrectly disabled

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/Commands/MVKCmdRenderPass.mm
MoltenVK/MoltenVK/Commands/MVKCmdTransfer.h
MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.h
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.h
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueryPool.mm
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.h
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.mm
MoltenVK/MoltenVK/Utility/MVKEnvironment.h
MoltenVK/MoltenVK/Utility/MVKFoundation.h

This PR fixes some issues with dynamic rendering and occlusion queries, and modifies the some Metal debug labelling to make it easier to distinguish attachment clearing activities within a GPU capture.
- Fix crash when `VkCommandBufferInheritanceInfo::renderPass` is `VK_NULL_HANDLE`.
- Do not clear attachments when dynamic rendering is resumed.
- Allow ending dynamic rendering to trigger next multiview pass if needed.
- Move deciding to begin next multiview pass to `MVKCommandEncoder`.
- Fix premature caching of occlusion query results during tessellation rendering. Tessellation ends Metal renderpass for compute control and eval stages. Wait until end of Metal renderpass after rasterization stage.
- `vkCmdCopyQueryPoolResults()`: Fix loss of queries when query count is not a multiple of …

Fixes to dynamic rendering and occlusion queries.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKQueue.h
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm

Use a different visibility buffer for each MTLCommandBuffer in a queue submit.

---

Common/MVKCommonEnvironment.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

Fixes #1814.
MoltenVK currently assumes that all the formats the M1 brings to the table (because it's based from the Apple A family which supported other formats than the macOS GPUs) are only available when building for arm64. However, the SDK is currently built as x86_64 and some games might ship with x86_64 binaries of MoltenVK. The aforementioned formats are actually still available on that architecture, and this PR changes the code to allow all the new formats on any architecture.
Also, side question, but is there any reason MoltenVK does not use things like std::array, as MoltenVK is set to use C++17 anyway? Is this because of debug performance?

Allow M1 formats on non-arm64 driver builds

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/Utility/MVKEnvironment.h

This is related to issue #1838.
Since there's a fix being worked, and it could take some time, and probably not a priority for now, it'd be nice to give at least the possibility to disable the workaround via an ENV variable like it's done with other features in the codebase.
I was thinking something like MVK_CONFIG_ENABLE_EXPLICIT_LOD_WORKAROUND=0 to disable it and have it set to 1 by default so that it doesn't change anything compared to the current state of the codebase.

Allow to disable Explicit LOD Workaround for Apple silicon.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKSync.h

- Fix memory leak when waiting on timeline semaphores.
- For correctness, set `VkPhysicalDeviceLimits::lineWidthGranularity` to `1`.
- Update MoltenVK to version 1.2.4.
- Update `Whats_New.md` document with recent changes.
Fixes issue  #1860.

Several simple maintenance fixes.

---

Common/MVKCommonEnvironment.h
Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

- Add `MVK_XCODE_14_3` macro to compile for iOS/tvOS 16.4 and above.
- Add support for BC compression on iOS/tvOS 16.4 and above were supported.
- Consolidate `MVKPixelFormats::modifyMTLFormatCapabilities(mtlDev)` and centralize querying MTLDevice format methods for all platforms.
- Replace references to macOS 10.16 with 11.0, and standardize use of whitespace in `MVKPixelFormats::modifyMTLFormatCapabilities()` (unrelated).
For review purposes, this is structured in two commits. The first contains the added BC support. The second just contains syntactic noise redefinitions.
Implements issue #1863.

Support BC compression on iOS/tvOS, where available.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.h
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKDeviceMemory.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
MoltenVK/MoltenVK/Utility/MVKFoundation.h
MoltenVKShaderConverter/MoltenVKShaderConverter/SPIRVToMSLConverter.cpp
MoltenVKShaderConverter/MoltenVKShaderConverter/SPIRVToMSLConverter.h

- `MVKDevice` track `VkBuffers` marked with `VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT`.
- Add `SPIRVToMSLConversionResultInfo::usesPhysicalStorageBufferAddressesCapability` to detect and track shaders that use `PhysicalStorageBufferAddresses` capability, and track such shader stages within pipeline.
- `MVKResourcesCommandEncoderState` encode usage of `VkBuffers` marked with `VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT` when pipeline uses `PhysicalStorageBufferAddresses` capability.
- Rename `MVKResourcesCommandEncoderState::encodeArgumentBufferResourceUsage()` to `encodeResourceUsage()`.
- `MVKDevice` move some functions to public scope and remove friend classes.
- `MVKDeviceMemory` ensure `_vkMemAllocFlags` is always initialized (unrelated).
- Rename `MVKFoundation` template method …

Ensure shaders using PhysicalStorageBufferAddresses encode the associated MTLBuffer.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/Utility/MVKCodec.mm

Disable pipeline cache compression prior to macOS 10.15 and iOS/tvOS 13.0

---

Docs/Whats_New.md
MoltenVK/MoltenVK/Commands/MVKCmdRenderPass.h
MoltenVK/MoltenVK/Commands/MVKCmdRenderPass.mm
MoltenVK/MoltenVK/Commands/MVKCmdTransfer.h
MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.h
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.h
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKFramebuffer.h
MoltenVK/MoltenVK/GPUObjects/MVKFramebuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.h
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.mm
MoltenVK/MoltenVK/Layers/MVKExtensions.def

With the introduction of `VK_KHR_dynamic_rendering`, Vulkan permitted separate depth and stencil attachments, which Metal always supported, although in Vulkan, the two attachments are, for the time being, restricted to the same pixel format and image view.
This PR implements depth and stencil attachments as separate attachments, and fixes attachment Metal validation errors in the process. This PR is more than strictly necessary to fix the reported Metal validation issues, but better aligns MoltenVK with Metal depth and stencil handling, and is positioned for a potential future enhancement to Vulkan, where separate depth and stencil formats might be supported in the future.
- `MVKRenderSubpass` add separate `getDepthFormat()` & `getStencilFormat()`, and `isDepthAttachmentUsed()` & …

Support separate depth and stencil attachments during dynamic rendering

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/mvk_config.h
MoltenVK/MoltenVK/API/mvk_deprecated_api.h
MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm
MoltenVK/MoltenVK/Layers/MVKExtensions.mm
MoltenVK/MoltenVK/Vulkan/mvk_api.mm

Remove `vkGetMoltenVKConfiguration2MVK()` and `vkSetMoltenVKConfiguration2MVK()`.
Also undeprecate the original `vkGet/SetMoltenVKConfigurationMVK()`.
In expectation of the upcoming `VK_EXT_layer_settings extension`, it is felt that adding these additional functions at this time would be confusing to app devs.

Remove vkGetMoltenVKConfiguration2MVK() and vkSetMoltenVKConfiguration2MVK()

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.h
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm

- `MVKPresentableSwapchainImage::presentCAMetalDrawable()` and `addPresentedHandler()` pass `MVKImagePresentInfo` by value instead of reference, to avoid callbacks colliding with tracked `MVKImagePresentInfos` being cleared when `MVKQueuePresentSurfaceSubmission` is destroyed after it is run.
Fixes race condition part of issue #1882.

Fix race condition when updating values in VkPastPresentationTimingGOOGLE.

---

.github/workflows/CI.yml
Docs/Whats_New.md
README.md

- Build one universal build, instead of per-platform.
- Upload this single build artifact to GitHub.
- Upgrade to v3 of action dependencies to remove _Node.js_ deprecation warnings.
- Use macOS 13 and Xcode 14.3.
- `README.md` document access to binary artifacts.

GitHub CI improvements.

---

.github/workflows/CI.yml

Implements a GitHub Actions workflow for creating releases when a tag is pushed. The workflow will upload any files uploaded to the artifact "MoltenVK" by the CI build as release assets.
Example workflow execution: https://github.com/Steveice10/MoltenVK/actions/runs/4932936369
Example release created by this workflow: https://github.com/Steveice10/MoltenVK/releases/tag/v1.2.4
Note that the title and description will still need to be manually customized after the release is created. By default it creates the release with the tag as the release name and the commit description as the release details.

Add GitHub Actions workflow for automatically creating releases.

---

.github/workflows/CI.yml

Simple update to the release workflow for the build CI updates. Since we have ```MoltenVK-all```, ```MoltenVK-macos```, and ```MoltenVK-ios``` artifacts in the build workflow, we can capture all of these and upload their artifacts with the glob pattern ```MoltenVK*/*```.
Resulting release: https://github.com/Steveice10/MoltenVK/releases/tag/v1.2.4

Update release action artifact glob.

---

.github/workflows/CI.yml

Adds some parameters to make the release workflow more lenient in how it can be executed, along with some comments to explain each parameter's purpose.
Brief explanation:
* allowUpdates: This allows the release workflow to update an existing release for the tag. This allows you to cut a tag by creating a release in the GitHub UI, as they will no longer conflict.
* removeArtifacts: When a release is updated, delete any existing assets first. This way if a release workflow is re-run you won't end up with a large build-up of release assets from multiple runs.
* omit(Name/Body)DuringUpdate: When the release already exists, don't set the name or body. This allows filling in the name and body info when creating the release in the GitHub UI, without the release workflow then overwriting it all. …

Make the GitHub Actions release workflow more lenient.

---

MoltenVK/MoltenVK/Commands/MVKCmdPipeline.mm
MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.mm
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

Prevents calls to `vkCmdPushDescriptorSetKHR` with layouts that specify `VK_SHADER_STAGE_ALL` from applying to things they shouldn't (e.g. having `VK_PIPELINE_BIND_POINT_COMPUTE` binds trash the graphics bindings)

Respect the bind point supplied to vkCmdBindDescriptorSets / vkCmdPushDescriptorSets

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

Fix depth clamp and texture swizzle feature discovery on simulator builds
Both of these features are not supported by the iPhone simulator and leads to crashes when used

Fix simulator feature discovery

---

Common/MVKStrings.h
Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/Utility/MVKBaseObject.mm
MoltenVK/MoltenVK/Utility/MVKFoundation.h

- Make `MVKDevice::enableFeatures()` functions into templates to pass struct type.
- Add `mvkGetAddressOfFirstMember()` to retrieve the address of the first member of a struct, taking into consideration whether the struct has a Vulkan `pNext` member.
- Add `mvk::getTypeName()` and `mvk::getOrdinalSuffix()` string functions.
Fixes issue #1871.

Identify each unsupported device feature flag that the app attempts to enable.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm

If Metal reports zero `presentedTime`, and desired presentation time has not been set by app, use the current time.
Fixes second part of #1882.

Ensure swapchain image presented time is always populated when requested.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

`MTLDevice registryID` is not constant across OS reboots, which is not conformant with `deviceUUID` requirements.
Replace with combination of `MTLDevice` `location`, `locationNumber`, `peerGroupID`, and `peerIndex`, which should define uniqueness, and **_should_** be constant across OS reboots.
I've included device peer group because `locationNumber` is [not unique](https://developer.apple.com/documentation/metal/mtldevice/3114006-locationnumber?language=objc) in the case of slots and external ports that support multiple GPUs. However, I am not 100% certain that the peer group info is constant across a reboot, although it will be for cases where a peer group is not defined.
Fixes issue #1880.

Populate deviceUUID from MTLDevice location and peer group info.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.h
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm

Should fix issues #1870 & #1811.

Accumulate render stages when a resource is used by multiple descriptor bindings.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

Advertise `VK_KHR_depth_stencil_resolve` extension on early iOS devices, since `VK_RESOLVE_MODE_SAMPLE_ZERO_BIT` is supported on all devices, even if other resolve modes are not, and makes it consistent with Vulkan 1.2 mandatory support for `VK_RESOLVE_MODE_SAMPLE_ZERO_BIT`.
Fixes #1875.

Advertise VK_KHR_depth_stencil_resolve extension on all devices.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/mvk_config.h
MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.h
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueryPool.mm

The same compute encoder is used across dispatches and other commands, which may override compute state, and end up breaking subsequent dispatches.
- Mark compute encoding state dirty when following commands, which use Metal compute encoders, are issued:
- `vkCmdCopyBuffer()`
- `vkCmdClearColorImage()`
- `vkCmdClearDepthStencilImage()`
- `vkCmdFillBuffer()`
- `vkCmdCopyQueryPoolResults()`
- `MVKCommandEncoder` move marking compute state dirty from `endCurrentMetalEncoding()` to `getMTLComputeEncoder()`.
- For efficiency, don't prematurely force end of query copy compute encoder used on renderpass end, in case compute dispatches follow.
- Update MoltenVK to 1.2.5 (unrelated).
Fixes issue #1874

Ensure compute encoding state is marked dirty for non-dispatch commands.

---

Demos/Cube/macOS/DemoViewController.m
Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm

- Only log performance stats on FPS logging if logging style is explicitly set to `MVK_CONFIG_ACTIVITY_PERFORMANCE_LOGGING_STYLE_FRAME_COUNT` (unrelated).

Add support for VK_PRESENT_MODE_IMMEDIATE_KHR to macOS Cube demo.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm

- `[MTLDrawable presentAtTime:]` syncs to display vsync. To support `VK_PRESENT_MODE_IMMEDIATE_KHR` while using `VkPresentTimeGOOGLE::presentID`, only call `presentAtTime:` if `VkPresentTimeGOOGLE::desiredPresentTime` has been explicitly set to a non-zero value.
- Clarify initially clearing `MVKImagePresentInfo` to all zeros.
Fixes issue #1925.

Support VK_PRESENT_MODE_IMMEDIATE_KHR if VkPresentTimeGOOGLE::desiredPresentTime is zero.

---

MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

This avoids crashes in CTS when creating a graphics pipeline.

Allow both renderPass and VkPipelineRenderingCreateInfo to be missing.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKShaderModule.mm
MoltenVKShaderConverter/MoltenVKShaderConverter/SPIRVToMSLConverter.cpp

Remove unhelpful "Shader module does not contain
an entry point named 'main0'" error message.

Log more info about SPIR-V to MSL conversion errors.

---

Docs/MoltenVK_Runtime_UserGuide.md
Docs/Whats_New.md
MoltenVK/MoltenVK/API/mvk_datatypes.h
MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.h
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKDeviceFeatureStructs.def
MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.h
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm
MoltenVK/MoltenVK/Layers/MVKExtensions.def
MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm

This turned out to be a little bit more involved than I had hoped. But, with this, we can now use the `VK_FORMAT_A4R4G4B4_UNORM_PACK16` and `VK_FORMAT_A4B4G4R4_UNORM_PACK16` formats from shaders, use them as blit sources, and even clear them. Storage images and render targets of these formats aren't supported, however. To support the latter would require the insertion of a swizzle into the fragment shader before returning. The former cannot be reasonably supported.

Support the `VK_EXT_4444_formats` extension.

---

Docs/MoltenVK_Runtime_UserGuide.md
Docs/Whats_New.md
MoltenVK/MoltenVK/Layers/MVKExtensions.def

This just provides support for the `SPV_KHR_non_semantic_info` extension, which supports extended instruction sets that do not affect the semantics of a SPIR-V shader (e.g. debug info). SPIRV-Cross already handles these instruction sets, so no additional work is required on our part to support this extension.

Advertise the `VK_KHR_shader_non_semantic_info` extension.

---

MoltenVK/MoltenVK/GPUObjects/MVKSync.h
MoltenVK/MoltenVK/GPUObjects/MVKSync.mm
MoltenVK/MoltenVK/Vulkan/vulkan.mm

- Fix unreachable code in `MVKDeferredOperation::join()`.
- Refactor code so deferred functions call back to `MVKDeferredOperation` instance to update current status, and deferred function execution returns result of individual thread execution.
- `MVKDeferredOperation` use `MVKSmallVector` for `_functionParameters`.
- `MVKDeferredOperation` use a single mutex lock.
- Add additional comments explaining design to developers of future extensions that use deferred operations.
@AntarticCoder Please review as changes to your original code. Most of it is just clean up and documentation, but the way that deferred functions interact with `MVKDeferredOperation::join()` functionally has changed. I also did not have any trouble with `MVKSmallVector` on either Xcode 14 or 15, so I've reverted to …

Fix unreachable code in MVKDeferredOperation::join().

---

Docs/Whats_New.md
MoltenVK/MoltenVK/Commands/MVKCmdDraw.h
MoltenVK/MoltenVK/Commands/MVKCmdDraw.mm
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/Commands/MVKCommandEncodingPool.h
MoltenVK/MoltenVK/Commands/MVKCommandEncodingPool.mm
MoltenVK/MoltenVK/Commands/MVKCommandPipelineStateFactoryShaderSource.h
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.h
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
MoltenVK/MoltenVK/Utility/MVKFoundation.h
MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm

To reduce complexity and repetitive copy-pasted spaghetti code, the design approach here was to implement triangle fan conversion on `MVKCmdDrawIndexedIndirect`, as the most general of the draw commands, and then populate and invoke a synthetic `MVKCmdDrawIndexedIndirect` command from the other draw commands.
- Rename pipeline factory shader `cmdDrawIndexedIndirectMultiviewConvertBuffers()` to `cmdDrawIndexedIndirectConvertBuffers()`, and in addition to original support for modifying indirect content to support multiview, add support for converting triangle fan indirect content and indexes to triangle list.
- Modify `MVKCmdDrawIndexedIndirect` to track need to convert triangle fans to triangle list, and invoke kernel function when needed.
- Modify `MVKCmdDraw`, `MVKCmdDrawIndexed`, and …

Add support for VK_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN.

---

Common/MVKCommonEnvironment.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVKShaderConverter/MoltenVKShaderConverterTool/OSSupport.mm

In this PR, I've added support for Xcode 15, and added a case for MSL version 3.1. I added this because I noticed xcode was throwing some warnings about an unhandled switch case.

Added Enum for MSL Version 3.1

---

Common/MVKOSExtensions.h
Common/MVKOSExtensions.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
MoltenVK/MoltenVK/GPUObjects/MVKShaderModule.h
MoltenVK/MoltenVK/GPUObjects/MVKShaderModule.mm
MoltenVK/MoltenVK/Layers/MVKExtensions.def

This provides feedback that indicates:
* how long it took to compile each shader stage and the pipeline as a whole;
* whether or not the pipeline or any shader stage were found in any supplied pipeline cache; and
* whether or not any supplied base pipeline were used to accelerate pipeline creation.
This is similar to the performance statistics that MoltenVK already collects.
Since we don't use any supplied base pipeline at all, this implementation never sets
`VK_PIPELINE_CREATION_FEEDBACK_BASE_PIPELINE_ACCELERATION_BIT`. However, I've identified several places where we could probably use the base pipeline to accelerate pipeline creation. One day, I should probably implement that.
Likewise, because we don't yet support using `MTLBinaryArchive`s, …

Support the `VK_EXT_pipeline_creation_feedback` extension.

---

MoltenVK/MoltenVK/API/mvk_datatypes.h
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.h
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm
MoltenVK/MoltenVK/Layers/MVKExtensions.def
MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm

This extension allows apps to provide a hint to the presentation engine indicating which parts of the surface need updating. To provide this hint, we call `-[CALayer setNeedsDisplayInRect:]`, which indicates that only the given rectangle needs updating.
I'm not sure if this will have any effect, especially if `CAMetalLayer.presentsWithTransaction` is `NO`. Luckily for us, this is only a hint, and it is permissible for the presentation engine to do nothing with the hint.
The tests don't work because they apparently can't handle `VK_SUBOPTIMAL_KHR` being returned.

Support the `VK_KHR_incremental_present` extension.

---

.github/workflows/CI.yml
Docs/Whats_New.md

- Remove Xcode 11 build from GitHub CI.
- Leave `MVK_XCODE_12` guards in place to allow devs to possibly continue to attempt to build existing MoltenVK code using Xcode 11, even though it's not officially supported. Such devs may have to add their own additional `MVK_XCODE_12` guards for any Xcode 12 API features added after this change.

Drop official support for using Xcode 11 to build MoltenVK.

---

MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm

Needed to complete fix for #1874
We can't wait until getMTLComputeEncoder() is called to dirty the state, because this call will be avoided by dirty checks themselves. Those checks are comparing against leftover and now incorrect state since the previous encoder has already ended.
It needs to be dirtied on encoder end.

Fix regression caused by #1922

---

fetchDependencies

This allows rebuilding without an internet connection and avoids random build failures on flaky connections.

Don't fetch a submodule if the commit is already known

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueue.h
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm

The `[MTLDevice sampleTimestamps:gpuTimestamp:]` function turns out to be synchronized with other queue activities, and can block GPU execution if it is called between `MTLCommandBuffer` submissions. On non-Apple-Silicon devices, it was called before and after every `vkQueueSubmit()` submission, to track the correlation between GPU and CPU timestamps, and was delaying the start of GPU work on the next submission (on Apple Silicon, both CPU & GPU timestamps are specified in nanoseconds, and the call was bypassed).
Move timestamp correlation from `vkQueueSubmit()` to `vkGetPhysicalDeviceProperties()`, where it is used to update `VkPhysicalDeviceLimits::timestampPeriod` on non-Apple-Silicon devices.
Delegate `MVKPhysicalDevice::getProperties(VkPhysicalDeviceProperties2*)` to …

Fix sync delay between calls to vkQueueSubmit() on non-Apple-Silicon devices.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

Xcode simulator always requires 256B buffer alignment, even when running on Apple Silicon. Previously, it was assumed that Apple Silicon would use its native 16B buffer alignment.
Fixes issue #1989.

Ensure Xcode simulator always uses 256B buffer alignment.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

- Guard against Intel returning zero values for CPU & GPU timestamps.
- Apply lowpass filter on timestampPeriod updates, to avoid wild temporary changes, particularly at startup before GPU has been really exercised.
Fixes #1995.

Fix VkPhysicalDeviceLimits::timestampPeriod calculations on Intel GPU.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.h

In the rare case where vertex attribute buffers are bound to `MVKCommandEncoder`, are not used by first pipeline, but are used by a subsequent pipeline, and no other bindings are changed, the `MVKResourcesCommandEncoderState` will not appear to be dirty to the second pipeline, and the buffer will not be bound to Metal.
When reverting a binding to dirty if it is not used by a pipeline, also revert the enclosing `MVKResourcesCommandEncoderState` to dirty state.
Update MoltenVK to version 1.2.6 (unrelated).
Fixes issue #1931.

Fix rare case where vertex attribute buffers are not bound to Metal.

---

Common/MVKOSExtensions.h
Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm

- Calling `nextDrawable` may result in a nil drawable, or a drawable with no pixel format. Attempt several times to retrieve a drawable with a valid pixel format, and if unsuccessful, return an error from `vkQueuePresentKHR()` and `vkAcquireNextImageKHR()`, to force swapchain to be re-created.
- Reorganize `MVKQueuePresentSurfaceSubmission::execute()` to detect drawable with invalid format, attach `MTLCommandBuffer` completion handler just before commit, and delay enqueuing `MTLCommandBuffer` until commit.
- Refactor `mvkOSVersionIsAtLeast()` for clarity (unrelated).
Possible fix for #1990.

Guard against CAMetalDrawable with invalid pixel format.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/mvk_config.h
MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm

- `vkCmdBlitImage()` ensure swizzle texture view is retained for life of `MTLCommandBuffer`.
- `vkQueuePresentKHR()` use `MTLCommandBuffer` that retains references.
- Update MoltenVK version to 1.2.6.
Fixes #2014.

Ensure objects retained for life of MTLCommandBuffer.

---

Common/MVKOSExtensions.h
Common/MVKOSExtensions.mm
Docs/MoltenVK_Runtime_UserGuide.md
Docs/Whats_New.md
MoltenVK/MoltenVK.xcodeproj/project.pbxproj
MoltenVK/MoltenVK/API/mvk_config.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/Utility/MVKConfigMembers.def
MoltenVK/MoltenVK/Utility/MVKEnvironment.cpp
MoltenVK/MoltenVK/Utility/MVKEnvironment.h
Scripts/runcts

- Add `MVKConfiguration::timestampPeriodLowPassAlpha`, along with matching `MVK_CONFIG_TIMESTAMP_PERIOD_LOWPASS_ALPHA` env var.
- Add `MVKConfigMembers.def` file to describe `MVKConfiguration` members, to support consistent batch handling of members.
- Add env var & build settings `MVK_CONFIG_DEBUG`, plus legacy `MVK_CONFIG_ALLOW_METAL_EVENTS` & `MVK_CONFIG_ALLOW_METAL_FENCES`.
- Simplify environment variable retrieval functions and macros.
- Rename `MVKDevice::updateTimestampsAndPeriod()` to `updateTimestampPeriod()`.
Fixes issue #2013.

Add configurable lowpass filter for VkPhysicalDeviceLimits::timestampPeriod.

---

MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueue.h
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.h
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm

- To force any incomplete CAMetalDrawable presentations to complete, don't force the creation of another transient drawable, as this can stall the creation of future drawables. Instead, when a swapchain is destroyed, or replaced by a new swapchain, set the `CAMetalLayer drawableSize`, which will force presentation completion.
- Add presentation completion handler in command buffer scheduling callback, move marking available to presentation completion handler, and minimize mutex locking.
- `MVKQueue::waitIdle()` remove wait for swapchain presentations, and remove callbacks to MVKQueue from drawable completions.
- `MVKQueue::submit()` don't bypass submitting a misconfigured submission, so that semaphores and fences will be signalled, and ensure misconfigured submissions are well behaved.
- …

Rework workaround to force incomplete CAMetalDrawable presentations to complete.

---

Docs/MoltenVK_Runtime_UserGuide.md
Docs/Whats_New.md
MoltenVK/MoltenVK/API/mvk_datatypes.h
MoltenVK/MoltenVK/Commands/MVKCmdPipeline.h
MoltenVK/MoltenVK/Commands/MVKCmdPipeline.mm
MoltenVK/MoltenVK/Commands/MVKCmdQueries.h
MoltenVK/MoltenVK/Commands/MVKCmdQueries.mm
MoltenVK/MoltenVK/Commands/MVKMTLResourceBindings.h
MoltenVK/MoltenVK/GPUObjects/MVKBuffer.h
MoltenVK/MoltenVK/GPUObjects/MVKBuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKDeviceFeatureStructs.def
MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueue.h
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.h
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.mm
MoltenVK/MoltenVK/GPUObjects/MVKResource.h
MoltenVK/MoltenVK/GPUObjects/MVKShaderModule.h
MoltenVK/MoltenVK/GPUObjects/MVKShaderModule.mm
MoltenVK/MoltenVK/Layers/MVKExtensions.def
MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm
MoltenVK/MoltenVK/Vulkan/vulkan.mm

- `MVKPhysicalDevice` add support for `VkPhysicalDeviceSynchronization2Features`.
- Pass sync2 structs to `MVKPipelineBarrier`, `MVKCmdPipelineBarrier`, `MVKCmdSetEvent`, `MVKCmdResetEvent`, `MVKCmdWaitEvents`, `MVKRenderPass`, `MVKQueue` & `MVKQueueSubmission`.
- Replace use of `VkPipelineStageFlags` & `VkAccessFlags` with `VkPipelineStageFlags2` & `VkAccessFlags2`.
- Add stage masks to `MVKPipelineBarrier`, and redefine `apply*MemoryBarrier()` functions to remove separately passing stage masks.
- Add `MVKSemaphoreSubmitInfo` to track semaphores in `MVKQueueSubmission`.
- Add `MVKCommandBufferSubmitInfo` to track command buffers in `MVKQueueCommandBufferSubmission`.
- Add `MVKSubpassDependency` to combine `VkSubpassDependency` & `VkMemoryBarrier2` in `MVKRenderPass`.
- Remove abstract …

Add support for extension VK_KHR_synchronization2

---

MoltenVK/MoltenVK/Commands/MVKCommandBuffer.h
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.h
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/Commands/MVKMTLBufferAllocation.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueryPool.h
MoltenVK/MoltenVK/GPUObjects/MVKQueryPool.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueue.h
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.h
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.mm
MoltenVK/MoltenVK/Utility/MVKBaseObject.h
MoltenVK/MoltenVK/Utility/MVKFoundation.h
MoltenVK/MoltenVK/Utility/MVKSmallVector.h
MoltenVK/MoltenVK/Vulkan/vulkan.mm

Minor things I changed while working on other features
You can check the individual commits for details, the biggest one is a modification of MVKArrayRef so you use `MVKArrayRef<const X>` instead of `const MVKArrayRef<X>`, as you can't accidentally un-const the former by copying it into a local variable, (which you can do with ArrayRefs, since they don't own their storage)

Misc Cleanup

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

- `MVKPipeline` only work around zero stride if stride is static.
- Ensure dynamic vertex stride is not enabled on builds before Xcode 15.
- Add `MVKRenderStateType::LineWidth` for track all default options (unrelated).
Fixes issue #2041.

Fixes for VK_EXT_extended_dynamic_state.

---

Docs/MoltenVK_Runtime_UserGuide.md
Docs/Whats_New.md
MoltenVK/MoltenVK/API/mvk_config.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueryPool.mm
MoltenVK/MoltenVK/Utility/MVKConfigMembers.def
MoltenVK/MoltenVK/Utility/MVKEnvironment.cpp
MoltenVK/MoltenVK/Utility/MVKEnvironment.h

- On Apple GPUs, set `timestampPeriod` to 1.0.
- On non-Apple GPUs, calculate `timestampPeriod` each time it is retrieved.
- On older devices that do not support GPU timestamps, use nanosecond CPU timestamps to be consistent with `timestampPeriod` of 1.0.
- Change `MVKConfiguration::timestampPeriodLowPassAlpha` and environment variable `MVK_CONFIG_TIMESTAMP_PERIOD_LOWPASS_ALPHA` to `1.0`, to use only latest value by default.
- Add build-time verification that `MVKConfigMembers.def` includes all members of `MVKConfiguration` (unrelated).
Fixes issue #2039.
Fixes issue #2040.

Fixes to determination of VkPhysicalDeviceLimits::timestampPeriod.

---

MoltenVK/MoltenVK/Commands/MVKCmdRendering.h
MoltenVK/MoltenVK/Commands/MVKCmdRendering.mm
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.h
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

- Move check and warning to `MVKRenderingCommandEncoderState`.
- Pass `primitiveRestartEnable` to `MVKRenderingCommandEncoderState`.
- Warn only if `primitiveRestartEnable` disabled and strip topology is used.
Fixes issue #2045.

Emit primitiveRestartEnable disabled warning only for strip topology.

---

.github/workflows/CI.yml
Docs/Whats_New.md
MoltenVK/MoltenVK/API/mvk_config.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
README.md
Scripts/create_ext_lib_xcframeworks.sh
Scripts/package_ext_libs_finish.sh
fetchDependencies

- Add `--keep-cache` option to control whether or not to retain the `External/build/Intermediates` directory (default not retained).
- Export `KEEP_CACHE` & `SKIP_PACKAGING` to be available within scripts used by `ExternalDependencies` Xcode builds.
- Move `BLD_SPECIFIED` to `build()` instead of `build_impl()` to avoid updating it from background thread (which will fail).
- Update MoltenVK version to 1.2.7 (unrelated).
- Add `CompilerMSL::Options::replace_recursive_inputs` to pipeline cache (unrelated).
- Update GitHub CI to Xcode 15.0.
- Update `Whats_new.md` document.

Reduce disk space consumed after running fetchDependencies.

---

MoltenVK/MoltenVK/Utility/MVKBitArray.h

Reset startIndex so that we only skip over bits in the section that contains it.

Fix MVKBitArray::getIndexOfFirstSetBit() skipping over entries.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm

- Don't create global `MVKPixelFormats` instance during launch, as this triggers a call to `MTLCopyAllDevices()`, which can deadlock if app is also launching other services that use Metal.
Fixes #2050.

Fix rare deadlock during launch via dlopen().

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

These features must be supported if the extension or `descriptorIndexing` feature is.
Fixes `dEQP-VK.info.device_mandatory_features`.

Enable some mandatory `VK_EXT_descriptor_indexing` features.

---

MoltenVK/MoltenVK/GPUObjects/MVKBuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

Previously, we were erroneously failing create calls that specified zero external handle types (as opposed to omitting external memory info entirely).
Fixes 6 tests under
`dEQP-VK.api.buffer_memory_requirements.create_no_flags.ext_mem_flags_included.*`

MVKBuffer, MVKImage: Also ignore no external handle types specified.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

- Don't update value of `timestampPeriod` on first measurement.
- Force that first measurement upon creation of `MVKPhysicalDevice`, so an accurate value for `timestampPeriod` will be calculated when next queried.
Adds further fix to #2040.

Fix initial value of VkPhysicalDeviceLimits::timestampPeriod on non-Apple Silicon GPUs.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

As required by the Vulkan spec.
Fixes the CTS tests
`dEQP-VK.api.info.vulkan1p2_limits_validation.khr_maintenance_3` and
`dEQP-VK.api.maintenance3_check.maintenance3_properties`.

MVKDevice: Clamp max per-set descriptor limit to minimum 1024.

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

Handle it similarly to the `A4R4B4G4` and `A4B4G4R4` formats, with a swizzle. Vulkan requires support for this format.
Fixes the following tests:
* `dEQP-VK.api.info.format_properties.b4g4r4a4_unorm_pack16`.
* `dEQP-VK.texture.explicit_lod.2d.formats.b4g4r4a4*`

MVKPixelFormats: Handle the `B4G4R4A4` format.

---

Common/MVKOSExtensions.h
Common/MVKOSExtensions.mm
Docs/MoltenVK_Runtime_UserGuide.md
Docs/Whats_New.md
MoltenVK/MoltenVK.xcodeproj/project.pbxproj
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKInstance.h
MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.h
MoltenVK/MoltenVK/GPUObjects/MVKSurface.h
MoltenVK/MoltenVK/GPUObjects/MVKSurface.mm
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.h
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm
MoltenVK/MoltenVK/GPUObjects/MVKSync.mm
MoltenVK/MoltenVK/Layers/MVKExtensions.def
MoltenVK/MoltenVK/OS/CAMetalLayer+MoltenVK.h
MoltenVK/MoltenVK/OS/CAMetalLayer+MoltenVK.mm
MoltenVK/MoltenVK/Vulkan/vulkan.mm
README.md

- Consolidate info about `CAMetalLayer` and headless in `MVKSurface`.
- `MVKSwapchainImage` remove `getCAMetalDrawable()` and focus on abstracting `getMTLTexture()`.
- `MVKPresentableSwapchainImage::getCAMetalDrawable()` return `nil` if headless.
- Add `MVKPresentableSwapchainImage::_mtlTextureHeadless` to support a fixed `MTLTexture` that is not retrieved from a `CAMetalDrawable`.
- `MVKPresentableSwapchainImage` refactor signalling semaphores and fences.
- `MVKPresentableSwapchainImage` don't lock when signalling semaphores and fences.
- If no present occurs, `actualPresentTime` will be zero. Set it to current time, instead of to `desiredPresentTime`, since it's more accurate.
- Rework timestamps:
- Remove `_mvkTimestampBase` so `mvkGetTimestamp()` is equal to `mach_absolute_time()`, …

Add support for extension VK_EXT_headless_surface.

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

PixelFormatView disables compression on color textures, and shouldn't be applied to every texture that can be used as a copy source / dst (which includes all textures in translation libraries like DXVK and vkd3d)
Improves performance in games like Diablo IV on M1
This does mean we may need an extra copy if something attempts to reinterpret-copy between two images with different formats, but hopefully that's less common than using the images normally.

Don't enable PixelFormatView just in case we need it to copy

---

Common/MVKOSExtensions.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

Fixes #2082 for non-unified memory machines.  No change for unified memory machines.
1. Replaces `task_vm_info.phys_footprint` with `task_vm_info.ledger_tag_graphics_footprint` in `mvkGetUsedMemorySize()`.  This provides a more accurate estimate of mapped memory for `heapUsage[1]` on non-unified memory machines.  As an aside, it also provides a more accurate fall-back within `MVKPhysicalDevice::getCurrentAllocatedSize()` if the selector is not available for any machine.
2. Fixes the calculation for `heapUsge[0]` on non-unified memory machines, where it represents the device-only memory.  The calculation remains the same for unified memory machines (where `heapUsage[1] = 0`).
The only edge case I see is for non-unified memory machines where the `currentAllocatedSize` selector is not …

Fix heapUsage query for non-unified memory devices

---

MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.h
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm

- `MVKGraphicsPipeline::isRenderingPoints()` fix regression error to support dynamically setting point topology.
- Move emulation of `VK_POLYGON_MODE_POINT` in Metal, if the polygon model is static, to `MVKRenderingCommandEncoderState`, to handle dynamic setting of topology.
- `MVKDevice` populate `VkPhysicalDeviceExtendedDynamicState3PropertiesEXT`.
- Move error reporting in `mvkMTLTriangleFillModeFromVkPolygonModeInObj()` to encoding.
- `MVKRenderingCommandEncoderState::setCullMode()` use `getContent()` for readability and consistency (unrelated).
- Pass pipeline object to datatype functions for reporting accuracy (unrelated).
Fixes issue #2096.

Fix regression error and properties in point-topology/polygon-mode behavior.

---

Common/MVKOSExtensions.mm

use sysctlbyname("hw.memsize") to get sytem memory size instead of host_info, host_info is not available on tvOS, so we change to sysctlbyname which support all apple platforms
the sytem memory size of tvOS is hardcoded as 0 currently, found this [bug](https://github.com/haasn/libplacebo/issues/229#issuecomment-1857622686) while using libplacebo's vulkan render to play video on tvOS 
apple [document](https://developer.apple.com/documentation/kernel/1387446-sysctlbyname
) didn't stat this API is available on tvOS though

Fix system memory size of tvOS

---

MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.h
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

Metal 3.1 and iOS 17/macOS 14 add support for these two new vertex/attribute formats.
I also put in all of the necessary fixes (afaik) for Xcode 15 into this PR.

Add support for RG11B10 and RGB9E5 vertex formats

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

Tiny fix to recognize Apple9 and some format changes.
The [feature set tables](https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf) list 'All' for every 32-bit format on Apple9.
I also noticed that `RG32Uint` and `RG32Sint` have MSAA (since Apple7) and Atomic (since Apple8). The Atomic one is not listed in the MVK code at all, while MSAA relies on the `supports32bitMSAA` function. Though I am not sure that's correct, since the MSAA capabilities don't line up with the other formats. Is this intended?

Add: Recognize Apple9

---

Docs/MoltenVK_Runtime_UserGuide.md
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.h
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm
MoltenVK/MoltenVK/Layers/MVKExtensions.def

We don't use any of the new flags anyway, so this should be an invisible change to most users. But this extension and its functionality are part of 1.3, so this has to be implemented anyway.
This code is just blindly converting the flags right now, but it works for now. I also decided to switch to the new flag bits internally because I think this would allow seamless usage of any new flag bits we might want to make use of. The conversion back is a simple static_cast so I don't think there's any performance or memory reason to choose either side. Though should I also replace every single usage of the original enumerations with the new ones? Right now they work seamlessly but it could look weird in the future when both are mixed together.

Add: KHR_format_feature_flags2

---

MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.h
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

- Support additional VK_KHR_format_feature_flags2 format feature flags.
- `VK_FORMAT_FEATURE_2_STORAGE_READ_WITHOUT_FORMAT_BIT`
- `VK_FORMAT_FEATURE_2_STORAGE_WRITE_WITHOUT_FORMAT_BIT`
- `VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_DEPTH_COMPARISON_BIT`
-`MTLPixelFormats` constructor retrieve MTLDevice when no physical device (unrelated).
- To consistently modify settings based on `MTLDevice`, `MTLPixelFormats` constructor retrieves or creates temp `MTLDevice` once, and passes to support functions.

Various small regression fixes from SDK testing

---

Common/MVKCommonEnvironment.h
Demos/Cube/Cube.xcodeproj/project.pbxproj
Demos/README.md
Docs/Whats_New.md
Makefile
MoltenVK/MoltenVK/Vulkan/vulkan.mm
README.md

- Statically expose `vkGetInstanceProcAddr()`, even when `MVK_HIDE_VULKAN_SYMBOLS` is enabled.
- To support _Volk_, link _Cube_ demo dynamically to `libMoltenVK.dylib` instead of statically to `MoltenVK.xcframework`.

Revert to disabling MVK_HIDE_VULKAN_SYMBOLS by default.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/mvk_private_api.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

- `MVKImage` add functions to consolidate mapping plane indexes to memory bindings to add safety in situation where one memory binding supports all planes.
- Update MoltenVK version to 1.2.8 (unrelated).
This PR fixes an internal design issue uncovered during preliminary testing of PR #2116, the additional functionality of which caused certain CTS tests to crash. This PR fixes those crashes, and potentially other future crashes.
Initially pushing this to a temporary branch, until the current SDK release process is completed.

Fix potential crash when using multi-planar images.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/Commands/MVKCmdDispatch.mm
MoltenVK/MoltenVK/Commands/MVKCmdDraw.mm
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.h
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.h
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

Fix issue where push constants contain a buffer address, but no descriptor resources are encoded, resulting in addressed buffer not resident in GPU.
- Add `MVKGPUAddressableBuffersCommandEncoderState` to track when the GPU-addressable buffer usage needs to be encoded, and only encode them once per Metal renderpass.
- Set `MVKGPUAddressableBuffersCommandEncoderState` dirty whenever a buffer is bound for a descriptor or a push constant.
Unrelated changes:
- `MVKCommandEncoder::finalizeDrawState()` reorder encoding of encoder states to encode resource and push-constant encoder states together.
- Move `getGraphicsPipeline()` and `getComputePipeline()` to `MVKCommandEncoder`.
- `MVKDevice` remove preallocation on _resources and _gpuAddressableBuffers.
- Align conditions for …

Ensure buffers available for buffer addresses in push constants.

---

MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

Fix crash on CTS test:
dEQP-VK.robustness.robustness1_vertex_access.out_of_bounds_stride_30_middle_of_buffer
Bindings with multiple vertex attributes would not correctly detect if the whole binding was remapped to new location/s. This meant original binding's stride was never set to 0 which would report an error and in some cases crash.

Fix translation of fully remapped multi vertex attribute bindings

---

Demos/Cube/Cube.xcodeproj/project.pbxproj
Demos/README.md
Docs/Whats_New.md
MoltenVK/MoltenVK.xcodeproj/project.pbxproj

- Xcode now supports building `dylib` for iOS Simulator (but unfortunately not yet tvOS Simulator).
- Restore support for iOS Simulator destination in recent update to Cube demo that uses dynamic-linking, by using script build phase to overwrite the iOS build of MoltenVK with the iOS Simulator build.
Fix #2134.

Support libMoltenVK.dylib for iOS Simulator architecture.

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/Commands/MVKCommandEncodingPool.h
MoltenVK/MoltenVK/Commands/MVKCommandEncodingPool.mm
MoltenVK/MoltenVK/Commands/MVKCommandPipelineStateFactoryShaderSource.h
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.h
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.mm
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.mm

Implementation did not correctly handle array textures when resolving unresolvable textures like r8uint formats. Add kernel modules to correctly resolve through the compute pass.
Fixes CTS failures in test families:
`dEQP-VK.api.image_clearing.core.clear_color_attachment.*`
`dEQP-VK.renderpass.suballocation.multisample_resolve.*`

Fix unresolvable layered compute resolve

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKSurface.h
MoltenVK/MoltenVK/GPUObjects/MVKSurface.mm

Don't update currentExtent of headless surface when swapchain attached.

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

Fixes CTS tests:
`dEQP-VK.pipeline.monolithic.sampler.border_swizzle.d*.opaque_white.*`

Handle depth/stencil swizzle sample correctly

---

Docs/Whats_New.md
MoltenVKPackaging.xcodeproj/project.pbxproj
Scripts/get_failing_cts_tests.py
Scripts/runcts

- Add `get_failing_cts_tests.py` script to extract failures from `runcts` output, and call automatically from `runcts`.

runcts script also output a file containing a list of the failed CTS tests.

---

MoltenVK/MoltenVK/Utility/MVKSmallVector.h

Or the newest libc++ in Xcode 15.3 won't build.
Fixes #2156.

MVKSmallVector: Make iterator const correct.

---

MoltenVK/MoltenVK/API/mvk_private_api.h
MoltenVK/MoltenVK/GPUObjects/MVKBuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.mm
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.h
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

This commit conditionally skips the emulated image atomics paths if native texture atomics are available and a configuration option is set.
Apart from unlocking some potential performance benefits from not having to force some textures to be linear, it also makes texture atomics work with argument buffers.

Enable use of native texture atomics.

---

MoltenVK/MoltenVK/GPUObjects/MVKBuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

Partially fixes #2172. Outstanding problems are float atomics and that we're not handling image views correctly, as described in the issue.

Don't set MTLTextureUsageShaderAtomic if the pixel format does not support it.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKDeviceFeatureStructs.def
MoltenVK/MoltenVK/Layers/MVKExtensions.def
fetchDependencies

- `fetchDependencies` script pulls `VK_KHR_portability_subset_metal` content from private Khronos repo.
- Add `VK_KHR_portability_subset_metal` extension.
- Include `VkPhysicalDevicePortabilitySubsetMetalFeaturesKHR` in `pNext` of `VkPhysicalDeviceFeatures2`.

Development support for future VK_KHR_portability_subset_metal extension.

---

MoltenVK/MoltenVK/API/mvk_private_api.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueue.h
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm
MoltenVK/MoltenVK/Vulkan/mvk_api.mm

Addresses #2177.
This small PR adds a `previous` member to the `MVKPerformanceTracker` struct and saves the former `latest` value before updating `latest` within `updateActivityPerformance()`.  It also adds `previous` to `MVKLogInfo`.
Note that I did not change the `MVK_PRIVATE_API_VERSION`.
I still have a question about how to determine version information at runtime.  Now that `vkGetVersionStringsMVK()` is deprecated, what is the offical means of determining MoltenVK's version or the `MVKPerformanceStatistics` version at runtime?  This is to handle cases when dynamic linking is used and one needs to determine if the new field is present.
Is the only mechanism to use the `VK_SUCCESS` or `VK_INCOMPLETE` return code from `vkGetPerformanceStatisticsMVK()`?  This approach seems limiting …

Add "previous" member to MVKPerformanceTracker structure

---

Docs/Whats_New.md
Scripts/package_dylibs.sh

- Create symlink from `MoltenVK/dylib` to `MoltenVK/dynamic/dylib`.
Fixes issue #2191.

To support legacy apps, restore MoltenVK/dylib directory.

---

Docs/Whats_New.md
Templates/Vulkan-Headers/VK_EXT_metal_objects-unret.gitdiff
fetchDependencies

Apple's Automatic Reference Counting automatically releases the Metal objects returned by `VK_EXT_metal_objects`.
The `fetchDependencies` script now applies
`Templates/Vulkan-Headers/VK_EXT_metal_objects-unret.gitdiff` to add an `__unsafe_unretained` ownership qualifier to the Metal object declarations in `vulkan_metal.h`.
This should be a temporary patch until the `VK_EXT_metal_objects` extension can be properly modified.
Fixes #2151.
Replaces #2179.
@MennoVink Please review.

Fix crash when using VK_EXT_metal_objects under ARC.

---

MoltenVK/MoltenVK/API/mvk_private_api.h
MoltenVK/MoltenVK/Utility/MVKConfigMembers.def
MoltenVK/MoltenVK/Utility/MVKEnvironment.cpp

- Remove `_unused_struct_padding` from `MVKConfiguration` and `MVKConfigMembers.def`.
- Add `kMVKConfigurationInternalPaddingByteCount` to specify `MVKConfiguration` internal padding byte count, for use in build time assertion check.

Simplify maintenance of build-time checking of MVKConfiguration members.

---

Docs/MoltenVK_Configuration_Parameters.md
MoltenVK/MoltenVK/API/mvk_private_api.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
MoltenVK/MoltenVK/GPUObjects/MVKShaderModule.mm
MoltenVK/MoltenVK/Utility/MVKConfigMembers.def
MoltenVK/MoltenVK/Utility/MVKEnvironment.h

Adds an option to dump shaders and pipelines to a directory
When enabled, it writes the spirv and resulting msl for every shader compiled to a file named by the spirv hash
Usually a bit easier to search through than trying to look through an MVK_DEBUG=1 log, especially for pipeline link failures

Add option to dump shaders

---

MoltenVK/MoltenVK/API/mvk_datatypes.h
MoltenVK/MoltenVK/GPUObjects/MVKBuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKDeviceMemory.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm

Like their iOS/tvOS counterparts, macOS Apple Silicon GPUs support using Shared memory for textures, and do not require resource synchronization, even with Managed memory. This change treats macOS Apple Silicon the same as iOS & tvOS.
- `MVKPhysicalDevice` add `_hasUnifiedMemory` & `_isAppleGPU` flags.
- `MVKDeviceTrackingMixin` add `isUnifiedMemoryGPU()` & `isAppleGPU()`.
- Do not advertise host-visible-but-not-host-coherent Vulkan memory type on macOS Apple Silicon.
- Replace `mvkMTLStorageModeFromVkMemoryPropertyFlags()` with `MVKPhysicalDevice::getMTLStorageModeFromVkMemoryPropertyFlags()`, and return Shared instead of Managed for Apple Silicon, even if coherency is not requested.
- On unified memory devices, avoid needless calls to `didModifyRange:`, `synchronizeResource:`, and …

On macOS Apple Silicon, avoid managed-memory textures, and resource syncs.

---

MoltenVK/MoltenVK/Commands/MVKCmdDraw.mm
MoltenVK/MoltenVK/Commands/MVKCmdPipeline.mm
MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.h
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/Commands/MVKCommandEncodingPool.mm
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.mm
MoltenVK/MoltenVK/Commands/MVKMTLBufferAllocation.mm
MoltenVK/MoltenVK/GPUObjects/MVKBuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.mm
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKDeviceMemory.mm
MoltenVK/MoltenVK/GPUObjects/MVKFramebuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKInstance.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueryPool.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueue.h
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.mm
MoltenVK/MoltenVK/GPUObjects/MVKShaderModule.h
MoltenVK/MoltenVK/GPUObjects/MVKShaderModule.mm
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm
MoltenVK/MoltenVK/GPUObjects/MVKSync.h
MoltenVK/MoltenVK/GPUObjects/MVKSync.mm

This is a non-functional code-maintenance change.
Previously, `MVKDevice` contained a significant amount of publicly exposed internal content. This patch adds functions to `MVKDeviceTrackingMixin` to better encapsulate, consolidate & streamline access to this content.
- Make `MVKDeviceTrackingMixin` a friend of `MVKDevice` & `MVKPhysicalDevice`.
- Hide public `MVKDevice` content behind `MVKDeviceTrackingMixin` functions.
- Remove similar `MVKDevice` content pointers from `MVKCommandEncoder`.
- `MVKDevice` remove `getPhysicalDevice()`, `getPixelFormats()` & `getMTLDevice()`, to focus access through `MVKDeviceTrackingMixin`.
- Move performance tracking functions to `MVKDeviceTrackingMixin` to remove need to reference `MVKDevice` multiple times when marking performance values.
- Subclass …

Refactor public MVKDevice content into MVKDeviceTrackingMixin functions.

---

MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm

There was a missing autorelease pool. Fixes #2223.

Fix memory leak in vkQueueWaitIdle

---

MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm
MoltenVK/MoltenVK/Utility/MVKBaseObject.h
MoltenVK/MoltenVK/Utility/MVKBaseObject.mm

Fixes #2219.
Previously the `pMessageIdName` field of debug utils callback data was set to **nullptr**, i.e. no messageId name.  To provide more context and information to the user, we now fill this field with the MoltenVK log level string.  This, combined with the `pMessage` string, shows the severity of the message in textual form, and indicates that it comes from MoltenVK.
Note I have changed the `mvkGetReportingLevelString()` function declaration to **inline** - I hope this is appropriate.
Also, after making this change I wonder whether it should also be applied to the debug report callback code, i.e. replace `_debugReportCallbackLayerPrefix` with `mvkGetReportingLevelString()` for consistency?  I don't want to break anything re automated testing scripts, etc. so I didn't make this …

Return MoltenVK log level string in pMessageIdName field of debug utils callback data

---

MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

Fixes #1609 
Due to how MoltenVK decides when a buffer can be bound based on its requirements for the implicit buffer, if the application uses all bindings, implicit buffer index will be uint max. This lead to used buffers not being bound.
I did not test with the application mentioned in #1592 so if someone with the set up ready to test could, it would be great.
Although this change fixes the issue, it's a partial fix. I will create a new issue to discuss some concerns about the whole vertex input attachment architecture, since I do believe we would benefit from a rework of the system (I may be wrong tho). Haven't created a PR with a proof of concept since it'll require a considerable time investment I cannot afford currently.

Allow vertex buffer binding when they are used disregarding implicit buffer index

---

Docs/Whats_New.md
ExternalRevisions/SPIRV-Cross_repo_revision
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

- Pull in SPIRV-Cross fix for argument buffer padding.
- Only use `MTLTextureUsageShaderAtomic` if native atomics are supported on the platform.
Fixes issues #2216 and #2180.

Fix shader argument buffer padding and atomics.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/Vulkan/vulkan.mm
fetchDependencies

- Add `vkGetPhysicalDevicePortabilitySubsetMissingFeaturesKHR()`.
- Log missing features when creating a physical device.

Add support for final version of VK_KHR_portability_subset extension.

---

MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm

Some context: https://github.com/KhronosGroup/MoltenVK/issues/2235.

Enforce barrier when sampling timestamps

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKBuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.mm
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

- `mvkPopulateShaderConversionConfig()` `VK_DESCRIPTOR_TYPE_STORAGE_IMAGE` and `VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER`, don't add buffer resource binding if native texture atomics are supported.
- Remove `MVKPhysicalDevice::useNativeTextureAtomics()` and update all occurrences of `getPhysicalDevice()->useNativeTextureAtomics()` to `getMetalFeatures().nativeTextureAtomics`.
Fixes issue #2180.

Fix shader conversion failure when using native texture atomics.

---

MoltenVK/MoltenVK/API/mvk_private_api.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm

Occasionally I want to capture a single GPU frame but have trouble attaching Xcode. I hacked in something of this sort several times already, so here it is cleaned up.

Added mechanism to trigger GPU capture without attaching a debugger.

---

MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

With dynamic patch control points enabled, the pipeline does not need to be created with tessellation info included in the create info. Store a separate boolean flag to treat all pipelines that have tessellation shaders properly.

MVKGraphicsPipeline: Don't use _tessInfo to decide if pipeline is a tessellation pipeline.

---

MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.h
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.mm

2 workarounds introduced:
- Fragments with side effects will now execute following Vulkan
- Depth/Stencil write postponed to post fragment execution when input attachment and depth/stencil attachment reference the same resource
Fixes #2232
Fixes #2233

Apply SPIRV-Cross workarounds for Metal bugs

---

.github/workflows/CI.yml

- Use latest macOS and default Xcode versions for primary CI environment.
- Github CI no longer supports macOS 11. Update legacy CI to macOS 12 and Xcode 13.4.1.

Update Github CI versions.

---

MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

Need to investigate failing tests:
dEQP-VK.fragment_shader_interlock.basic.discard.image.pixel_ordered.1xaa.no_sample_shading.1024x1024 and similars
Temporary fix for #2265

Revert enforcing fragments with side effects

---

MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.mm
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.h

- `MVKDescriptorSetLayoutBinding` add `getMaxPlaneCount()` to determine the number of planes for a combined image-sampler, from the immutable samplers.
- When using `MTLArgumentEncoder`, add encoder arguments for each texture plane.
- Don't build `MTLArgumentEncoder` if descriptor count is zero.
- For discrete multi-plane and multiple descriptors per binding, use max plane count to determine a consistent array size for each plane.
- Some minor formatting fixes found along the way.
Although there was some original concern in [this discussion](https://github.com/KhronosGroup/MoltenVK/pull/2260#discussion_r1663613174) that we might need to hold 3 argument buffer slots for all images if `samplerYcbcrConversion` was enabled, it turned out that this feature only permits multiplanar images as …

Support multiplanar images in Metal argument buffers.

---

Common/MVKCommonEnvironment.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVKShaderConverter/MoltenVKShaderConverterTool/OSSupport.mm

This adds a new preprocessor macro for xcode16 / ios18 sdk and reroutes the version to 3.1 (additions to MVKDevice are iline with as what we did for other xcode versions in the past)

[ios18 support] add new case for Metal Version 3.2 that is on ios 18 -- reroutes MoltenMK to use version 3.1

---

Docs/Whats_New.md
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.mm
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

Existing implementation allocated enough descriptors to cover the maximum defined by the descriptor layout binding. This used more memory than needed, and caused pool exhaustion when allocating descriptors from a smaller pool, that contains enough descriptors to cover the variable count, but not the maximum count. Descriptors are now allocated from the pool only to cover the variable quantity.
- When creating `MTLArgumentEncoder`, only add the variable number of descriptors, and fix memory leak. 
- Add buffer-sized buffer to the front of the argument buffer, instead of at the end, to give it a fixed slot for access from the shader.
- Set variable count arrays in shader to length `1`.
- `MVKDescriptorSetLayout` don't track fixed descriptor count, resource count, argument buffer encoder …

Descriptor set only consumes the variable number of descriptors from the pool.

---

MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm

As per https://github.com/KhronosGroup/MoltenVK/issues/1930#issuecomment-2089164911, adds a mapping for `VK_ATTACHMENT_STORE_OP_NONE` to `MTLStoreActionStore`, since it is required by `VK_KHR_dynamic_rendering` and storing is the closest equivalent in behavior provided by Metal. This will help silence log spam from the default case in applications that use this store op.
I assumed that it should mirror the behavior of `VK_ATTACHMENT_STORE_OP_STORE` with regards to multisampling and assigned it the same switch case. Let me know if that's not the case and I'll adjust it.

Add MTLStoreAction mapping for VK_ATTACHMENT_STORE_OP_NONE.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm

Some `VK_EXT_layer_settings` info was being read too late to have effect.
- `MVKInstance` enable extensions and set config info from `VkLayerSettingsCreateInfoEXT` before creating `MVKPhysicalDevice` instances, and before any logging.

Ensure all MoltenVK config info set by VK_EXT_layer_settings is used.

---

Docs/MoltenVK_Configuration_Parameters.md
Docs/Whats_New.md
MoltenVK/MoltenVK/API/mvk_private_api.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm
MoltenVK/MoltenVK/Utility/MVKConfigMembers.def
MoltenVK/MoltenVK/Utility/MVKEnvironment.h

- `MVKDescriptorTypePool` if the pool is exhausted, report a warning, allocate a new descriptor instance, and when it is freed, destroy it.
- Deprecate `MVKConfiguration::preallocateDescriptors` and `MVK_CONFIG_PREALLOCATE_DESCRIPTORS`, as both preallocation and dynamic allocation of descriptors are now supported.
- `vkAllocateDescriptorSets()`: Per Vulkan spec, if any descriptor set allocation fails, free any successful allocations, and populate all descriptor set pointers with `VK_NULL_HANDLE`. In addition, return `VK_ERROR_FRAGMENTED_POOL` if failure was due to Metal argument buffer fragmentation.
- `vkUpdateDescriptorSets()` accepts null `VkDescriptorSet`s as no-ops.
- `MVKDescriptorPool::getLogDescription()` include count of remaining descriptors in the pool, for diagnostic logging …

Support dynamically allocating descriptors when pool is exhausted.

---

MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm

- ~`MVKDescriptorSet::write()`: Revert to verifying each descriptor has the same type as its descriptor binding, to guard against an app mistakenly running off the end of an array of descriptors.~
- ~`MVKDescriptorSet::hasMetalArgumentBuffer()` ensure _layout is available.~
- MVKDescriptorSet::write() & read(): Refactor descriptor iteration to clarify loop indexing, and to check array limits to guard against an app mistakenly running off the end of an array of descriptors.

Add additional defensive code within vkUpdateDescriptorSets().

---

Docs/Whats_New.md
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

Move primitive-restart-disabled warning from renderpass to pipeline creation, to reduce voluminous log noise.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.mm
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

On iOS GPUs with Tier1 argument buffer support, Metal does not support writable textures in argument buffers. MoltenVK and SPIRV-Cross were addressing this differently.
- Set `CompilerMSL::Options::ArgumentBuffersTier` to align behaviour between MoltenVK and SPIRV-Cross.
- On iOS Tier1 GPUs, if a descriptor set contains a storage image, don't use a Metal argument buffer for that descriptor set.

iOS: Support storage images in Metal argument buffers.

---

MoltenVK/MoltenVK/GPUObjects/MVKQueue.h
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm

That seems to be causing mysterious crashes with asynchronous queue submissions. I've been debugging one where it'd crash the encoding thread because we destroyed the swap chain right after calling `vkQueueWaitIdle`, and it wasn't done encoding the Present.
For what it's worth in my case the bug bisected to f0cb31a12b59f05177f07ab5a46bc9084ba5fbc9.
Ping #2295, possibly others..

MVKQueue: Make sure waitIdle waits for all commands to be encoded before enqueuing its own waitUntilCompleted.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/Commands/MVKMTLBufferAllocation.mm
MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.mm
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm

- Revert to allowing `vkUpdateDescriptorSets()` to write or copy beyond the end of a descriptor binding count if subsequent descriptors are of the same type. This fixes a regression caused by 7fe7423 in PR #2293, that added a guard against writing or copying past a descriptor binding size.
- Add `MVKInlineUniformBlockDescriptor::writeBytes()` & `readBytes()` to support updating byte contents, and allow `vkUpdateDescriptorSets()` to break a write or copy of a large byte range into multiple inline uniform block descriptors of smaller size.

Support Vulkan requirement to allow write or copy beyond descriptor binding size.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKFramebuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.h
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

- Add `MVKMTLDeviceCapabilities` to encapsulate Metal GPU family capabilities, and use it in `MVKPhysicalDevice` and `MVKPixelFormats` to identify GPU capabilities.
- Remove all references to `MTLGPUFamily` and `MTLFeatureSet` outside `MVKMTLDeviceCapabilities`.
- Blend or select AppleGPU and MacGPU format capabilities.
- Simplify `MVKPixelFormats::modifyMTLFormatCapabilities()` based on `MVKMTLDeviceCapabilities`.
- Add guard code to ensure `MTLPixelFormatInvalid` & `MTLVertexFormatInvalid` capabilities are not overwritten by other formats that don't exist on some platforms.
- Update `MTLPixelFormat` capabilities based on latest Metal docs.
- Remove some variations tied to very older OS versions, or `MTLFeatureSets` that have the same GPU family, including setting MSL 2.0 as the earliest …

Refactor defining MTLPixelFormat and GPU capabilities.

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.mm
MoltenVK/MoltenVK/GPUObjects/MVKBuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKDeviceMemory.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueryPool.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm
MoltenVK/MoltenVK/GPUObjects/MVKShaderModule.mm
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm
MoltenVK/MoltenVK/GPUObjects/MVKVulkanAPIObject.h
MoltenVK/MoltenVK/GPUObjects/MVKVulkanAPIObject.mm
MoltenVK/MoltenVK/OS/MVKGPUCapture.mm
MoltenVK/MoltenVK/Vulkan/vulkan.mm
MoltenVKShaderConverter/MoltenVKShaderConverterTool/OSSupport.mm

- On GPU error, log indicate whether device has been resumed or lost, and report as either warning or error, respectively.
- On `VkDevice` loss, stop device-scope GPU capture.
- In debug mode, include address of Metal object in Metal object label.
- Replace `setLabelIfNotNil()` with `setMetalObjectLabel()` and move inside `MVKVulkanAPIObject` to allow access to config info.
- When logging contents of `MVKDescriptorPool`, only list descriptor types with allocations.
- Add `@autoreleasepool` around complex `NSString` creation.
Expansion and replacement of PR #2305.

Minor debugging enhancements.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

- Retain `MVKImage` in `MVKImageView`.
- Fixes issue #2206.

Fix race condition when VkImage destroyed while used by descriptor.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVKShaderConverter/MoltenVKShaderConverter.xcodeproj/xcshareddata/xcschemes/MoltenVKShaderConverter.xcscheme

- Fix build failure on VisionOS 2.0 platform.
- Restore `MoltenVKShaderConverter` scheme runtime arguments.
Fixes #2322.

Misc small fixes.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/Commands/MVKCmdPipeline.h
MoltenVK/MoltenVK/Commands/MVKCmdPipeline.mm
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm
MoltenVK/MoltenVK/Utility/MVKFoundation.h
MoltenVK/MoltenVK/Vulkan/vulkan.mm

- Fix crash when entries in `VkDescriptorUpdateTemplateCreateInfo` are not sorted by offset.
- `MVKCmdPushDescriptorSetWithTemplate` allocate new data memory only if existing memory allocation is too small.
- `mvkCopy()` support void pointers, and copy a single value directly.
Fixes issue #2323.

Fixes to vkCmdPushDescriptorSetWithTemplateKHR().

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

The Apple documentation is ambiguous on exactly when these formats were added to iOS and tvOS, but it was sometime around tvOS 11. They are definitely available in iOS/tvOS 13+.

Add support for RGB10A2Unorm and BGR10A2Unorm formats on ios/tvos

---

MoltenVK/MoltenVK.xcodeproj/project.pbxproj
MoltenVK/MoltenVK/Commands/MVKCommandPipelineStateFactoryShaderSource.h

Two parts:
* SPIRV-Cross uses std::stable_sort, and on tvOS using the new linker, this causes a crash: https://forums.developer.apple.com/forums/thread/742470. A workaround is to use the old linker with the flag `-ld_classic`.
* #2132 causes compilation problems on tvOS 13 because `texture2d_ms_array` is not available.

Fixes to enable running on tvOS 13

---

Docs/MoltenVK_Configuration_Parameters.md
Docs/Whats_New.md
MoltenVK/MoltenVK/API/mvk_private_api.h
MoltenVK/MoltenVK/GPUObjects/MVKShaderModule.mm
MoltenVK/MoltenVK/Utility/MVKConfigMembers.def
MoltenVK/MoltenVK/Utility/MVKEnvironment.h

Logging estimated GLSL shader code by default clutters the log with info that is not necessarily helpful, and it can occasionally result in a crash during the generation of GLSL, even though the MSL is correctly generated.
- Add `MVKConfiguration::shaderLogEstimatedGLSL`, and environment variable `MVK_CONFIG_SHADER_LOG_ESTIMATED_GLSL`, to enable or disable the logging of estimated GLSL code, and disable it by default.
- Clean up alphabetic order of `MoltenVK_Configuration_Parameters.md` doc.

Support disabling logging GLSL shader code during shader conversion logging.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.mm
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm

- `MVKDescriptorSetLayout`: Test for iOS & tvOS Tier 1 storage images in any binding before construction of `MVKDescriptorSetLayoutBindings`.
Fixes issue #2329.

Fix shader conversion failure when using storage images

---

fetchDependencies

fetchDependencies can loop forever without any feedback to the user when leading `-` are missing.
Detected when running `./fetchDependencies macos` which is of course incorrect.
This is fixed by widening the wildcard for unsupported options.

Improve fetchDependencies

---

MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h

- Make `MVKPhysicalDevice::getCurrentAllocatedSize()` and various `getLogDescription()` functions public so they can be accessed everywhere during debugging.
- `MVKDescriptorPool::getLogDescription()` add indication of whether descriptor sets can be individually freed.

Misc minor debug logging improvements.

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

Fix leak where texel buffer is occasionally accidentally created during image-memory unbinding (#2341)

---

MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm
MoltenVK/MoltenVK/Utility/MVKBitArray.h

If a descriptor set with fewer than 64 descriptors replaced one with more, the resources it contained were not made resident to the GPU, due to `MVKBitArray` thrashing incorrectly when transitioning between static and dynamic memory allocations.
- Overhaul `MVKBitArray` design:
- Never downsize memory allocation unless `reset()` is called.
- No longer support static allocation for smaller sizes, to avoid thrashing between dynamic and static allocs when frequently resizing up and down.
- Use `realloc()` instead of malloc/copy to improve performance.
- Simplify tracking of partially and fully disabled sections.
- Rename `setXX()` and `clearXX()` functions to `enableXX()` & `disableXX()`.
- Rename several internal functions.
- `getIndexOfFirstEnabledBit()` & `enumerateEnabledBits()` no …

Fix occasional GPU crash when a smaller descriptor set replaces a larger one.

---

MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm

Vulkan permits `VkDescriptorSetLayout` to be destroyed while descriptor set is in use, as long as `vkUpdateDescriptorSets()` is not called.
- `MVKDescriptorSet` retain() layout on allocation, and release() it on free.
Fixes #2356.

Fix crash when VkDescriptorSetLayout is destroyed while descriptor set is in use.

---

.github/workflows/CI.yml

- Update deprecated `CI.yml` action versions to latest versions.

Fix GitHub CI release action failure to publish artifacts.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

A super basic cleanup, caught by enabling `-Wunused-but-set-variable` in clang.

Fix set, but never read variable within MVKDevice::getFirstViewIndexInMetalPass.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm

- Replace hardcoded reference to `MVK_spirv_cross` with `SPIRV_CROSS_NAMESPACE`.
Fixes #2365.

Fix SPIRV-Cross namespace build error on some alternate build environments.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

Defines certain unsupported Metal Pixel formats as invalid for the iOS/tvOS Simulator.  Fixes #2353 for MoltenVK 1.2.11.
I have tested this on an x86_64 host using Xcode 15.2 with the iOS Simulator (running iOS 17.2).  I can't test on tvOS so I would appreciate others (@warmenhoven) checking out this scenario.
Also, I am not sure whether the `#ifdef` condition should also contain an Xcode version test.  Perhaps @cdavis5e could weigh in on that aspect.  Thanks.

Disable unsupported Metal Pixel formats for iOS/tvOS Simulator

---

MoltenVK/MoltenVK/Utility/MVKBitArray.h

In some conditions the bit array ends up fetching a section that doesn't exist, one past the end of the array.

Fix a crash when searching the first enabled bit in a completely disabled bit array

---

MoltenVK/MoltenVK.xcodeproj/project.pbxproj
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
MoltenVK/MoltenVK/GPUObjects/MVKShaderModule.h
MoltenVK/MoltenVK/GPUObjects/MVKShaderModule.mm

This removes `using namespace ...;` from headers, as such reducing header namespace pollution.
Whilst not critical for MoltenVK itself, when incorporated in a larger project makes sure that symbols/functionality is addressed appropriately and items within `mvk` namespace aren't considered to be part of the global namespace.
Also enabled the warning within xcodeproj, so it's visible when this is added again.

Fix header namespace pollution.

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

Adds support for `VK_FORMAT_B5G6R5_UNORM_PACK16` and `VK_FORMAT_B5G5R5A1_UNORM_PACK16` using swizzles, same as how 4444 format variations are supported.
These formats are pretty broadly supported elsewhere, so it's helpful to have support for them out-of-the-box on Apple systems as well.

MVKPixelFormats: Add support for B5G6R5_UNORM_PACK16 and B5G5R5A1_UNORM_PACK16 using swizzle.

---

MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.mm
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

- Add support for passing an indent value to `getLogDescription()`.
- `MVKPipelineLayout::getLogDescription()` log descriptions of descriptor set layouts.

When logging a pipeline layout, log contained descriptor set layouts.

---

MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.h
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm
MoltenVK/MoltenVK/Utility/MVKBitArray.h

- Fix regression in `MVKBitArray::getIndexOfFirstEnabledBit()` that didn't continue searching beyond the initial start section.
- After freeing the last descriptor set in Metal argument buffer, support replacing it with a longer descriptor set.
- `MVKMetalArgumentBuffer` track encoded size of descriptor set.
- `MVKDescriptorPool`: Determine the offset of allocated space in argument buffer for a descriptor set from the previous descriptor set allocation, instead of using a separate member variable.
Replaces PR #2388.

Fixes to managing descriptor set allocation in a Metal argument buffer.

---

MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm

https://github.com/KhronosGroup/MoltenVK/issues/2399
Fix memory management issue in MVKSwapchain

fix memory management issue in MVKSwapchain

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

Similar to https://github.com/KhronosGroup/MoltenVK/pull/2383, adds support for some more B8G8R8A8 formats using swizzle.
I've tested this with B8G8R8A8 storage images in [shadPS4](https://github.com/shadps4-emu/shadPS4). We don't have proper support for emulating arbitrary storage image swizzles used by the emulated game yet, but we have a simple path for emulating RGBA -> BGRA storage image swizzles that changes out the Vulkan format. Adding these formats helps us with that.

MVKPixelFormats: Add support for more B8G8R8A8 formats using swizzle.

---

MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

macOS 10.15's AMD driver is broken and crashes if you try to encode a `sampleCountersInBuffer:` to a blit command encoder before encoding any actual work.

Work around 10.15 AMD driver's broken blit encoder timestamp sampling

---

.github/workflows/CI.yml

macOS 12 runners are gone: https://github.com/actions/runner-images/issues/10721

GHActions: Update legacy build to macOS 13 / Xcode 14

---

MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

Ran into this while testing with a local compile. In `MVKPipeline.mm`, it seems that with `MVK_USE_CEREAL=0`, `sstream` is not included, but `stringstream` is used.

Fix compile with MVK_USE_CEREAL=0

---

MoltenVK/MoltenVK/GPUObjects/MVKBuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

Looking into https://github.com/KhronosGroup/MoltenVK/issues/2414, it appears that 64-bit atomics for RG32 texture is not supported by Vulkan at this time, and code for it was only added to prepare for if it is in the future.
However, marking every texture with this format as atomic not only could have performance implications, it is also causing issues on devices like M1 family GPUs that support native texture atomics but not 64-bit atomics. Thus it is better to remove it and revisit if Vulkan ever does decide to support this.
I left the part enabling MTLPixFmtCaps as it already has a flag to force-disable it since it isn't supported by Vulkan along with a comment explaining, and thus it seems pretty harmless. Although I removed enabling it on `RG32Sint` as according to the spec Metal …

Remove atomic usage for RG32Uint.

---

MoltenVK/MoltenVK/Commands/MVKCmdDraw.mm

When we call vkCmdDraw with vertexCount=N and firstVertex=X, we only need an array with N element, X, X+1, ..., X+N-1, to generate the indirect indices. However, the current logic generates all the way from 0 to X+N-1 (which is X+N elements) while only reserving N spaces. This causes issue when the unreserved part is overwritten, for example, when issuing consecutive draw calls with triangle fan primitives.
Fixes #2418

MVKCmdDraw: Fix indirect index for triangle fan topology

---

MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

I didn't get any feedback on https://github.com/KhronosGroup/MoltenVK/issues/2416 whether this would be an acceptable fix, so I'm opening it as a PR in case it's wanted.
Basically it seems that for some reason when Metal shader validation is enabled, there may be a crash due to auto-release pool double-release on an `MTLComputePipelineDescriptorInternal`, but only when using `newComputePipelineStateWithFunction`. I'm not sure why this is happening or whether it's an internal Metal bug with the validation layer or MoltenVK's fault, but changing it to create a temporary `MTLComputePipelineDescriptor` and call `newComputePipelineStateWithDescriptor` resolves the issue for me.

Fix crash when shader validation is enabled.

---

MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

* Checks if any descriptor set layouts bound to a pipeline layout are actually using argument buffers before reserving any indices to bind them.
* Reduces the number of reserved indices for argument buffers to only the number of descriptor sets.
I was hitting limits on number of bind indices available because a fixed 8 are always reserved for argument buffers, even with only a single descriptor set using push descriptors (which do not use argument buffers). Mainly when tessellation is involved, it was unable to reserve indices for the output buffer.
Please let me know if there's anything I'm missing with this approach, I tested it in my application both as-is and with push descriptors disabled, and it seems to work fine.
Side note: It may be worth modifying the `maxPushDescriptors` …

Reduce number of unused pipeline bindings reserved for argument buffers.

---

MoltenVK/MoltenVK/Commands/MVKCommandBuffer.h
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm

Updates the compute-based vertex shader path for tessellation to take into account the dynamic vertex binding stride, when enabled for the pipeline, in the same fashion as regular vertex bindings.
Fixes https://github.com/KhronosGroup/MoltenVK/issues/2428

Fix dynamic vertex stride with tessellation.

---

Docs/MoltenVK_Runtime_UserGuide.md
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
MoltenVK/MoltenVK/Layers/MVKExtensions.def
MoltenVKShaderConverter/MoltenVKShaderConverter/SPIRVToMSLConverter.cpp
MoltenVKShaderConverter/MoltenVKShaderConverter/SPIRVToMSLConverter.h

SPIRV-Cross already has a flag for converting from `[-w, w]` depth to `[0, w]`. Take advantage of that to implement `VK_EXT_depth_clip_control`.
Ran CTS tests `dEQP-VK.pipeline.monolithic.depth.depth_clip_control.*`, results:
```
Test run totals:
Passed:        36/72 (50.0%)
Failed:        0/72 (0.0%)
Not supported: 36/72 (50.0%)
Warnings:      0/72 (0.0%)
Waived:        0/72 (0.0%)
```
With the general case for `Not supported` just being tests using unsupported depth formats.

Add support for VK_EXT_depth_clip_control

---

MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

Small fix pointed out in https://github.com/KhronosGroup/MoltenVK/pull/2430#issuecomment-2621122639; need to add `shouldFixupClipSpace` option to pipeline serialization.

Fix not saving shouldFixupClipSpace when serializing a pipeline.

---

MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

Currently, the vertex attribute buffer count estimation (to reserve binding for implicit buffers) is too generous. This merge request improves the estimation by introducing one case from the actual allocation logic, `addVertexInputToPipeline`, i.e., synthetic binding buffer if the vertex attribute offset is 0. This helps in reducing the required binding slots the majority of pipelines generated by ANGLE and allows vertex shaders that uses more than 10 attribute inputs to work.
In the meantime, the change brings bindings of implicit buffers and vertex attributes into close vicinity, and exposes a bug where implicit buffer interferes with vertex attribute at the same binding index across draw calls in the same render pass. This is masked by the previous over-conservative estimation. The …

Improved estimation of vertex attribute buffer count when reserving for implicit buffer

---

MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm

This is a followup of #2400. `CAEDRMetadata` is a type that has internal use of `autorelease`. As there is no other alternatives, wrap its usage in an `@autoreleasepool {...}` block instead of doing explict release, which would cause segfaults from double release.

Autorelease CAEDRMetadata in MVKSwapchain

---

Docs/MoltenVK_Runtime_UserGuide.md
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKDeviceFeatureStructs.def
MoltenVK/MoltenVK/Layers/MVKExtensions.def

`OpTerminateInvocation` is already handled in SPIRV-Cross identically to `OpKill`. Advertise support for the extension.

Advertise VK_KHR_shader_terminate_invocation.

---

MoltenVK/MoltenVK/API/mvk_datatypes.h
MoltenVK/MoltenVK/API/mvk_private_api.h
MoltenVK/MoltenVK/Commands/MVKCmdPipeline.mm
MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.h
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/Commands/MVKMTLBufferAllocation.mm
MoltenVK/MoltenVK/GPUObjects/MVKBuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKDeviceMemory.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm

This PR implements execution barriers with Metal fences and puts all resources in a residency set to avoid having to useResource all resources in bound argument buffers. That makes it possible to run programs that use descriptor indexing with large descriptor tables efficiently.
Consider a pipeline executing some render passes with a couple vertex to fragment barriers:
```
1 2   3 4   5 6
v v B v v B v v
f f B f f B f f
```
Here `v` and `f` symbolize the vertex and fragment stages of a render pass, and `B` stands for the barrier.
In this example, stages `v1` and `v2` need to run before `f3..6`, and `v1..4` before `f5` and `f6`.
To implement this I maintain a set of fences that will be waited on before each stage, and updated after it. Here's a diagram with the fences `a` and `b` placed …

Avoid calling useResource on resources in argument buffers

---

MoltenVK/MoltenVK/Commands/MVKCmdDraw.mm
MoltenVK/MoltenVK/Commands/MVKCmdPipeline.mm
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.h
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm

May improve performance in some cases although it didn't do much to the game I was writing this for.

Use concurrent compute command encoders.

---

Docs/MoltenVK_Runtime_UserGuide.md
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/Layers/MVKExtensions.def
MoltenVK/MoltenVK/Vulkan/vulkan.mm

Implements basic support for `VK_EXT_tooling_info`.
Everything is wired up for the `MVKPhysicalDevice` to provide tool properties, but it currently just returns that there are no tools, since (as far as I can tell) Metal does not have a standard way of reporting any attached tools on the Metal side of things. However, with support now advertised, applications can now properly detect support and get information on Vulkan-side tools from the Vulkan loader in the middle, such as the Vulkan Validation Layers if attached.
Passes both available CTS tests `dEQP-VK.api.tooling_info.validate_getter` and `dEQP-VK.api.tooling_info.validate_tools_properties`.

Implement basic support for VK_EXT_tooling_info.

---

MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm

PR #2435 implemented `VK_EXT_tooling_info` using the existing entry-point definition of `vkGetPhysicalDeviceToolProperties`, but missed that the entry point had previously been misclassified as an instance entry-point instead of a device entry-point. According to [the spec](https://registry.khronos.org/vulkan/specs/latest/man/html/VK_EXT_tooling_info.html), as well as the extension definition in MoltenVK, it is a device extension, not an instance extension.
This PR fixes the issue by re-classifying as a device entry-point. It also happens to fix that it was being added with a KHR suffix instead of EXT. I seem to have missed this as it only causes problems when linking with MoltenVK directly without the `libvulkan` loader.

Properly designate vkGetPhysicalDeviceToolProperties as a device entry-point.

---

MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

Fixes regression introduced in #2430.

Ignore allowed bad pViewportState pointer if rasterization is disabled.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm

MTLCommandQueues are shared, we need to clean up so that we don't leak and hit the limit of residency sets per queue.
Supersedes #2448 
Fixes issue #2444.

MVKQueue: Remove residency set from MTLCommandQueue on destruction.

---

MoltenVK/MoltenVK/Commands/MVKCmdDraw.mm
MoltenVK/MoltenVK/Commands/MVKCmdPipeline.mm
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.h
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm

This reverts commit 835f85ecfed65bf660fd2d15a543e2c4ae2258f6.
This addresses concerns raised in #2458 regarding breakage on AMD GPUs, until such time as a replacement PR can be developed that works on both M-series GPUs and AMD GPUs.
This PR tested on my AMD 6600 GPU as working properly again using Sascha Willems' _computecloth_ example.
Fixes #2458.

Revert "Use concurrent compute command encoders."

---

MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

Partially reverts https://github.com/KhronosGroup/MoltenVK/pull/2417, restoring fixed argument buffer reservation count but only when argument buffers are used by any descriptor set.
I've found that this seems to break the "compatible for set N" rule when push constants are used and the application relies on not having to re-push them after changing pipelines. I got in a situation where, when a pipeline with N + 1 descriptor sets is followed later by pipelines with N descriptor sets, something with the way buffer bindings dirty state works for layout compatibility may end up re-binding that N + 1 argument buffer into the push constants slot that is now at N + 1. Then, since the push constants are not re-pushed, they are not updated by MoltenVK back into that slot. I think that reserving …

Revert to fixed number of argument buffer binding reservations.

---

MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm

Texture view creation is not allowed from `framebufferOnly` textures. The flag should be disabled if texture view will be created from it.
Related: https://github.com/KhronosGroup/MoltenVK/issues/2261

Fix Metal API violation when using VK_KHR_swapchain_mutable_format.

---

Docs/MoltenVK_Configuration_Parameters.md
Docs/MoltenVK_Runtime_UserGuide.md
MoltenVK/MoltenVK/Utility/MVKEnvironment.h

- Enable `MVK_CONFIG_USE_MTLHEAP` by default to support `VK_EXT_image_2d_view_of_3d`.
- Alphabetize position of `VK_EXT_external_memory_metal` in `MoltenVK_Runtime_UserGuide.md` (unrelated).

Enable MVK_CONFIG_USE_MTLHEAP by default to support VK_EXT_image_2d_view_of_3d

---

MoltenVK/MoltenVK/GPUObjects/MVKBuffer.h
MoltenVK/MoltenVK/GPUObjects/MVKBuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/Vulkan/vulkan.mm

- `MVKImage::getMemoryRequirements()` fix access to memory bindings.
- Fix parameter declarations of `getMemoryRequirements()` on `MVKImageMemoryBinding`, `MVKImage`, and `MVKBuffer`.
- Use inline allocation for temp `MVKImage` in `vkGetDeviceImageMemoryRequirements()` and temp `MVKBuffer` in `vkGetDeviceBufferMemoryRequirements()`.

Fix crash on vkGetDeviceImageMemoryRequirements().

---

MoltenVK/MoltenVK/GPUObjects/MVKShaderModule.mm
MoltenVKShaderConverter/MoltenVKShaderConverter/SPIRVToMSLConverter.cpp

- When shader specifies both `WorkgroupSize` builtin and `LocalSizeId`, the builtin takes precedence.

Fix failure when shader specifies both LocalSizeId and workgroup size builtin.

---

MoltenVK/MoltenVK/GPUObjects/MVKDeviceMemory.mm

MTLHeaps on Apple Device Simulator must use private storage

---

MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.mm

Reverts part of https://github.com/KhronosGroup/MoltenVK/pull/2273 that set variable length arrays in argument buffers to size 1 in shaders.
This seems to be the cause behind various recent issues with argument buffers (https://github.com/KhronosGroup/MoltenVK/issues/2480, https://github.com/KhronosGroup/MoltenVK/issues/2453, probably https://github.com/KhronosGroup/MoltenVK/issues/2300). It seems that using an array of size 1 for variable length arrays may have been partially broken before, and is now completely broken as of macOS 15.4 on M1 and M2 systems. I verified on M1 myself that with this partial revert in place, my application works perfectly instead of immediately hitting a GPU page fault, and that it still works fine on M4.
As I understand, this may trigger some Metal …

Revert use of size 1 for variable length arrays in shader.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm
MoltenVK/MoltenVK/Layers/MVKExtensions.mm
MoltenVK/MoltenVK/Vulkan/vulkan.mm

Allow the proc address of vkGetMoltenVKConfigurationMVK() to be retrieved before a VkInstance has been created.

---

Docs/MoltenVK_Runtime_UserGuide.md
Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKDeviceFeatureStructs.def
MoltenVK/MoltenVK/Layers/MVKExtensions.def

Adds support for the `VK_KHR_shader_expect_assume` extension, which is required for [Vulkan 1.4](https://github.com/KhronosGroup/MoltenVK/issues/2490). Tbh I haven't tested this at runtime yet, but it compiles :sparkles:
See https://github.com/KhronosGroup/SPIRV-Cross/pull/2466

Support for KHR_shader_expect_assume

---

Docs/MoltenVK_Runtime_UserGuide.md
Docs/Whats_New.md
MoltenVK/MoltenVK/Commands/MVKCmdDraw.mm
MoltenVK/MoltenVK/GPUObjects/MVKBuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKDeviceFeatureStructs.def
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKInstance.h
MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm
MoltenVK/MoltenVK/Layers/MVKExtensions.def
MoltenVK/MoltenVK/Vulkan/vulkan.mm

Adds `VK_KHR_maintenance6`, required for Vulkan 1.4 (https://github.com/KhronosGroup/MoltenVK/issues/2490).
List of changes:
* [VkBindMemoryStatusKHR](https://registry.khronos.org/vulkan/specs/latest/man/html/VkBindMemoryStatusKHR.html) may be included in the pNext chain of [VkBindBufferMemoryInfo](https://registry.khronos.org/vulkan/specs/latest/man/html/VkBindBufferMemoryInfo.html) and [VkBindImageMemoryInfo](https://registry.khronos.org/vulkan/specs/latest/man/html/VkBindImageMemoryInfo.html), allowing applications to identify individual resources for which memory binding failed during calls to [vkBindBufferMemory2](https://registry.khronos.org/vulkan/specs/latest/man/html/vkBindBufferMemory2.html) and [vkBindImageMemory2](https://registry.khronos.org/vulkan/specs/latest/man/html/vkBind …

Add support for VK_KHR_maintenance6

---

Docs/MoltenVK_Runtime_UserGuide.md
Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKDeviceFeatureStructs.def
MoltenVK/MoltenVK/Layers/MVKExtensions.def

Adds VK_KHR_maintenance7, containing the following:
* Add a property query to determine if a framebuffer writes to depth or stencil aspect does not trigger a write access in the sibling aspect. For example, this allows sampling stencil aspect as a texture while rendering to the sibling depth attachment and vice-versa given appropriate image layouts.
* `true`, as this seems to be the case and CTS tests reflect that.
* Add a way to query information regarding the underlying devices in environments where the Vulkan implementation is provided through layered implementations. For example, running on Mesa/Venus, driver ID is returned as VK_DRIVER_ID_MESA_VENUS, but it can be necessary to know what the real driver under the hood is. The new …

Add support for VK_KHR_maintenance7

---

Docs/MoltenVK_Configuration_Parameters.md
Docs/MoltenVK_Runtime_UserGuide.md
Docs/Whats_New.md
MoltenVK/MoltenVK/API/mvk_private_api.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/Utility/MVKConfigMembers.def
MoltenVK/MoltenVK/Utility/MVKEnvironment.h

- Convert `MVK_CONFIG_USE_MTLHEAP` and `MVKConfiguration::useMTLHeap` to enumeration and add `MVK_CONFIG_USE_MTLHEAP_WHERE_SAFE` option.
- Use `MTLHeap` by default, except on _AMD_ devices.
Completes #2475.

Disable MVK_CONFIG_USE_MTLHEAP for AMD devices by default.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

- Add and use macro to enable extension features from promoted features structs.
- Rename Vulkan 1.2 feature structs to allow macro to work on them.

MVKDevice refactor enabling promoted physical device features.

---

MoltenVK/MoltenVK/GPUObjects/MVKInstance.h
MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm

Multi-extension configuration on proc-addrs really wasn't doing what it was being used for. It really only had once specialized purpose, so it's been removed it altogether. The specialized device group functions support is now handled more explicitly with a clean test for existence of a function either within a version or extension.
- Remove multi-extension testing when determine function support.
- Ensure entry point API version is set before comparing it.
- Add the ability to test the special case of an extension function in core, or an extension, under the same function name (promoted but not renamed).

Cleanup MVKInstance proc-addr function mapping.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/mvk_deprecated_api.h
MoltenVK/MoltenVK/API/mvk_private_api.h
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm
MoltenVK/MoltenVK/Layers/MVKExtensions.mm
MoltenVK/MoltenVK/Utility/MVKEnvironment.h

Several proc addr for `VK_MVK_moltenvk` extension functions were erroneously hidden by commit 70db7651.
- Handle the proc addrs for functions `vkGetPhysicalDeviceMetalFeaturesMVK()`, `vkGetPerformanceStatisticsMVK()`, and `vkSetMoltenVKConfigurationMVK()` consistently with all other functions, by replacing these functions under the `VK_MVK_moltenvk` extension, and requiring that extension to be enabled to use the functions.
- Remove `ADD_INST_OPEN_ENTRY_POINT()` and `ADD_DVC_OPEN_ENTRY_POINT()` macros.
- Improve warning message output when extension `VK_MVK_moltenvk` is enabled.
Completes #2532.
@SRSaunders  I put the previously un-categorized functions under `VK_MVK_moltenvk`, where they started out. This makes them like any other extension functions, to avoid the special-case situation …

Re-expose proc addr for VK_MVK_moltenvk extension functions.

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.h
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm

Encountered an issue using present wait in practice in [Unleashed Recompiled](https://github.com/hedge-dev/UnleashedRecomp), where when v-sync is enabled the present wait would take too long and severely disrupt frame pacing.
While looking into it I noticed a section near the present handler logic where we signal the present fence in a separate completed handler, because the present handler callbacks can possibly stall. Indeed, moving the logic to notify the swapchain to update the present ID seems to have solved my issues; I went from having wild fluctuations around 9ms for present waits for `currentPresentId - 1` to around a microsecond. I also verified with timestamps that the completed handler is paced correctly, rather than just seeing the results I expect due to it calling very …

Fix high latency on present wait.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

- Update Cereal Archive for `CompilerMSL::Options` to fix cache misses.
- Add validation functions to report if Cereal Archive definitions deviate from struct definitions in the future.
- Replace unused variable warning suppression with `[[maybe_unused]]` compilation attribute (unrelated).
Fixes part of #2547.

Fix shader cache misses within pipeline cache.

---

Common/MVKCommonEnvironment.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/Utility/MVKCodec.h
MoltenVKShaderConverter/MoltenVKShaderConverterTool/OSSupport.mm

* Adds `MVK_XCODE_26` for Xcode 26.
* Adds necessary code to use `MTLLanguageVersion4_0` when supported.
* Fixes a missing include in `MVKCodec.h` for using `std::unique_ptr`.
* Minor fixes to whitespace consistency around these changes.

Support compiling using Xcode 26

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

Luckily, I know this one was actually fixed; this doesn't happen after 10.15.
While I'm at it, put all the known RDNA device IDs into a single function, and call it from both the subgroup size code and the zombie counter set hack. This should also correct the minimum subgroup size for those GPUs.

MVKDevice: Also apply zombie counter set workaround to AMD RDNA devices.

---

MoltenVK/MoltenVK/GPUObjects/MVKInstance.h
MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm

I know, I know, but it turns out the spec really does require this, and the CTS _enforces_ it.
Add some more, hopefully improved comments explaining all this so that well-meaning reformers don't try to remove it again.
Fixes the `dEQP-VK.api.get_device_proc_addr.non_enabled` test.

MVKInstance: Go back to checking two extensions for some entry points.

---

MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.h
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.mm

Fixes:
```
dEQP-VK.pipeline.monolithic.stencil.no_stencil_att.dynamic_rendering.static_enable.d32_sfloat_s8_uint
dEQP-VK.pipeline.monolithic.stencil.no_stencil_att.dynamic_rendering.dynamic_enable.d32_sfloat_s8_uint
```
And should fix https://github.com/KhronosGroup/MoltenVK/issues/2412
The depth attachment is not supposed to automatically be used for stencil, and vice-versa. I'm not sure what exactly this logic was intended to handle originally but it is invalid behavior for Vulkan. Plus it was actually causing Metal validation errors; if you have a depth-stencil formatted image for the depth attachment, a null stencil attachment, and the corresponding depth format and `UNDEFINED` stencil format in the pipeline, you would get this:
```
-[MTLDebugRenderCommandEncoder …
```

Do not attempt to use dynamic depth/stencil attachment for alternate purpose.

---

MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.mm

https://github.com/KhronosGroup/MoltenVK/blob/48d5cfbf25c0d98e6337522b9a17472351731b2a/MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.mm#L795-L801
Attachment will be always loaded regardless of its specified loadOp, if it is not the first use at the subpass.
https://github.com/KhronosGroup/MoltenVK/blob/48d5cfbf25c0d98e6337522b9a17472351731b2a/MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.mm#L882-L888
If the render pass is using multiview, whether the attachment image is first used or not is determined by `MVKAttachmentDescription::_firstUseViewMasks`, by accessing the `subpass->_subpassIndex`-th element.
https://github.com/KhronosGroup/MoltenVK/blob/48d5cfbf25c0d98e6337522b9a17472351731b2a/MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.mm#L945-L984
`MVKAttachmentDescription::_firstUseViewMasks` is …

Fix out-of-bound access when using multiview with multiple subpasses.

---

MoltenVK/MoltenVK/GPUObjects/MVKBuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

When handling `VkExternalMemoryBufferCreateInfo`/`VkExternalMemoryImageCreateInfo`, properly handle and succeed on host memory types, since we support `VK_EXT_external_memory_host`.
I've refactored the logic here to be more straightforward. It now does a simple check up-front for supported `handleTypes`, then just uses `handleTypes` to perform the previously duplicated logic once.
Fixes https://github.com/KhronosGroup/MoltenVK/issues/2619, and passes relevant CTS tests:
```
dEQP-VK.memory.external_memory_host.*
dEQP-VK.api.external.memory.mtlbuffer.*
dEQP-VK.api.external.memory.mtltexture.*
Test run totals:
Passed:        40/63 (63.5%)
Failed:        0/63 (0.0%)
Not supported: 23/63 (36.5%)
Warnings:      0/63 (0.0%)
Waived:        0/63 (0.0%)
```

Fix VkExternalMemory*CreateInfo not allowing host memory handle types.

---

Docs/MoltenVK_Configuration_Parameters.md
Docs/Whats_New.md
Makefile
MoltenVK/MoltenVK.xcodeproj/project.pbxproj
MoltenVK/MoltenVK/API/mvk_private_api.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
README.md

- ~Update to latest SPIRV-Cross version.~
- Disable Mac Catalyst builds from all and all-debug in Makefile, due to unresolved issues with Mac Catalyst builds (see issue #2626).
- Disable numerous deprecation warnings in visionos builds.
- Remove references to deprecated `MTLFeatureSet`.
- Remove `MVK_CONFIG_SUPPORT_LARGE_QUERY_POOLS` from `MoltenVK_Configuration_Parameters.md` document.
- Update `Whats_New.md` document.

Miscellaneous build and documentation updates.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

Adds a base GPU family of `Apple9` for `samplerMipLodBias` support.
Testing has revealed that it does not function correctly on `Apple7` (e.g. M1) GPUs. I have confirmed it works on `Apple9`, but do not have an `Apple8` device to test, so I have left that as a TODO item. If anyone can test CTS for this on `Apple8`, I can update the support requirement.
On M4:
```
./deqp-vk --deqp-case="dEQP-VK.pipeline.monolithic.sampler.*.lod.*"
Test run totals:
Passed:        4865/6244 (77.9%)
Failed:        0/6244 (0.0%)
Not supported: 1379/6244 (22.1%)
Warnings:      0/6244 (0.0%)
Waived:        0/6244 (0.0%)
```

Add base GPU family for samplerMipLodBias support.
