KhronosGroup/MoltenVK

README.md

Update ThirdPartyConfig.md markdown link

---

.travis.yml
README.md

Add a basic `.travis-ci.yml` that builds MoltenVK

Add CI support using Travis CI

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
README.md

Fix issues #64 & #97.

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.h
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.h
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.mm
MoltenVK/MoltenVK/GPUObjects/MVKShaderModule.h
MoltenVK/MoltenVK/GPUObjects/MVKShaderModule.mm
MoltenVK/MoltenVK/Utility/MVKFoundation.h

Clearing multisampled textures + minor fix to depth clip mode handling.

---

Docs/MoltenVK_Runtime_UserGuide.md

Fix typo in MoltenVK_Runtime_UserGuide.md

Fix typo in MoltenVK_Runtime_UserGuide.md

---

Docs/MoltenVK_Runtime_UserGuide.md
ExternalRevisions/README.md
README.md

Fix several document typos.

---

MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKBuffer.h
MoltenVK/MoltenVK/GPUObjects/MVKBuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKDeviceMemory.h
MoltenVK/MoltenVK/GPUObjects/MVKDeviceMemory.mm
MoltenVK/MoltenVK/GPUObjects/MVKImage.h
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/GPUObjects/MVKResource.h
MoltenVK/MoltenVK/GPUObjects/MVKResource.mm
MoltenVK/MoltenVK/Utility/MVKFoundation.h

Support mapping and filling device memory before binding an image to it.
Support using Metal texel buffer for linear images to increase host coherency.
Includes fix for issue #163.

Device memory management changes.

---

MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm

Swapchain return VK_ERROR_OUT_OF_DATE_KHR when window resized.

---

Docs/MoltenVK_Runtime_UserGuide.md

We had some user feedback that made them believe that it wasn't possible to use layers at all with MVK.  This PR clarifies the situation.

docs:  Improve layer limitations description

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueue.h
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm
MoltenVK/MoltenVK/OS/CAMetalLayer+MoltenVK.h
MoltenVK/MoltenVK/OS/CAMetalLayer+MoltenVK.m
MoltenVK/MoltenVK/Vulkan/vulkan.mm

Only update CAMetalLayer drawableSize property during swapchain creation.

---

fetchDependencies

Fixes typos in comments in fetchDependencies.

Fix typos in comments in fetchDependencies

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

Now when we set up the `MTLRenderPassAttachmentDescriptor` for the 3D
texture, we set the `depthPlane` property instead of the `slice`
property. Combined with an appropriate setting for
`renderTargetArrayLength` in the base descriptor, this allows rendering
to a subset of a 3D texture.

Better support subviews of 3D textures.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/mvk_datatypes.h
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.h
MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.mm
MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
MoltenVK/MoltenVK/OS/MTLRenderPipelineDescriptor+MoltenVK.h
MoltenVK/MoltenVK/OS/MTLRenderPipelineDescriptor+MoltenVK.m
MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm
MoltenVKShaderConverter/MoltenVKShaderConverter.xcodeproj/xcshareddata/xcschemes/MoltenVKShaderConverter.xcscheme

 Support polygonMode VK_POLYGON_MODE_POINT.

---

MoltenVK/MoltenVK/GPUObjects/MVKDeviceMemory.mm

Allow linear images to use host-coherent memory. But map its internal
storage mode to `MTLStorageModeManaged`, so we know that we need to keep
it in sync manually.
Also, only do this check at all on Mac. iOS has no problem with shared memory
for images.

MVKDeviceMemory: Relax memory requirements for linear images.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

Fix memoryTypes order on macOS to match spec

---

MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm

A bit that I missed in my initial change to add this.

MVKImage: Support image views of 2D multisample array images.

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

Setting that usage bit on a non-renderable format, especially a
compressed one, can cause Metal to crash. (And I mean crash, without
raising an assertion failure.)

MVKImage: Don't set MTLTextureUsageRenderTarget for non-blittable formats.

---

MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

The original author confirmed it is no longer necessary.

Remove needless disablement of the fragment aux buffer.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.h
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm
MoltenVK/MoltenVK/GPUObjects/MVKSync.mm
MoltenVK/MoltenVK/OS/CAMetalLayer+MoltenVK.h
MoltenVK/MoltenVK/OS/CAMetalLayer+MoltenVK.m
MoltenVK/MoltenVK/Utility/MVKFoundation.h

- Increase max swapchain images to 3.
- Return VK_TIMEOUT even on zero wait if fences not signalled.
Fixes issues #429 & #430.

Fix issues #429 & #430.

---

Docs/Whats_New.md
MoltenVK/MoltenVK.xcodeproj/project.pbxproj
MoltenVKShaderConverter/MoltenVKShaderConverter.xcodeproj/project.pbxproj

Support iOS builds for arm64e architecture.

---

Docs/Whats_New.md
MoltenVKShaderConverter/MoltenVKShaderConverterTool/DirectorySupport.h
MoltenVKShaderConverter/MoltenVKShaderConverterTool/DirectorySupport.mm
MoltenVKShaderConverter/MoltenVKShaderConverterTool/MoltenVKShaderConverterTool.cpp
MoltenVKShaderConverter/MoltenVKShaderConverterTool/MoltenVKShaderConverterTool.h

MoltenVKShaderConverter tool returns failure exit code when any file in directory fails.

---

MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm

Dual-source blending is supported on all devices starting with iOS 11.
Cube arrays are supported on A11. Layered rendering and multiple
viewports are supported on A12.

Support some more features on iOS.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

According to the Vulkan spec:
> `sampleCounts` will be set to `VK_SAMPLE_COUNT_1_BIT` if at least one
> of the following conditions is true:
>
> * `tiling` is `VK_IMAGE_TILING_LINEAR` [we already handled this]
> * `type` is not `VK_IMAGE_TYPE_2D`
> * `flags` contains `VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT`
> * Neither the `VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT` nor the
>   `VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT` flag in
>   `VkFormatProperties::optimalTilingFeatures` returned by
>   `vkGetPhysicalDeviceFormatProperties` is set
Use the maximum cube dimensions for cube-compatible images. It makes no
difference in practice, since the maximum dimensions of a cube and a 2D
image are the same on all platforms and devices, but this seems more
correct to me.

MVKDevice: Correct returned values from getImageFormatProperties().

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

Actually turn on the `layeredRendering` feature for A12 on iOS. This
should actually allow clients to take advantage of that on A12 devices.
Turn on the `variableMultisampleRate` and `inheritedQueries` features.
`variableMultisampleRate` means that pipelines with no attachments may
have different sample counts. Since no-attachment pipelines are
emulated, we don't have that limitation anyway. If and when Metal gains
real support for no-attachment pipelines, we may have to revisit this.
`inheritedQueries` means that queries may apply to secondary command
buffers as well as primary commands. Secondary command buffers are also
emulated, and should by virtue of being inlined into the primary's
`MTLCommandBuffer` inherit any query-related state.
Use the `maxBufferLength` property of `MTLDevice` …

MVKDevice: Correct some more features and limits.

---

Common/MVKLogging.h
Common/MVKLogging.mm
MoltenVK/MoltenVK.xcodeproj/project.pbxproj
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/OS/MVKOSExtensions.h
MoltenVK/MoltenVK/OS/MVKOSExtensions.mm
MoltenVKShaderConverter/MoltenVKShaderConverter.xcodeproj/project.pbxproj

Allow logging level to be controlled via runtime environment variable.

---

MoltenVK/MoltenVK/OS/MVKOSExtensions.mm

This should be better behaved with systems that have more than one GPU
and aren't e.g. MacBooks with graphics switching.

Use the device's registryID property to locate it in IOKit.

---

Docs/MoltenVK_Runtime_UserGuide.md
README.md

Clarify Xcode version requirements in documentation.

---

Docs/Whats_New.md
fetchDependencies

Fix issue loading from Vulkan-Portability_repo_revision in fetchDependencies.
Fix #514.

Update What's New document.

---

MoltenVK/MoltenVK/OS/MTLRenderPassDescriptor+MoltenVK.m

Actually set the renderTargetArrayLength property on iOS 12.

---

MoltenVK/MoltenVK/Commands/MVKCmdDraw.mm
MoltenVK/MoltenVK/Commands/MVKCommandPipelineStateFactoryShaderSource.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm
MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm

This is currently the sum of issues I've been able to find and fix regarding tessellation. These all work to my testing but may require deeper testing due to my limited selection of hardware.

Several fixes regarding tessellation, especially in indexed and instanced rendering

---

MoltenVK/MoltenVK/Commands/MVKCmdDraw.mm
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.h
MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.h
MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.mm

Fix tessellation pipeline re-clearing attachments.

---

MoltenVK/MoltenVK/Commands/MVKCmdDraw.mm

In a tessellated draw, the vertex shader will take a `device` pointer to
the vertex count. It must be a `device` pointer, because the `constant`
AS on Mac requires 256-byte alignment, which we cannot guarantee,
particularly with an indirect draw. But, the `setVertexBytes:...` method
cannot be used with the `device` AS. So, we need yet another temporary
buffer to hold this value in the `device` AS.
Fixes #566.

Don't use setVertexBytes() for passing vertex counts.

---

MoltenVK/MoltenVK/GPUObjects/MVKBuffer.mm
MoltenVKShaderConverter/MoltenVKSPIRVToMSLConverter/SPIRVToMSLConverter.h

Fix offset of buffer view relative to buffer offset within device memory.

---

MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.h
MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

Move push constant binding to vkCmdBindPipeline() from vkCmdBindDescriptorSet().

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDeviceMemory.mm

Fix MTLHeap memory leak in MVKDeviceMemory.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm

Add `MVKQueuePerformance::nextCAMetalDrawable`.

Track performance of CAMetalLayer nextDrawable call.

---

Docs/MoltenVK_Runtime_UserGuide.md
Docs/Whats_New.md

Fixes recommendation in issue #808.

Document recommendation to use 3 swapchain images, particularly with full-screen rendering.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.h
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm

- Add MVKSwapchain::getSurfaceStatus().
Fixes issue #857.

vkQueuePresentKHR() returns VkResult for each swapchain.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

MVKPhysicalDevice::getSurfaceFormats() reduce fragility of surface format definitions.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm

Fix new and unexpected App Store failure on newly deprecated color space values.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm

Also remove use of Metal kCGColorSpaceITUR_2020_PQ to avoid App Store rejections.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h

Update MoltenVK version to 1.0.45.

---

MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/Utility/MVKFoundation.h

Quiet warnings and errors building on Xcode 12 Beta.

Enable building on xcode 12 beta

---

MoltenVK/MoltenVK/Commands/MVKCmdDraw.mm

Calling `MVKGraphicsPipeline::getTessVertexStage*State` causes a crash for non-tessellated draws due to the lack of corresponding pipeline descriptor. I moved it, together with other tessellation related variables, inside the `isTessellationPipeline` check. This should fix #989.

Initialize tessellation related variables conditionally in indirect draws

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

MVKImagePlane: account for swapchain images in get/releaseMTLTexture()

---

Common/MVKCommonEnvironment.h
Docs/MoltenVK_Runtime_UserGuide.md
Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKInstance.h
MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm
MoltenVK/MoltenVK/Utility/MVKEnvironment.h
MoltenVK/MoltenVK/Vulkan/vulkan.mm

These changes add the remaining missing features of Vulkan 1.1.
Fixes #822.

Support Vulkan 1.1.

---

MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.mm

Store action validation warnings

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm

MVKCmdCopyImage handled compressed source/uncompressed destination case correctly, but not the opposite, resulting in a partial copy.

MVKCmdCopyImage: adjust destination extent when it's compressed

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm

This can be done by copying between each slice of the 2D image and each
plane of the 3D image individually.
This was actually quite simple to implement. I don't know why I punted
on this.

MVKCmdCopyImage: Support copies between 3D and 2D images.

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm

For these, we must use the `depthPlane` property to set the layer to
clear, and we must iterate over the image's depth, since the layer count
will be 1 in this case.

MVKCmdClearImage: Support clears of 3D images.

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

We were looking in the wrong chain for the
`VkImagePlaneMemoryRequirementsInfo` struct. We were also failing to
call through to the `MVKImageMemoryBinding` to get dedicated
requirements, which broke dedicated memory.
Clearly, I failed to properly review the patch which refactored
`MVKImage` for `VK_KHR_sampler_ycbcr_conversion`.

MVKImage: Fix broken getMemoryRequirements2().

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

Only do the managed-storage check on Mac.

Fix iOS build again.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

Fall through to the 2D case, so all the special handling for 2D is used
for 1D as well. Also, make sure 1D doesn't report multisampling or
support for 420 subsampled formats. Vulkan doesn't support 1D
multisampled textures anyway.
Also, clear the `VkImageFormatProperties` struct if the format is not
supported with the given parameters. Some tests seem to expect this.

MVKDevice: Fix reported image format properties for 1D images as 2D.

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm

This makes the clearing tests from the CTS marginally faster, by about 30 ms in many cases.

MVKCmdClearImage: Use layered rendering when possible.

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm

When calculating the vertices, we need to use the render area's
extent--but only if the implementation supports constraining the render
area using `renderTargetWidth` and `renderTargetHeight`. Otherwise, the
quad will be stretched and/or squashed because of the render area
constraint.

MVKCmdClearAttachments: Account for the renderArea.

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm

When the extent covers both the source and destination images
completely, we can use the copy method on `MTLBlitCommandEncoder` which
can copy multiple slices at once. This should hopefully reduce CPU
overhead and command buffer memory usage.

MVKCmdCopyImage: Use the method to copy multiple slices when possible.

---

MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm

I've noticed that in some tests, the clear values seem to be off by
about one ULP, and the tests subsequently fail. This should cause Metal
to round up instead of down and fix those tests.

MVKPixelFormats: Add 0.5 ULP to clear values for normalized formats.

---

MoltenVK/MoltenVK/OS/MVKGPUCapture.mm

For some reason, when we create the `MTLCaptureScope` with capture
enabled, in addition to the reference from object creation, Metal
retains the object for no apparent reason in the base `MTLCaptureScope`
initializer. This causes us to leak the capture scope--and with it, the
queue. Let's hope Apple isn't doing anything with that extra reference.
I admit this is a horrible kluge and we shouldn't need it. But without this,
I can't get through the CTS without it hanging.

MVKGPUCapture: Make sure the MTLCaptureScope has only one reference.

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

If the texture is not properly aligned, creation will fail. Make sure
we ask for enough memory to hold all planes with alignment, or a plane
could wind up beyond the bounds of the heap.

MVKImage: Make sure plane heap offsets are properly aligned.

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

Transfer commands don't use image views. The transfer usages, then,
shouldn't figure into whether it's valid to use a view a particular way.

MVKImageView: Always ignore transfer usages.

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm
MoltenVK/MoltenVK/Commands/MVKCommandPipelineStateFactoryShaderSource.h
MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.mm

I wanted to do this in the last release, but I ran out of time.
It doesn't seem to provide much speed up.

MVKCmdBlitImage: Use layered draws when possible.

---

MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm

Metal's validation layer doesn't like it when we render to both a 2D and
a 3D texture with layered rendering. Work around this by not setting the
`renderTargetArrayLength` if it would be one and we are rendering to
mixed 2D and 3D textures.
If the pipeline sets `[[render_target_array_index]]`, we're hosed either
way. Perhaps this is why Vulkan has a special flag,
`VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT`, intended for rendering to 3D
textures.

MVKCommandEncoder: Don't set renderTargetArrayLength for mixed 2D/3D renders.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

I misread the table when I added this.

MVKPhysicalDevice: Enable texture swizzle on all Apple GPUs.

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

Detect more swizzle patterns that are equivalent to identity, so that Metal does not disable usage capabilities that we want.

MVKImage: Avoid swizzling storage and/or attachment image views.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h

- Update `VK_MVK_MOLTENVK_SPEC_VERSION` to `30`.
- Update What's New document.

Update MoltenVK to version 1.1.2.

---

MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm

Metal does not allow color write masks with this format where some but
not all of the channels are disabled. Either all must be enabled or none
must be enabled. Presumably, this is because of the shared exponent.
This is just good enough to stop the validation layer from violently
terminating the program. To implement this properly requires using
framebuffer fetch, with a change to SPIRV-Cross. Luckily, the only GPUs
that support `RGB9E5` rendering also support framebuffer fetch.
Honestly, I don't understand why Apple's drivers don't do this.

MVKGraphicsPipeline: Fix color write mask with RGB9E5 RTs.

---

MoltenVKShaderConverter/MoltenVKShaderConverter/SPIRVReflection.h

Previously if you had multiple vertex shader entry points in 1 SPIR-V binary file it would return a list of all vertex outputs instead of only the outputs from the selected entry point. This causes mismatches later in the [SPVtoMSLConverter](https://github.com/KhronosGroup/MoltenVK/blob/master/MoltenVKShaderConverter/MoltenVKShaderConverter/SPIRVToMSLConverter.cpp#L267).
This solves that issue by looping over the active interface variables instead.

SPIRVReflection: Multiple entry point support for getShaderOutputs

---

.github/workflows/CI.yml

GitHub Actions: Update Xcode to 12.3

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

Advertise macOS M1 GPU as VK_PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVKShaderConverter/MoltenVKShaderConverterTool/OSSupport.mm

Fix build on Xcode 11.

---

.github/workflows/CI.yml

This is an alternative method of achieving #1234

CI enhancements - update to Xcode 12.4, add (legacy) Xcode 11.7 build

---

Demos/Cube/Cube.xcodeproj/xcshareddata/xcschemes/Cube-macOS.xcscheme
Docs/Whats_New.md
MoltenVK/MoltenVK/Utility/MVKBlockObserver.m

Add ability to instrument profile Cube demo on macOS.
Fixes #1383.

Fix small memory leak during swapchain creation.

---

.gitignore
Docs/Whats_New.md
MoltenVKPackaging.xcodeproj/project.pbxproj
Scripts/runcts

Update `.gitignore` to ignore CTS artifacts in `Scripts` directory.

Add Scripts/runcts script as a convenience for running Vulkan CTS tests.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKShaderModule.mm
MoltenVK/MoltenVK/GPUObjects/MVKVulkanAPIObject.mm

Fix Metal object retain-release errors in assignment operators.

---

MoltenVKShaderConverter/MoltenVKShaderConverter/SPIRVReflection.h

Maintain the incrementing location throughout the structure traversal.

fix for #1501

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKSync.h
MoltenVK/MoltenVK/GPUObjects/MVKSync.mm
MoltenVK/MoltenVK/Utility/MVKEnvironment.cpp
MoltenVK/MoltenVK/Utility/MVKEnvironment.h
Scripts/runcts

Merge SingleQueueSemaphore branch into master

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm

Fix: Invalid blit offsets

---

MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.mm

- Set Metal depth store action to `MTLStoreActionDontCare` when depth attachment exists, but depth component has been swizzled away.
Fixes last part of #1579.

Avoid Metal validation warning when depth component swizzled away

---

MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm

Fix a warning I accidentally added in #1898

Fix reorder-ctor warning

---

Docs/Whats_New.md
MoltenVK/MoltenVK/API/mvk_config.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.h
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/Utility/MVKEnvironment.cpp
MoltenVK/MoltenVK/Utility/MVKEnvironment.h

https://developer.apple.com/videos/play/wwdc2023/10127/?time=540
On an M1 Pro Macbook Pro 16" maximumConcurrentCompilationTaskCount goes from 2 to 8

Allows maximizing the concurrent executing compilation tasks.

---

MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm

Fix deadlock when reporting debug message on MVKInstance destruction.

---

MoltenVK/MoltenVK/GPUObjects/MVKImage.mm

Fix up for #2164, fixes #2168.

Fix uninitialized MVKImage member.

---

MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm

Prevent deadlock if working on non-main thread

---

MoltenVK/MoltenVK/GPUObjects/MVKDescriptorSet.mm

- Argument buffer offset into `MTLBuffer` must respect Metal buffer alignment limits.

Fixes from Vulkan SDK 1.3.290 testing.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/Utility/MVKEnvironment.h

Set value of minSubgroupSize on AMD RX6600 to 32

---

MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm

Related https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8408

Fix debug utils messenger leak

---

MoltenVK/MoltenVK.xcodeproj/project.pbxproj
MoltenVK/MoltenVK/GPUObjects/MVKImage.mm
MoltenVK/MoltenVK/Utility/MVKBitArray.h
MoltenVKShaderConverter/MoltenVKShaderConverter.xcodeproj/project.pbxproj

- Add `-Wunused-but-set-variable` to catch additional unused variables.
- Remove unused variable in `MVKSampler()` constructor.
- Include `<functional>` header in `MVKBitArray.h`.

Minor cleanups.

---

MoltenVK/icd/MoltenVK_icd.json

Update ICD API version to 1.3

---

MoltenVK/MoltenVK/Commands/MVKCmdDraw.mm

* Remove CPU path from Uint8 index handling as it does not account for pending buffer write or copy from the GPU side.
* Fix offsets of temporary buffers for index buffer handling not being accounted for.

Remove CPU path from Uint8 index handling.

---

MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm

- Populate `VkPhysicalDeviceVulkan14Properties` layout structs dynamically. Static population caused crash because content sizing is determined dynamically.
- Add missing switch breaks during feature struct population.
- Revert to simpler mechanism for retaining pNexts during version feature and property structs.
- Clear and populate `MVKPhysicalDevice::_vulkan14NoExtFeatures` and `_enabledVulkan14NoExtFeatures`.

Fix crash and bad data during populating feature and property structs.

---

MoltenVK/MoltenVK.xcodeproj/project.pbxproj

- Suppress clang `vla-cxx-extension` warning.

Support Xcode 16.3

---

MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm

- When using resource residency sets, abort descriptor layout binding checking as soon as it is determined that the Metal argument buffer for the descriptor set needs to be bound. Previous code continued to needlessly iterate through all layout bindings.
- Document the logic better in code comments.

Minor optimization in processing resource residency sets.

---

Docs/Whats_New.md
MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm

vkDeviceWaitIdle() & vkQueueWaitIdle() wait even on VK_ERROR_DEVICE_LOST.

---

MoltenVK/MoltenVK/Commands/MVKCmdTransfer.mm

* Use temp buffer for `maintenance8` color<->depth image copy since Metal does not allow taking a depth pixel view of a color image.
* Fix temp buffer image copy path causing device loss due to not accounting for copy layers when calculating temp buffer size.
Fixed some Metal assertions and device losses I encountered with image copies in practice.

Fix color-depth image copies and image copies using buffer with multiple layers.
